### ISSUE TITLE
Criação do DAO para a classe Comentario método inserir

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#10]

**Comment by FernandoMacielS** [comment]
Corrigido. Adição da letra "s" em "comentario".

**Comment by Ronneesley** [comment]
De fato, deve incluir curtidas, data, postagem e resposta antes que eu encerre a tarefa.

**Comment by FernandoMacielS** [comment]
> "De fato, deve incluir curtidas, data, postagem e resposta antes que eu encerre a tarefa."

Atualizado.

**Comment by Ronneesley** [comment]
A indentação não está boa na linha 110. Mesmo assim encerro a atividade. Mas aguardo a correção.
