### ISSUE TITLE
Protótipo do gerenciamento de conta

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#100]

**Comment by Ronneesley** [comment]
Reveja o protótipo segundo o RF13 da documentação.
Ao terminar a figura, utilize a opção "Fit content" do Pencil e exporte a imagem em PNG para a pasta **resultados**

**Comment by EduardoOliveiraSilva** [comment]
não consegui colocar um captcha!

**Comment by Ronneesley** [comment]
Ok
