### ISSUE TITLE
Protótipo para convidar pessoas a participarem de grupos

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#101]
RF14

**Comment by FernandoMacielS** [comment]
> "RF14"

Criação concluída.

**Comment by Ronneesley** [comment]
Qual o nome do arquivo do pencil e onde está a imagem em PNG?

**Comment by FernandoMacielS** [comment]
>Qual o nome do arquivo do pencil e onde está a imagem em PNG?

GitHub\redesocial\prototipos arquivo "grupo_convidar".
Não tinha visto os arquivos em PNG, vou colocar na mesma pasta que estão os demais, nesse mesmo diretório, na pasta "resultados".

**Comment by Ronneesley** [comment]
Ok, aguardo o PNG

**Comment by FernandoMacielS** [comment]
> "Ok, aguardo o PNG"

Adicionado.

**Comment by Ronneesley** [comment]
Isso seria no chat?
Onde está o nome do grupo ao qual estou convidando alguém?

**Comment by FernandoMacielS** [comment]
> Isso seria no chat?

Bom, quando o usuário clica-se no botão "CONVIDAR" ele abriria essa "mini-janela" do "PASSO 2" já com os seus "Amigos" que se tem adicionado em forma alfabética e com o sistema de busca por letra/nome e a opção de adicionar por "email".

> Onde está o nome do grupo ao qual estou convidando alguém?

Posso estar colocando na mensagem do "PASSO 4", e se ficar mais intuitivo, no lugar de "PASSO 3" trocar o nome por "PASSO 2.1" e "PASSO 4" por "PASSO 3".

**Comment by FernandoMacielS** [comment]
Enviado o designer de convite para grupos e uma pré-página de grupo.
Se resolver usar a página de grupo adiciona uma estrela a mais pra um necessitado.

**Comment by Ronneesley** [comment]
Agora está muito bom. Gostaria apenas que tirasse os espaços do nome do arquivo: **pagina grupo temporaria para criação do botão convidar**. 
Irei considerar como duas atividades tendo em vista a qualidade final e abonarei o prazo de entrega que havia marcado como atrasado.
