### ISSUE TITLE
Protótipo do chat (lista de pessoas ativas e inativas)

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#103]

**Comment by Jonathanss123** [comment]
Boa noite!! Rone mandei o Protótipo, dps confere lá.

**Comment by Ronneesley** [comment]
Jonathan, retire da pasta com seu nome e coloque o projeto na pasta de protótipos e o PNG na pasta resultados.
Ajuste no Pencil as margens, está gerando uma imagem grande demais.
Acho que está parecendo demais o facebook, você pode pensar em algo diferente.

**Comment by Jonathanss123** [comment]
Ronne, mandei as Correções solicitadas.

**Comment by Ronneesley** [comment]
Ok
