### ISSUE TITLE
Criação da classe EstadoBO

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#105]
Seguir os moldes da classe UsuarioBO e PaisBO

**Comment by dmcardoso** [comment]
Concluído

**Comment by Ronneesley** [comment]
Oi Daniel, está muito bom, mas no estado também é obrigatório preencher o país.
Assim que colocar a validação fecho a tarefa.

**Comment by dmcardoso** [comment]
Corrigido, acredito que esteja certo


________________________________
De: Ronneesley Moura Teles <notifications@github.com>
Enviado: quinta-feira, 10 de agosto de 2017 17:13
Para: Ronneesley/redesocial
Cc: DanielIFGoianoSI; Assign
Assunto: Re: [Ronneesley/redesocial] Criação da classe EstadoBO (#105)


Oi Daniel, está muito bom, mas no estado também é obrigatório preencher o país.
Assim que colocar a validação fecho a tarefa.

**Comment by Ronneesley** [comment]
Oi Daniel, veja o método *validar()* na classe *UsuarioDAO*.
As validações são feitas no mesmo método, no seu caso você criou outro método chamado *validarPais()*.
A validação é feita verificando apenas se o país foi preenchido, assim:
*if (dto.getPais() == null)*
Aguardo a correção.

**Comment by dmcardoso** [comment]
corrigido

Em 11 de agosto de 2017 11:20, Ronneesley Moura Teles <notifications@github.com<mailto:notifications@github.com>> escreveu:

Oi Daniel, veja o método validar() na classe UsuarioDAO.
As validações são feitas no mesmo método, no seu caso você criou outro método chamado validarPais().
A validação é feita verificando apenas se o país foi preenchido, assim:
if (dto.getPais() == null)
Aguardo a correção.

**Comment by Ronneesley** [comment]
Perfeito, existe um detalhe no meio de tudo, mas vou abrir outra *issue* depois.
