### ISSUE TITLE
Criação do DAO PostagemAlbum método excluir()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#106]

**Comment by Ronneesley** [comment]
Mais uma atividade, caso queira continuar.

**Comment by WesleyMFelix** [comment]
Essa já foi enviada! Tive um problema com o meu notebook e enviei pelo do Igor e mesmo saindo da conta dele me parece que foi upado com o nome del!

**Comment by WesleyMFelix** [comment]
Atividade enviada!

**Comment by Ronneesley** [comment]
Ok
