### ISSUE TITLE
Criação do protótipo de cadastro de artigos.

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#109]
Estou pensando em seguir algumas vertentes diferentes e gostaria que fosse possível cadastrar artigos científicos na rede social para que fossem objetos de discussão.
Gostaria então que fizesse um protótipo, permitindo a pessoa informar o título, autores, data, revista, área e resumo do artigo.

**Comment by Ley00** [comment]
De uma olhada para ver se precisa modificar algo, o nome é cadastro_artigos

**Comment by Ronneesley** [comment]
Favor exportar primeiro o PNG para a pasta **resultados**.
Aguardo.

**Comment by Ley00** [comment]
Pronto

**Comment by Ronneesley** [comment]
Ficou muito bom, somente preencha os campos em branco como ISSN, título e resumo.
Já vou considerar a tarefa pronta, mas aguardo essa atualização. Parabéns.
