### ISSUE TITLE
Criação do DAO para a entidade Postagem método inserir

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#11]

**Comment by Ronneesley** [comment]
Brener, no SQL o *id* é autoincremental portanto não deve ser informado no SQL, consequentemente a linha 36 *pstmt.setId(1,p.id);* não existe.
Além disso a forma de obter os dados nas linhas 36 a 39 devem usar o método get, portanto getCurtidas(), getDescricao(), getData().
Aguardo as correções, quando terminar me avise.

**Comment by BrenerGomesSI** [comment]
Realizei as correções como solicitado.

Em 10 de agosto de 2017 09:33, Ronneesley Moura Teles <
notifications@github.com> escreveu:

**Comment by Ronneesley** [comment]
Novamente, estamos mais pertos desta vez. O nome da tabela não é *postagem*, confira no DER.
Você colocou os métodos *getCurtidas(), getDescricao(), getData()* no lugar errado.
Fiz dois exemplos para ti:
*pstmt.setInt(1, p.getCurtidas());* e
*pstmt.setDate(3, new java.sql.Date(p.getData()));*
Já submeti no código.
Então arrume apenas *pstmt.getDescricao(2,p.descricao);* para que eu termine a atividade.

**Comment by BrenerGomesSI** [comment]
Tinha confundido o local dos get, alterei a tabela do bd.

Em 10 de agosto de 2017 16:12, Ronneesley Moura Teles <
notifications@github.com> escreveu:

**Comment by Ronneesley** [comment]
Oi Brener, ainda está errado o comando:
*pstmt.setDescricao(2,p.getDescricao());*
O *pstmt* tem apenas métodos *setInt()*, *setString()*, *setDate()*. Assim vc deve olhar o tipo do atributo descrição.

**Comment by BrenerGomesSI** [comment]
HM entendi estava com esta duvida porque vi alguns DAO com e outros sem
estes comandos. Obrigado vou alterar.

Em sexta-feira, 11 de agosto de 2017, Ronneesley Moura Teles <
notifications@github.com> escreveu:

**Comment by BrenerGomesSI** [comment]
Realizei a alteraçao direto pelo site da GitHub.

Em 11 de agosto de 2017 14:23, Brener Gomes SI <brenerifg@gmail.com>
escreveu:

**Comment by Ronneesley** [comment]
Perfeito.
