### ISSUE TITLE
Criação do DAO PostagemAlbum método alterar()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#110]

**Comment by Ronneesley** [comment]
Gusttavo converse com o @PHRA-IFGOIANO sobre como ele pretende fazer a atividade #85, pois são duas atividades muito parecidas em entidades diferentes. Talvez juntos consigam resolver as duas mais rapidamente.

**Comment by gusttavogomes** [comment]
Dei commit, aguardo correção.

**Comment by gusttavogomes** [comment]
Terminei as correções. Finalizado.

**Comment by Ronneesley** [comment]
Perfeito.
