### ISSUE TITLE
Criação do HTML de solicitação de amizade e envio de mensagens

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#114]
Seguir os protótipos definidos em #102

**Comment by Ronneesley** [comment]
Agora a criação do HTML da questão #102 conforme o que foi prototipado.

**Comment by IgorJustinoRodrigues** [comment]
Acabei de mandar, não tenho certeza quanto ao de mensagem.

2017-08-10 11:45 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Está muito bom, parabéns, somente separe o botão *close.png* nas três operações distintas.

**Comment by IgorJustinoRodrigues** [comment]
Acabei de mandar a correção.

2017-08-11 11:35 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Perfeito.
