### ISSUE TITLE
Criação do HTML do cadastro de grupos de usuários

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#115]

**Comment by Ronneesley** [comment]
Seguir o que foi definido em #97

**Comment by WesleyMFelix** [comment]
Reenviado!

_Sent from my Motorola Moto G (5) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Ronneesley** [comment]
Wesley a imagem do grupo está aparecendo fora do quadro, gostaria que desse uma olhada.
Mesmo assim considero fechada a atividade.
