### ISSUE TITLE
Criar classe CidadeBO

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#116]

**Comment by Ronneesley** [comment]
Segue mais uma atividade caso queira continuar pontuando.

**Comment by Ronneesley** [comment]
Veja as classes *UsuarioBO* e *PaisBO* para conseguir criar a sua.

**Comment by LuckasAzevedo** [comment]
OK

**Comment by Ronneesley** [comment]
Lucas olhe novamente a classe *UsuarioBO* fiz lá uma validação de chave estrangeira para servir de exemplo para ti.
Note que você criou um método *validarEstado()* para validar o estado, este código deveria estar no mesmo método *validar()*.

**Comment by LuckasAzevedo** [comment]
Okay.

**Comment by Ronneesley** [comment]
Perfeito. Somente corrija o texto *Insira o nome **dacidade**.*
Mas já vou encerrar a tarefa.

**Comment by LuckasAzevedo** [comment]
feito

2017-08-11 15:57 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:
