### ISSUE TITLE
Criar classe ComentarioBO

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#117]

**Comment by Ronneesley** [comment]
Caso queira continuar pontuando... Veja as classes *UsuarioBO* e *PaisBO* para criar a sua.

**Comment by adallberto** [comment]
Ok! Classe Criada!

**Comment by Ronneesley** [comment]
Adalberto, veja os atributos da classe de comentário. Todos os campos que foram marcados como obrigatórios no DER devem ser validados.
Evite no código a presença de duas ou mais linhas em branco seguidas.

**Comment by Ronneesley** [comment]
Perfeito, mas faltou o acento em **comentario**.
