### ISSUE TITLE
Criar classe AlbumBO

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#118]

**Comment by Ronneesley** [comment]
Mais uma caso queira continuar pontuando veja as classes *UsuarioBO* e *PaisBO* para criar a sua.

**Comment by aandreysr** [comment]
classe AlbumBO criada

**Comment by Ronneesley** [comment]
Andrey, o atributo *data* também deve ser obrigatório. Confira no DER.
Aguardo a resposta/modificação,, se ela for obrigatória ou não.

**Comment by aandreysr** [comment]
Eu retirei o .trim da validação da data, nao tinha colocado inicialmente porque achei que a data seria gerada pelo sistema

**Comment by Ronneesley** [comment]
A validação da data é assim: *dto.getData() == null*
Aguardo a correção, mas já fecho a atividade.
