### ISSUE TITLE
Criar a especificação de requisitos para cadastro de artigos científicos

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#122]

**Comment by aandreysr** [comment]
Professor, não estou conseguindo compilar o codigo no Latex por conta de erro nos arquivos da pasta capitulos/especificacao_requisitos, e quando eu corrijo um, outros erros aparecem na pasta de capitulos

**Comment by aandreysr** [comment]
problema resolvido

**Comment by aandreysr** [comment]
Fiz o codigo no latex e salvei, porém o arquivo nao compila por vário erros em outros arquivos, mas o codigo está salvo em especificacao_requisitos.tex

**Comment by Ronneesley** [comment]
Aqui compilou normalmente sem erros.
Veja que o texto: **O sistema deve permitir o cadastro de artigos** é suficiente.
A menção da quantidade deve ficar na seção de especificação apenas, veja que está redundante estar esta menção nas duas seções: descrição e especificação.

Aguardo a correção e a compilação ai, busque ver o que está dando erro na sua máquina.
Lá no site http://www.profronneesley.analistasi.com.br/index.php?operacao=PaginaDinamica&pagina=latex tem todos os pré-requisitos do LaTeX.
Veja que o TexMaker instala os pacotes faltantes um a um, então quando for compilar tem que deixar ele instalar.

**Comment by aandreysr** [comment]
Instalei tudo novamente nas ultimas versões, e quando compilei ele instalou os pacotes faltantes, mas continuou com o mesmo erro ! Undefined control sequence. l.1 \chapter {Especificação de requisitos e outros vários desse mesmo tipo

**Comment by aandreysr** [comment]
poblema resolvido e compilado com as alterações

**Comment by Ronneesley** [comment]
Andrey faltou mencionar os campos que devem estar no cadastro. Veja o protótipo.

**Comment by aandreysr** [comment]
Já atualizei o arquivo

**Comment by Ronneesley** [comment]
Tem duas tabelas seguidas do RF21, elas devem ser só uma.

**Comment by aandreysr** [comment]
concertei esse e outros erros

**Comment by Ronneesley** [comment]
Continuo vendo no PDF (documentacao.pdf) duas tabelas distintas. Parece que você não está compilando o arquivo **documentacao.tex**

**Comment by aandreysr** [comment]
Sim, tinha dado um problema no commit do git, logo depois eu consegui e
agora esta tudo certo

2017-08-14 13:53 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Ainda são duas tabelas agora tem dois nomes RF21 e RF22.
Não existe a RF22, este texto da especificação deve estar na RF21.
A descrição do RF21 não está boa, deveria ser: *O sistema deve fornecer um cadastro de artigos científicos*.

**Comment by aandreysr** [comment]
Corrigido

Em 14 de ago de 2017 15:49, "Ronneesley Moura Teles" <
notifications@github.com> escreveu:

**Comment by Ronneesley** [comment]
Estamos quase chegando lá.
1) Os RFs 19 e 20 devem ser excluídos.
2) Acentuação: rever ortografia
3) Favor incluir a URL do artigo nos campos.
Incrementar o texto especificando a figura do protótipo, ex.: conforme a Figura 14.
Após isso encerro a atividade.

**Comment by aandreysr** [comment]
Feito, acredito que todos os erros foram ajustados

Em 14 de ago de 2017 18:38, "Ronneesley Moura Teles" <
notifications@github.com> escreveu:

**Comment by Ronneesley** [comment]
Ainda estou achando a escrita confusa, veja em vez de: 

> O sistema deve conter as seguintes opções: o usuário concordar ou não as normas de envio,
caso não concorde o artigo nao é cadastrado, para escolha do idioma do artigo, escolha do
nome da revista, campo para informar o ISSN, nome dos autores, data, escolha da área do
conhecimento, tı́tulo da publicação, campo para o resumo do artigo e opção de salvar ou
cancelar, conforme a Figura 14. 

Que tal:

O cadastro de artigos científicos no sistema somente será realizado com o aceite das condições de publicação por parte dos autores. Dada a permissão, os autores devem preencher o idioma, nome da revista, ISSN (International Standard Serial Number), seus nomes, data, área do conhecimento, título e resumo do artigo. 

Nota o seguinte: faltou mencionar a URL do artigo e o arquivo físico do artigo em PDF.

**Comment by Ronneesley** [comment]
Como estes itens não estão previstos no protótipo gostaria que adicionasse.

**Comment by Ronneesley** [comment]
Outro detalhe, não coloquei no texto mas referencie a **figura** como fez no seu texto, porém use o comando \ref{} para isso, porque a numeração pode mudar.

**Comment by Ronneesley** [comment]
Andrey, as tabelas 5, 6 e 7 não existem, nelas você criou RNFs 05, 06 e 07.

**Comment by aandreysr** [comment]
então devo excluir os RNFs 05, 06 e 07?

2017-08-16 10:06 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Sim

**Comment by aandreysr** [comment]
Fiz todas as alterações

Em 16 de ago de 2017 18:26, "Ronneesley Moura Teles" <
notifications@github.com> escreveu:

**Comment by Ronneesley** [comment]
Edite a figura do protótipo para condizer com a especificação.
URL e arquivo em PDF.
Em seguida fecho a tarefa.

**Comment by aandreysr** [comment]
Os arquivos do pencil assim como alguns resultados dos protótipos não estão
mais na pasta do repositório

Em 17 de ago de 2017 18:05, "Ronneesley Moura Teles" <
notifications@github.com> escreveu:

**Comment by aandreysr** [comment]
Foi um erro de pull, já resolvido

Em 18 de ago de 2017 13:21, "Andrey Silva" <aandreysr@gmail.com> escreveu:

**Comment by aandreysr** [comment]
Alterações feitas

Em 18 de ago de 2017 13:22, "Andrey Silva" <aandreysr@gmail.com> escreveu:

**Comment by Ronneesley** [comment]
Ok
