### ISSUE TITLE
Criar a documentação do caso de uso: Fazer Login

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#123]

**Comment by dmcardoso** [comment]
Bom dia, Ronne, fui realizar a tarefa no documento .tex de casos de uso e o mesmo está com aqueles caracteres estranhos que deu no netbeans. Posso apagar pra conferir o que fiz na compilação ou deixo lá mesmo?


________________________________
De: Ronneesley Moura Teles <notifications@github.com>
Enviado: sexta-feira, 11 de agosto de 2017 20:44
Para: Ronneesley/redesocial
Cc: DanielIFGoianoSI; Mention
Assunto: Re: [Ronneesley/redesocial] Criar a documentação do caso de uso: Fazer Login (#123)


Assigned #123<https://github.com/Ronneesley/redesocial/issues/123> to @DanielIFGoianoSI<https://github.com/danielifgoianosi>.

**Comment by dmcardoso** [comment]
Preenchi as informações do meu caso de uso, porém não compilei, devido o erro que comentei. Se houver algum problema relacionado ao que fiz corrijo. 
Aguardo correção.

**Comment by Ronneesley** [comment]
Isso, aguardo a correção. Lembre-se não é só ir apagando, é ver o que deu conflito e ver qual o mais atual.

**Comment by dmcardoso** [comment]
Como ficou?

**Comment by Ronneesley** [comment]
Alguns meros detalhes:
1) redesocial escreva rede social;
2) use ; no final de cada item, exceto o último que é .
3) **Após** inserir as informações...
4) Servidor valida as informações digitadas pelo usuário e **abre uma sessão para o usuário**
5) Referencie as figuras do protótipo, ex:
          Entre o item 1 e 2) o sistema exibe a página de login (Figura 1)

**Comment by dmcardoso** [comment]
corrigido


________________________________
De: Ronneesley Moura Teles <notifications@github.com>
Enviado: quarta-feira, 16 de agosto de 2017 00:40
Para: Ronneesley/redesocial
Cc: DanielIFGoianoSI; Mention
Assunto: Re: [Ronneesley/redesocial] Criar a documentação do caso de uso: Fazer Login (#123)


Alguns meros detalhes:

  1.  redesocial escreva rede social;
  2.  use ; no final de cada item, exceto o último que é .
  3.  Após inserir as informações...
  4.  Servidor valida as informações digitadas pelo usuário e abre uma sessão para o usuário
  5.  Referencie as figuras do protótipo, ex:
Entre o item 1 e 2) o sistema exibe a página de login (Figura 1)

**Comment by Ronneesley** [comment]
Em vez de Figura: 1, escreva Figura 1. 
No caso do segundo item coloque entre parênteses antes do fim da frase.
Utilize subitens para descrever os tratamentos dos fluxos alternativos.
Releia seu texto.

**Comment by dmcardoso** [comment]
Ronne, acredito que quanto aos dois primeiros itens, foi corrigido. Em relação aos subitens, fiquei em dúvida se é para descrever uma possível solução ou os motivos de ter gerado o fluxo alternativo

**Comment by dmcardoso** [comment]
Corrigido,

**Comment by Ronneesley** [comment]
O documento PDF não está sendo gerado. Aguardo a correção.

**Comment by dmcardoso** [comment]
Corrigido. O erro estava no caso de uso 7, e havia apagado o que eu tinha feito. peguei no histórico e adicionei novamente.
Aguardo a resposta.

2017-08-26 13:17 GMT-03:00 Ronneesley Moura Teles <notifications@github.com<mailto:notifications@github.com>>:

O documento PDF não está sendo gerado. Aguardo a correção.

**Comment by Ronneesley** [comment]
Ok
