### ISSUE TITLE
Criar a documentação do caso de uso: Sair

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#124]

**Comment by LuckasAzevedo** [comment]
Esta em branco modelo a ser seguido.

**Comment by Ronneesley** [comment]
Certamente, o modelo é só a tabela em branco mesmo.
Veja as aulas do semestre passado.

**Comment by LuckasAzevedo** [comment]
ok, foi feito

**Comment by Ronneesley** [comment]
Lucas, utilize **Deslogar** como nome do caso de uso, seguindo o diagrama da pasta de projeto.
Quais as pós-condições/garantias?
Você continua descrevendo o login como fluxo básico. O seu fluxo básico é deslogar.
Utilize subtópicos nos fluxos alternativos para estruturá-los

**Comment by LuckasAzevedo** [comment]
ok, feito,Favor verificar se há alterações a fazer.

Em 24 de agosto de 2017 15:18, Ronneesley Moura Teles <
notifications@github.com> escreveu:

**Comment by Ronneesley** [comment]
Lucas você descreveu o fluxo básico na divisão de interesse.

**Comment by LuckasAzevedo** [comment]
ok ,  concertado

**Comment by Ronneesley** [comment]
Você está falando como a pessoa deve proceder na parte de interesse.
O processo fica no fluxo básico.

INTERESSE: *"Deseja sair da rede social"*
PROCESSO: *"clicando no icone retangular proximo a foto como mostra a figura 7"*.

Obviamente você tem que adaptar o seu texto. Figura 7 é com F maiúsculo.

**Comment by LuckasAzevedo** [comment]
Feito, aguardo resposta!

**Comment by LuckasAzevedo** [comment]
Feito, aguardo resposta!

**Comment by Ronneesley** [comment]
Ok
