### ISSUE TITLE
Criar a documentação do caso de uso: Cadastrar-se

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#125]

**Comment by gusttavogomes** [comment]
Os casos de uso sobre o cadastro for inserido na documentação, aguardo correção.
Caso estiver tudo okay, aguardo mais tarefas.

**Comment by Ronneesley** [comment]
Veja o andamento dos protótipos #93 e #94, pois existem mais itens a ser configurado no cadastro.
Mude o nome do caso de uso para: **Realizar cadastro**
O servidor não entra como um interessado.

No fluxo básico, fale onde o usuário aciona as opções, ex.: O usuário aciona a opção "Criar Conta"
No fluxo alternativo, use um *\begin{itemize}* dentro de outro *\begin{itemize}* para criar uma hierarquia, para facilitar o entendimento.

**Comment by gusttavogomes** [comment]
Arrumei o caso de uso, aguardo resposta do @Lucianodcb e do @EXOxShiro para ver se precisa acrescentar mais coisas.

**Comment by Ronneesley** [comment]
Está ficando muito bom.  Apenas no fluxo básico deixe os itens todos no mesmo nível. A partir do 4° item você parou de falar o que é feito e quem faz. Veja o 4° item poderia ser assim: O sistema exibe a segunda etapa do cadastro. 

Nos itens seguintes você começou a colocar o que pode ser feito e não o que deve ser. Lembre-se o que pode ser feito deve ser expresso no fluxo alternativo. Reveja a escrita. Aguardo as correções.

**Comment by gusttavogomes** [comment]
Já fiz as alterações.

**Comment by Ronneesley** [comment]
Está ficando muito bom.
A hierarquia das duas últimas situações do fluxo alternativo deve ser o mesmo nível.
Faltou descrever o que acontece quando ele clica no link de confirmação de e-mail.

No primeiro item: "Usuário preenche os campos de nome, sobrenome**X**, e-mail e data de nascimento", retire o espaço excessivo.
Ao final coloque (Figura 6), use o comando \ref{figura:NOME} para isso.
Tente ordenar as figuras seguindo uma sequência lógica das funcionalidades.

Aguardo.

**Comment by gusttavogomes** [comment]
Reordenei as figuras para uma ordem mais lógica.
Fiz as alterações nos casos de uso ontem mesmo, referenciando as imagens, entretanto estava referenciando a imagem errada, devia ser um bug e dei commit e quando ia mexer hoje, os seguintes arquivos estavam em branco:
_introdução.tex_, _casos_uso.tex_ e _descricao_geral.tex_

**Comment by Ronneesley** [comment]
A referência errada era uma questão de ordem naquela função de **figura.sty**, já arrumei.
1) Onde referencia as figuras coloque Figura com 'F' maiúsculo.
2) O usuário **escolhe** (item 5)
    2.1) No mesmo item, o que quer dizer "e seus tipos"?
    2.2) Referencie a tabela de requisitos que especifica os requisitos da senha;
3) O termo anexar no item 6, tem outro sentido, use preenche;
4) Para concluir a segunda fase, ele tem que clicar em algo;
5) Nos fluxos alternativos em vez de um item para cada coloque apenas:
        "Usuário não preenche o campos de nome, sobrenome, celular ou e-mail, e precisa ser notificado.

**Comment by gusttavogomes** [comment]
Fiz as alterações. Sobre a tabela de requisitos em relação a senha, não referenciei porque não existe tal tabela que especifique tais requisitos da senha, portanto coloquei apenas "O usuário preenche sua senha." 
Aguardo correção.

**Comment by Ronneesley** [comment]
Após o envio do e-mail o usuário ainda volta ao sistema, ou seja, ainda há passos a descrever.
O fluxo alternativo está bom, só não creio que os itens 3 e 4 sejam sub-tópicos, eles são tópicos assim como os primeiros dois.

No fluxo básico você acabou removendo o segundo passo do cadastro que é o arquivo: *Cadastro_2_Passo.png*.
Tente descrever ele no fluxo básico assim como estava fazendo mesmo.

**Comment by gusttavogomes** [comment]
Fiz as alterações. Aguardo correção.

**Comment by Ronneesley** [comment]
Novamente, o único anexar é o caso da foto.
Reveja o termo **upando**, se ele pertence a um dicionário real de português.
Coloque ponto e vírgula ao final de cada item, somente no último coloque ponto final.
É necessário mais um item falando o que acontece no final da terceira etapa.
Fecharei a tarefa, mas aguardo estas correções.
