### ISSUE TITLE
Criar a documentação do caso de uso: Enviar post

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#126]

**Comment by IgorJustinoRodrigues** [comment]
Rone, não entendi muito bem oque e pra fazer. Vou fazer aquela tabela de
caso de uso?

2017-08-11 19:51 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Isso, agora você vai preencher aquela tabela que fez descrevendo este caso de uso

**Comment by IgorJustinoRodrigues** [comment]
Acabei de te mandar, mas eu não entendi oque vai ser o Enviar Post.

2017-08-12 14:37 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Ok
