### ISSUE TITLE
Criar função LaTeX para facilitar a definição de casos de uso

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#127]

**Comment by IgorJustinoRodrigues** [comment]
Criei a função LaTeX, mas não consegui configurar ela muito bem rsrsrs.


2017-08-11 19:52 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Ok, está perfeito.
