### ISSUE TITLE
Criar a documentação do caso de uso: Alterar dados do perfil

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#128]

**Comment by BrenerGomesSI** [comment]
Documentação Enviada na Quinta-feira pronta.

**Comment by Ronneesley** [comment]
Descrever as consequências dos fluxos alternativos

**Comment by BrenerGomesSI** [comment]
Inseri mais alguns fluxos alternativos. Fiz de acordo com o prototipo que fiz de preenchimento de dados do perfil.

**Comment by Ronneesley** [comment]
Brener, utilize o comando \ref{} para referenciar as figuras (veja que por isso o número das figuras estão errados). Ao se referenciar a elas use F maiúsculo: Figura.
No fluxo básico somente o usuário faz coisas, o sistema não responde suas ações?
Utilize subtópicos para estruturar seus fluxos alternativos.

**Comment by BrenerGomesSI** [comment]
realizei as alterações.

**Comment by Ronneesley** [comment]
O documento não está compilado em PDF. Aguardo  a correção.

**Comment by Ronneesley** [comment]
As figuras não estão referenciadas corretamente.

**Comment by Ronneesley** [comment]
No fluxo alternativo, para cada item de exceção colocado especifique como o sistema deve tratá-lo (o que o sistema deve fazer). Não basta apenas citar o que pode acontecer.

**Comment by BrenerGomesSI** [comment]
Assim que o pessoal que criaram as figuras decidirem os nomes delas eu altero.

**Comment by BrenerGomesSI** [comment]
Realizei mais umas alterações.

**Comment by Ronneesley** [comment]
Brener, nos tópicos não use a estrutura: *Usuário: Clicar...*, escreva no lugar *O usuário clica...* evite esse dois pontos no meio, porque todos os outros casos de uso estão escritos assim, até mesmo nos seus.

Reveja os fluxos alternativos, sempre que você colocar uma possibilidade de uso ou problema, você deve descrever os subpassos.

Veja:
 Sistema Offline
– Usuário desconectado.

O que **Usuário desconectado** descreve sobre como tratar o caso do **Sistema Offline**?

**Comment by Ronneesley** [comment]
Não foi feito. (2 semanas de atraso)

**Comment by BrenerGomesSI** [comment]
Realizei outras modificações, no aguardo!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#m_2069527319274945198_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-10-01 17:09 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Vi que melhorou colocando "Sistema exibe...", mas ainda tem casos em "Usuario: ..."
Retire esses dois pontos e redija uma frase.
Mesmo assim considerarei fechada, mas aguardo essa correção.
