### ISSUE TITLE
Criar a documentação do caso de uso: Manter álbum

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#129]

**Comment by maciele** [comment]
pronto terminei

**Comment by maciele** [comment]
Manter album pronto realizei commit

**Comment by Ronneesley** [comment]
Maciele, manter álbum é só um caso de uso, portanto só uma tabela.
O que encontrei formam: Criar álbum, visualizar álbum, editar álbum e apaga álbum.

**Comment by maciele** [comment]
pois é mais eu tinha entendido que o Manter álbum seria todo o álbum em si.

**Comment by maciele** [comment]
o que seria manter álbum? cite algum exemplo do que seria.

**Comment by Ronneesley** [comment]
A operação de manter álbum são todas as operações de CRUD juntas. Todas as operações que colocou em uma tabela, numa única.

**Comment by maciele** [comment]
corregi e enviei de novo

**Comment by maciele** [comment]
boa tarde Rone como você falou para a documentação de manter álbum preciso de dois prototipos, que seria (seus álbuns e suas fotos). Eu já fiz os dois pra ver como ficaria só que você tem que abrir mais issues se quiser colocar pra mim eu quero.

**Comment by maciele** [comment]
![untitled_page_1_1](https://user-images.githubusercontent.com/30672928/29724444-ea131248-899e-11e7-87db-a297dae622aa.png)
![untitled_page_1](https://user-images.githubusercontent.com/30672928/29724438-df27c0fe-899e-11e7-9cf2-6b7e7118951b.png)

**Comment by maciele** [comment]
enviei a documentação do manter álbum, fiz seguindo esses dois prototipos. Mais não subir os prototipos entao no lugar das figuras não aparecerá a numero (Ex: Figura 12).

**Comment by Ronneesley** [comment]
Suba os protótipos adicione-os no documento na seção correta.

**Comment by maciele** [comment]
já subir os dois prototipos e viz a documentação no latex, do caso de uso e tambem do prototipo.
atividade completa.

**Comment by Ronneesley** [comment]
O PDF da documentação não está gerado. Compile-o primeiro.

**Comment by maciele** [comment]
no meu pc esta gerando o pdf.

**Comment by maciele** [comment]
pronto fiz as alterações que você pediu.

**Comment by Ronneesley** [comment]
No item: *Usuário acessa o menu minhas fotos* você precisa especificar qual o protótipo (Figura X).

No item: *O sistema redireciona para seus álbuns:(Figura 20).* Esse sinal de : depois de parêntese está estranho.

O item: *Ao selecionar a opção desejada o sistema redireciona na rede social* está confuso. Qual função? Isso é fluxo alternativo.

Nos textos, os parênteses não podem estar juntos de palavras como em: *pode(editar e deletar)* nem separado como em: *pode( visualizar*

Quando o texto está citando diretamente a figura, não use parênteses.

**Comment by maciele** [comment]
pronto enviei

**Comment by Ronneesley** [comment]
Aqui não houve modificação.

**Comment by maciele** [comment]
Mais no código de caso de uso tem o novo código de caso de uso.

**Comment by Ronneesley** [comment]
Ok
