### ISSUE TITLE
Criação do protótipo do layout do sistema

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#13]

**Comment by Ronneesley** [comment]
Vou delegar esta tarefa a vocês dois.
Gostaria que entrassem em consenso sobre a ideia da aparência geral do sistema.

Conversando com o Salmi, ele fez um comentário interessante a respeito do mesmo. Não necessitamos ser identicos ao Facebook, porém devemos encarar os fatos que estamos criando uma rede social, portanto muitas ações como: fazer post, comentários, galeria de fotos, login, interface geral do usuário, etc. São necessários, mas não necessitam possuir o mesmo formato, podendo ter uma aparência totalmente inovadora.

Então confio esta tarefa a vocês.

**Comment by aandreysr** [comment]
Ok, viu conversar com ele

Em 8 de ago de 2017 16:09, "Ronneesley Moura Teles" <
notifications@github.com> escreveu:

**Comment by Ronneesley** [comment]
@aandreysr gostaria que focasse nesta tarefa agora com o @jrossini94. Então vou deixar apenas essa de layout em aberto para ti na categoria Design

**Comment by Ronneesley** [comment]
Senhores, qual foi o arquivo desta entrega?

**Comment by aandreysr** [comment]
Ainda não tem o arquivo, porem ja tenho uma ideia que até segunda faço a entrega

**Comment by aandreysr** [comment]
fiz o commit de um arquivo Novo_Layout_timeline

**Comment by Ronneesley** [comment]
Oi Andrey, a imagem está cortando.
Não use o termo *timeline*.

Gostaria que diferenciasse a posição daqueles três ícones na barra superior. Use a criatividade, invente outro conceito.

**Comment by aandreysr** [comment]
Atualizei novamente, os arquivos agora estão com o nome de Layout_Feed:
Termo timeline não será mais usado e sim Feed, podendo ter alguma tradução mas ainda nao sei como ficaria

Acrescentei o conceito de "Aporte", que são tópicos de discussão sobre determinados assuntos

**Comment by aandreysr** [comment]
Por ser novo, os Aportes precisam de uma documentação, prototipo e HTML, a ideia é que seja um "forúm" para determinados assuntos, no prototipo do feed, sao apenas links de redirecionamento  com o nome do tópico.

**Comment by Ronneesley** [comment]
Ok

**Comment by Ronneesley** [comment]
Somente vi participação apenas do Andrey, nenhum comentário ou aprensentação do Jefferson.
