### ISSUE TITLE
Criar a documentação do caso de uso: Comentar

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#130]

**Comment by PHRA-IFGOIANO** [comment]
O modelo diverge do protótipo pois o vídeo está como link (no protótipo).

**Comment by PHRA-IFGOIANO** [comment]
Comentei na issue errada -_-

**Comment by Ronneesley** [comment]
Estou olhando com base no arquivo *post rascunho.png* na pasta de *rascunhos*.
O caso de uso vai descrever o ato de comentar um post qualquer seja vídeo ou imagem ou galaria ou texto.
Mas isso é uma questão a olhar no DER mesmo.

**Comment by PauloHenriqueAraujo** [comment]
Subi essa também

**Comment by Ronneesley** [comment]
Não deleta os comentários, senão fica parecendo que não houveram correções e eu me perco onde estávamos.
Continuando... 
1) O texto o: usuário acesso o site da **rede social**.
2) *Faz Login* com letras minúsculas;
3) No fluxo alternativo o erro de login é uma condição para outro caso de uso;
4) No caso da postagem ser deletada, você deve prever como o sistema tem que tratar a condição;
5) *Algum erro* ao publicar é muito genérico, pois você tem que determinar o comportamento de tratamento;
Aguardo as correções.

**Comment by PauloHenriqueAraujo** [comment]
Deletei uns comentários que eu tinha feito sobre outra Isuue, era algo de HMTL e eu perguntei aqui.
Fiz as correções pedidas.

**Comment by PauloHenriqueAraujo** [comment]
Olha o meu Ronnee

**Comment by Ronneesley** [comment]
Ok, aguardo as correções como conversamos.
