### ISSUE TITLE
Criar a documentação do caso de uso: Solicitar amizade

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#131]

**Comment by Jonathanss123** [comment]
Ronne fiz a documentação conforme solicitado. dps confere se esta dentro do pedido.  UC12 Solicitar Amizade

**Comment by Ronneesley** [comment]
O documento PDF não está sendo gerado. Aguardo a correção.

**Comment by Jonathanss123** [comment]
Rone fiz as alterações ... dps da uma olhada la

**Comment by Ronneesley** [comment]
Em: *Ocorreu uma falha na conexão com a internet*  Use I maiúsculo em Internet.
Retire o tópico: *Solitação enviada*
No item: *Problemas com resposta do servidor ao adicionar o amigo* você tem que falar o que o sistema irá fazer.

**Comment by Jonathanss123** [comment]
Fiz as correções conforme solicitado

**Comment by Ronneesley** [comment]
Ok.
