### ISSUE TITLE
Criar a documentação do caso de uso: Enviar mensagem no chat

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#132]

**Comment by gleyson-alves** [comment]
Pronto

**Comment by Ronneesley** [comment]
Utilize o comando \ref{} conforme conversamos na aula hoje para referenciar uma figura.
Nas pré-condições considere que o usuário está autenticado.
Assim comece do terceiro item no fluxo básico.
Adicione a figura **chat_ativos_e_inativos.png** que está na pasta resultados e referencie-a no seu caso de uso.

**Comment by gleyson-alves** [comment]
corrigido, e adicionei a imagem chat_ativos_e_inativos.png

**Comment by Ronneesley** [comment]
Se a sua pré-condição é estar logado, não faz sentido descrever o processo de login, deixo-o para o caso de uso com esta finalidade. Exclua os itens 1 e 2.
O que isso quer dizer? "Usuário o sistema" "Usuário o ator". Releia o que escreveu.
Utilize o comando \ref{} para se referneciar a figuras.
Especifique o tratamento no fluxo alternativo.

**Comment by Ronneesley** [comment]
Ok
