### ISSUE TITLE
Criar a documentação do caso de uso: Apresentar o chat

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#133]

**Comment by adallberto** [comment]
Verificar se esta correto!

**Comment by adallberto** [comment]
Melhorias no caso de uso realizadas! Verificar por favor!

**Comment by Ronneesley** [comment]
Quando o texto refere-se diretamente à figura não use parênteses, como em:

* Usuário seleciona a opção mensagens, que pode ser observado através da (Figura 7)
* O sistema abre o chat, mostrando ao usuário seus amigos que estão online e offline, igual
a: (Figura 8)

Retire a letra maiúscula em *O Usuário...*

Utilize ponto e vírgula no final de cada tópico, exceto o último que é ponto final mesmo.

Aguardo as correções, mesmo assim encerro.
