### ISSUE TITLE
Adicionar os protótipos na documentação LaTeX

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#135]

**Comment by gusttavogomes** [comment]
Fiz o código para colocar os protótipos na documentação. Segue o local do arquivo:
[https://github.com/Ronneesley/redesocial/blob/primeira_codifica%C3%A7%C3%A3o/documentacao/capitulos/prototipos/prototipos.tex](url) 
Não sei se é o local certo, fiz com base no arquivo bem similar sobre caso de uso.
Sobre os protótipos coloquei apenas os classificados como "_resultados_" deixando de fora os "_rascunhos_", caso seja necessário coloca-lós também, me avise.
Aguardo correção

**Comment by Ronneesley** [comment]
Isso mesmo, mas gostaria que compilasse o arquivo **documentacao.tex** para ver se está tudo funcionando.

**Comment by gusttavogomes** [comment]
Tudo funcionando.
Se quiser mandar mais, não acharia ruim não rsrs

**Comment by Ronneesley** [comment]
Regula só o tamanho das imagens para mim, as grandes devem ficar grandes também no documento.
Use o bom senso. Mesmo assim finalizo a tarefa e aguardo essa correção. Ficou ótimo.

**Comment by gusttavogomes** [comment]
Tamanho ajustado.
