### ISSUE TITLE
Criar o comando \figura no LaTeX para facilitar a inclusão de imagens

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#136]

**Comment by Ronneesley** [comment]
Como já vai incluir as imagens dos protótipos na documentação, gostaria que você mesmo criasse o comando de inclusão de figuras. Veja o arquivo *requisitos.sty* que foi criado em #31. Lá uma função é definida, leia na internet como definir funções, um bom site é https://en.wikibooks.org/wiki/LaTeX/Macros.
Crie um arquivo chamado **figura.sty** e defina sua função lá, para testar tem que incluir seu pacote no cabeçalho.

**Comment by gusttavogomes** [comment]
Função criada e funcional.

**Comment by Ronneesley** [comment]
Ok.
