### ISSUE TITLE
Comentar o protótipo de login na documentação

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#137]

**Comment by Ronneesley** [comment]
Sua função será comentar os protótipos relacionados ao login na imagem **login.png** que será adicionada na documentação na tarefa #135, portanto converse com a pessoa responsável para saber o andamento.

**Comment by Lucianodcb** [comment]
ok

**Comment by Lucianodcb** [comment]
já fiz o commit, da uma olhada se a descrição tem que ser mais detalhada. E se a descrição vai ficar na frente do nome dos prototipos.

**Comment by Ronneesley** [comment]
Os textos que me mostrou ainda não foram enviados, aguardo eles.

**Comment by Lucianodcb** [comment]
Já dei commit neles

**Comment by Ronneesley** [comment]
Luciano, edite a Figura 2 no Pencil e retire esse espaço branco sobressalente.
Veja que em seu texto falta uma conexão: "A Figura 1 o usuário", ligue o número da figura com o texto adequadamente. Ex.: A Figura 1 apresenta...

**Comment by Lucianodcb** [comment]
ok

**Comment by Ronneesley** [comment]
Ok
