### ISSUE TITLE
Criação do texto da introdução da documentação em LaTeX

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#138]

**Comment by PauloHenriqueAraujo** [comment]
Fiz um pequeno parágrafo, gostaria que descrevesse melhor como deveria ser a introdução.

**Comment by PauloHenriqueAraujo** [comment]
Deve ser incluso os objetivos gerais e específicos também?

**Comment by Ronneesley** [comment]
Oi Paulo, está ficando bom. O que descreveu em **escopo do produto** deveria estar no tópico **introdução**. O veja no livro texto de Análise Orientada a Objetos o que deve incluir em escopo com mais detalhes. Escopo do produto tem falar o que é e os limites do sistema.

**Comment by PauloHenriqueAraujo** [comment]
Olha o meu Ronnee

**Comment by thaliasantana** [comment]
Não sei se ajuda mais, mas olha só o que eu tinha escrito e o Ronne tinha pedido para compartilhar contigo: 
A rede social criada terá por objetivo interconectar usuários distintos por meio de um ambiente colaborativo. No contexto do Campus Ceres do IF Goiano, o sistema desenvolvido promoverá um canal comunicativo entre discentes e docentes, e até mesmo entre a instituição e seus egressos.
Não se restringindo ao campus, o software deverá ser aplicado a instituições e organizações que busquem um portal de colaboração e comunicação, o qual promoverá interações que abarquem desde postagens, fotos, álbuns, discussões, grupos, páginas, chats e até inclusive, oferecer um local de cadastro de artigos científicos. Deste modo, o projeto rede social vai além das mídias comumente difundidas atualmente.

**Comment by Ronneesley** [comment]
Ok.
