### ISSUE TITLE
Escrita do texto sobre escopo do produto em LaTeX

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#139]

**Comment by iankatalita** [comment]
Olá Ronne, é para a próxima aula?

**Comment by Ronneesley** [comment]
No seu caso não.

**Comment by iankatalita** [comment]
Ronne, desculpa a demora, estou tendo problemas com a minha internet, fiz algumas correções porém não sei se está bom ou se está grande demais. Dê uma olhada depois.

**Comment by Ronneesley** [comment]
Ok. Somente o trecho *... post(postar).* não precisa do postar, basta colocar o *post* em itálico.
