### ISSUE TITLE
Definição da lista de siglas mais comuns que provavelmente usaremos em LaTex no arquivo *siglas.tex*

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#140]

**Comment by Ronneesley** [comment]
De preferência veja as siglas já usadas no texto, mas também pode colocar algumas muito usadas que vamos utilizar, ex: DER, SGBD, WWW, etc.

**Comment by gleyson-alves** [comment]
Pronto

**Comment by Ronneesley** [comment]
Somente a sigla IDE que no nosso caso é *Integrated Development Environment*
Aguardo correção mas já fecho a atividade.

**Comment by gleyson-alves** [comment]
corrigido


________________________________
De: Ronneesley Moura Teles <notifications@github.com>
Enviado: sexta-feira, 18 de agosto de 2017 23:38
Para: Ronneesley/redesocial
Cc: gleyson-alves; Assign
Assunto: Re: [Ronneesley/redesocial] Definição da lista de siglas mais comuns que provavelmente usaremos em LaTex no arquivo *siglas.tex* (#140)


Somente a sigla IDE que no nosso caso é Integrated Development Environment
Aguardo correção mas já fecho a atividade.

**Comment by Ronneesley** [comment]
No PDF ainda está a sigla antiga
