### ISSUE TITLE
Descrição em LaTeX da estrutura do documento

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#141]

**Comment by Ley00** [comment]
Eu enviei na pasta do documentacao e capitulos, de uma olhada

**Comment by Ronneesley** [comment]
Warley, você entendeu errado.
Você deve escrever a seção 1.2 chamada "estrutura do documento".
Eu movi seu arquivo para uma pasta chamada backups porque não era bem assim.
O bom é que você acabou aprendendo sobre a estrutura, o seu texto deve falar mais ou menos assim:

*O capítulo 2 apresenta a descrição geral do software ... O capítulo 3 apresenta a especificação de requisitos ...* 

E por ai vai.

**Comment by Ley00** [comment]
Atualizei o trabalho o que precisa ser modificado?

**Comment by Ronneesley** [comment]
Sim, conforme comentamos tem que tirar as subseções

**Comment by Ley00** [comment]
de uma olhada, disse que seria as meia noite =D

**Comment by Ronneesley** [comment]
Oi Warley, a ligação entre o número do capítulo e a descrição dele está inadequada.
Veja, o capítulo 2 até começa bem, "O capítulo 2 demonstra ...", na nossa área o termo demonstra é muito utilizado apenas para demonstrações matemáticas, como nenhum dos capítulos há este fato sugiro que troque o termo para "apresenta" ou "mostra" ou outro.
A questão é que os demais capítulos não tem o conectivo, veja: "capítulo 3 requisitos funcionais", "Capítulo 4 protótipos"??

Releia o que escreveu e introduza estes conceitos.

**Comment by Ley00** [comment]
pronto

**Comment by Ronneesley** [comment]
Utilize letra maiúscula para referenciar os capítulos: Capítulo.
Ainda continua os erros que havia mencionado "capı́tulo 3 requisitos funcionais", "em seguida o capı́tulo 4 protótipos"... releia o texto.

**Comment by Ley00** [comment]
consegui? (por favor diga que sim)

**Comment by Ronneesley** [comment]
Não vi modificação, você tem que compilar o documento.

**Comment by Ley00** [comment]
pronto

**Comment by Ronneesley** [comment]
Ainda está sem ligação o texto: **Capítulo 3 requisitos funcionais**
Faça a ligação ex: Capítulo 3 **apresenta os** requisitos funcionais
Veja os demais capítulos também.

**Comment by Ley00** [comment]
aleluia .-.

**Comment by Ronneesley** [comment]
Veja: **Capı́tulo 4 protótipos**
**Capı́tulo 5 descrever** 

Aguardo as correções, mesmo assim encerro.
