### ISSUE TITLE
Escrita do texto introdutório do capítulo de descrição geral em LaTeX

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#142]

**Comment by Ronneesley** [comment]
Veja no livro-texto da disciplina anterior os conteúdos das seções.

**Comment by dmcardoso** [comment]
Ronne, já fiz o commit. Não sei se coloquei no lugar certo. Aguardo sua avaliação para possíveis correções. Obrigado.

**Comment by Ronneesley** [comment]
Perfeito.
