### ISSUE TITLE
Escrita do texto sobre Perspectivas do produto em LaTeX

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#143]

**Comment by thaliasantana** [comment]
De acordo com tu:
Perspectiva do Produto: descrever situação ambiental de uso do software, interconexões, interfaces externas, operações, restrições de memória primária e secundária.
Lembro que quando fizemos nosso documento, nessa parte, colocamos os resultados estatísticos obtidos. O que devo frisar mais aqui nesse caso? Tipo, o sistema não irá interagir ainda com outro sistema, ainda não sei alguma especificidade de desempenho e memória,... Só vou tentar levantar sua importância, objetivo?

**Comment by thaliasantana** [comment]
Help me, estou com medo de apenas enrolar nessa parte e ficar repetitivo demais com demais itens do documento de requisitos.

**Comment by thaliasantana** [comment]
Aqui eu posso falar previamente das ferramentas usadas ou não?

**Comment by thaliasantana** [comment]
Até agora, veja o que já escrevi:
A rede social criada terá por objetivo interconectar usuários distintos por meio de um ambiente colaborativo. No contexto do Campus Ceres do IF Goiano, o sistema desenvolvido promoverá um canal comunicativo entre discentes e docentes, e até mesmo entre a instituição e seus egressos. 
Não se restringindo ao campus, o software deverá ser aplicado a instituições e organizações que busquem um portal de colaboração e comunicação, o qual promoverá interações que abarquem desde postagens, fotos, álbuns, discussões, grupos, páginas, chats e até inclusive, oferecer um local de cadastro de artigos científicos. Deste modo, o projeto rede social vai além das mídias comumente difundidas atualmente. 
Ademais, acerca de princípios técnicos de construção, o sistema trará como características principais o desenvolvimento em linguagem Java e banco de dados MySQL.

**Comment by thaliasantana** [comment]
Ronne? Conseguiu olhar?

**Comment by Ronneesley** [comment]
Ok, aguardo as modificações como conversamos.

**Comment by thaliasantana** [comment]
Lembrando que hoje estaremos em Luziânia e só irei mexer nisso a noite. Até quinta fica pronto!

**Comment by thaliasantana** [comment]
Quando eu digo, o software "irá" fazer tal coisa. Eu uso assim ou sigo aquela ideia de "deverá" fazer... ? Qual das formas de escrita é melhor?

**Comment by thaliasantana** [comment]
Enfim, eu coloquei lá no documento Latex! Veja se está tudo okay. Aguardo correções!

Obs.: Tive que comentar essa sessão abaixo no arquivo documentacao.tex, pois não compilava de jeito algum, aí vi que ela nao estava construída dentro da pastinha de capítulos... O que é? 	

\input{capitulos/especificacao_requisitos/Suposicoes_e_dependencias.tex}

**Comment by Ronneesley** [comment]
Ok
