### ISSUE TITLE
Criar método alterarSenha() em UsuarioDAO

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#144]
Este método funciona de forma similar ao alterar()
Porém só altera a senha

**Comment by laracaroline** [comment]
Feito! Confere se é só aquilo mesmo, por favor.

**Comment by Ronneesley** [comment]
Quase perfeito. Somente o nome da tabela que não é **usuario**
Aguardo a correção, mas já fecho a atividade.
