### ISSUE TITLE
Obtenção do ID após a inserção em todos os DAOs

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#145]

**Comment by Ronneesley** [comment]
Como estava ocupado com o DER segue uma atividade a mais para programação.

**Comment by Ronneesley** [comment]
Consiste em inserir após a última linha de todos os DAOs o comando:
*dto.setId(getId(pstmt));*
OBS: Se ele já não estiver presente, alguns eu já fiz como o *UsuarioDAO*.

**Comment by Salminunes** [comment]
Só isso mesmo? Só no inserir como no UsuarioDAO?

**Comment by Ronneesley** [comment]
Quase perfeito, somente em *PostagemDAO* o comando foi colocado 2 vezes, deixe apenas uma.
Já fecho a tarefa mas aguardo a correção.
