### ISSUE TITLE
Escrita do texto sobre Funções do produto em LaTeX

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#146]

**Comment by Warley01** [comment]
As funções do produto que você fala é as funcionais e não funcionais?

**Comment by Ley00** [comment]
As funções do produto que você fala é as funcionais e não funcionais? E tem que especificar o que ela realiza?

**Comment by Ronneesley** [comment]
Não, veja o livro texto sobre Análise Orientada a Objetos e veja estas seções.

**Comment by Ley00** [comment]
De uma olhada

**Comment by Ronneesley** [comment]
Ok
