### ISSUE TITLE
Escrita da seção Restrições gerais em LaTeX

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#148]

**Comment by IgorJustinoRodrigues** [comment]
Ronne, oque é Restrições Gerais? rsrsrsrs

2017-08-14 12:27 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Veja no livro texto de Análise Orientada a Objetos onde comentamos desta documentação.

**Comment by IgorJustinoRodrigues** [comment]
Acabei de mandar.

2017-08-14 13:30 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
No lugar de  > ...melhor aceito pela equipe...
Use "maior domínio".
