### ISSUE TITLE
Escrita da seção Suposições e dependências em LaTeX

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#149]

**Comment by Ronneesley** [comment]
Mais uma atividade.

**Comment by cybersecwoman** [comment]
Me explica por favor.

**Comment by Ronneesley** [comment]
Leia a página 14 do livro texto do semestre passado item 4.5.

**Comment by cybersecwoman** [comment]
Só criar, ou preenchê-la também? Vi várias criadas mas nenhuma tem conteúdo. E tenho uma certa dificuldade em entender o Latex, pode colocar assento lá?

**Comment by cybersecwoman** [comment]
Tá criada, porém não está preenchida.

**Comment by cybersecwoman** [comment]
Vê se aparece para você, o meu não compila, meu Latex tá com problemas.

**Comment by cybersecwoman** [comment]
Fiz as modificações que pediu.

**Comment by Ronneesley** [comment]
Ok

**Comment by cybersecwoman** [comment]
Corrigi o nome GlassFish lá e consegui compilar aqui no meu então acredito que agora está 100%.
