### ISSUE TITLE
Escrita do texto inicial do capítulo de projeto em LaTeX

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#150]

**Comment by FernandoMacielS** [comment]
Capitulo Projeto, texto inicial feito.

**Comment by Ronneesley** [comment]
Fernando não encontrei seu texto. O capítulo 6, página 45 está sem nada.

**Comment by FernandoMacielS** [comment]
> Fernando não encontrei seu texto. O capítulo 6, página 45 está sem nada.

Reenviado.

**Comment by Ronneesley** [comment]
DER não é fluxograma. Acrescente uma seção para o diagrama de classes e descreva-o no seu texto.

**Comment by FernandoMacielS** [comment]
O diagrama de classes, eu o deixo como 6.2 ou 6.4?

**Comment by Ronneesley** [comment]
Estou aguardando esta correção ainda.

**Comment by FernandoMacielS** [comment]
Correção Feita.

**Comment by FernandoMacielS** [comment]
Bom, aparentemente não esta querendo atualizar, mas não foi por falta de mandar.

**Comment by Ronneesley** [comment]
Dê espaço no parêntese. Diagrama Entidade e Relacionamento(DER)
