### ISSUE TITLE
Criação da unidade de testes para Estados método alterar()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#153]

**Comment by aandreysr** [comment]
Criação da unidade de testes para Estados método alterar funcionado

2017-08-15 12:37 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by aandreysr** [comment]
Eu faço o testo mas quando eu compilo aparece o seguinte erro em anexo
![cats](https://user-images.githubusercontent.com/22335271/29487179-84da2600-84cb-11e7-9805-1e94ca876422.jpg)

**Comment by aandreysr** [comment]
o meu test esta inserindo o pais no banco de dados mas quando testa  o arquivo da o erro  da falta de inserir o pais

**Comment by aandreysr** [comment]
Tudo corrigido e funcionando

**Comment by Ronneesley** [comment]
Ok
