### ISSUE TITLE
Criação da unidade de testes para Estados método listar()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#155]

**Comment by cybersecwoman** [comment]
Me dá uma luz  por favor, nem sei como começar.

**Comment by Ronneesley** [comment]
Veja o exemplo que já está no projeto: *PaisBOTest.java* no item **Pacotes de teste**

**Comment by cybersecwoman** [comment]
Já tem um criado EstadosBOTest.java o que é para fazer nele continuo sem entender kkkk. Ronne você poderia me auxiliar na aula hoje? Já agradeço.

**Comment by cybersecwoman** [comment]
Não sei fazer isso socorro

**Comment by cybersecwoman** [comment]
Eu fiz lá Criação da unidade de testes para Estados método listar()  mas não sei se está correto, olha lá por favor!

**Comment by Ronneesley** [comment]
Está melhorando, mas seu teste está falhando.
Para inserir um estado, antes tens que inserir um país.

**Comment by cybersecwoman** [comment]
Ronne eu bombei em banco, estou sinceramente travada, se puder me dar as coordenadas do que fazer, eu faço aqui da melhor forma possível, to tentando mas estou limitada pelo banco, não sei como rodar o teste sei que preciso do banco para isso mas não sei como fazer isso. Preciso de um Help!

**Comment by Ronneesley** [comment]
Anny, busque respostas do que é o defeito que está dando no Google. Mas sugiro que desinstale seu banco de dados e instale de novo. Não confunda o seguinte: WorkBench não é MySQL.
O site oficial é: https://dev.mysql.com/downloads/mysql/

**Comment by cybersecwoman** [comment]
Tá ok agora, só não ficou 100% porque pelo que entendi depende de uma outra atividade que não está feita.

**Comment by Ronneesley** [comment]
Então converse com a outra pessoa da atividade dependente. Aguardo a aprovação do teste inteiro.

**Comment by Ronneesley** [comment]
Foi um problema no código do Igor que alguém acabou excluindo o que ele tinha feito. Já voltei. Mas seu teste está falhando.

**Comment by cybersecwoman** [comment]
Vou tentar resolver aqui!

**Comment by cybersecwoman** [comment]
E agora? Tentei.

**Comment by Ronneesley** [comment]
A indentação não está boa e o teste está falhando.

**Comment by cybersecwoman** [comment]
Ronne eu não achei o erro, pedi ajuda para várias pessoas ninguém conseguiu me ajudar, se você não e ajudar infelizmente não vou conseguir te entregar essa tarefa.

**Comment by Ronneesley** [comment]
Ok
