### ISSUE TITLE
Criação da unidade de testes para Cidades método selecionar()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#159]

**Comment by BrenerGomesSI** [comment]
Ja fiz o commit pelo github online.

**Comment by Ronneesley** [comment]
Tem que inserir o estado e país antes.

**Comment by BrenerGomesSI** [comment]
Realizei a inserção dos dois.

**Comment by Ronneesley** [comment]
Execute seu teste, ele não está sendo aprovado.

**Comment by BrenerGomesSI** [comment]
Não estou conseguindo executar ele com o banco de dados.

2017-08-24 15:03 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Porquê?

**Comment by Ronneesley** [comment]
Seu código ainda não está funcionando.

**Comment by Ronneesley** [comment]
Ainda está falhando.

**Comment by Ronneesley** [comment]
(3 semanas de atraso)

**Comment by BrenerGomesSI** [comment]
Metodo Selecionar pronto!

**Comment by Ronneesley** [comment]
Ok
