### ISSUE TITLE
Criação do HTML para cadastro de usuários

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#16]

**Comment by Ronneesley** [comment]
O HTML foi criado e já codificado em JSP. Precisa de melhorias na aparência e outros detalhes.

**Comment by cybersecwoman** [comment]
Ok qual o prazo?

**Comment by Ronneesley** [comment]
Todas as atividades são 7 dias. Está atrasado.

**Comment by Ronneesley** [comment]
OK
