### ISSUE TITLE
Criação da unidade de testes para Cidades método listar()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#161]

**Comment by gleyson-alves** [comment]
Criação da unidade de testes para Cidades método listar() #161

**Comment by Ronneesley** [comment]
Seu teste está falhando, implemente as correções que vimos ontem.

**Comment by Ronneesley** [comment]
Aguardando correção.

**Comment by Ronneesley** [comment]
Ainda está falhando

**Comment by gleyson-alves** [comment]
terminado,
por favor passar outro.

**Comment by Ronneesley** [comment]
OK
