### ISSUE TITLE
Criação da unidade de testes para Album método excluir()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#164]

**Comment by iankatalita** [comment]
Confere pra ver se está tudo certo.

**Comment by iankatalita** [comment]
Ronee, não to entendendo como tenho que fazer o método excluir do álbum. Seguinte, tá pedindo data, ai lá no dto temos os campos Id, Nome, Data e Usuário, então quando eu for fazer o método excluir tenho que seguir o que tem lá? Tenho que mandar excluir todos aqueles campos? Ou os mesmos campos que tem em inserir? To mega confusa pq de todo jeito que faço ta pedindo a data só que eu coloquei a data. ME SOCORRE, PLEASE.

**Comment by iankatalita** [comment]
Ronne, eu de novo kkkkkkkkk tomei base o código da Thalia, acho que entende o que tinha que ser feito, se você inseriu as informações no método inserir, eram aquelas informações que eu iria pegar pra remover o álbum, bom meio que entendi assim, só não entendi o pq desse código ( bo.excluir(id); -  Album albumSelecionadoPosExclusao = bo.selecionar(id); ) ele serve pra escolher no caso? Realmente não entende. No final nos comandos de assertNotNull não deu pra colocar o fail tava dando erro e com a mensagem de Falha ao inserir Album: null, então pensei que as vezes o fail não se classificaria ali, e achei melhor inverter, coloquei outro assertNotNull, não sei se está correto, realmente não sei. Tenho muita dificuldade em entender algumas coisas. O código compilou sem erro, agora bom, me explica pra que serve esse código, please. :)

**Comment by Ronneesley** [comment]
Esses comandos servem para verificar se está excluído mesmo.
Tirar o *fail()* que deveria estar lá foi que nem varrer sujeira para debaixo da cama, se estava chegando lá era porque estava falhando, o que você fez foi tirar a mensagem de falha. 
Execute passo a passo para ver onde falha.

**Comment by iankatalita** [comment]
Pronto, menino Ronne.

**Comment by Ronneesley** [comment]
A indentação não está boa. Aguardo a correção.

**Comment by iankatalita** [comment]
Indentação pronta, confere se atende aos seus critérios, menino Ronne kkkkkkk

**Comment by Ronneesley** [comment]
Ainda não está bom no trecho:

} catch (Exception ex){
fail("Falha ao inserir um album: " + ex.getMessage());
}
