### ISSUE TITLE
Criação da unidade de testes para Album método selecionar()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#165]

**Comment by IgorJustinoRodrigues** [comment]
Mandei, não testei pois ainda estou esperando os outros métodos.

2017-08-15 21:30 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Senão houverem erros sintáticos, cada método é testado independentemente.
No seu método não haverá inserção sem preencher os outros atributos do álbum.

**Comment by IgorJustinoRodrigues** [comment]
Acabei de mandar.

2017-08-16 18:25 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Ok
