### ISSUE TITLE
Criação da unidade de testes para Album método listar()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#166]

**Comment by jonatas-rezende** [comment]
Tarefa cumprida e submetida

**Comment by Ronneesley** [comment]
Aguardo a inserção dos pré-requisitos como exemplificado na aula

**Comment by jonatas-rezende** [comment]
fiz todos os pré-requisitos, ele faz a inserção perfeitamente, porém ao sair do laço dá erro no próximo comando e não consegui arrumar... deixei o local comentado.

**Comment by Ronneesley** [comment]
Ok
