### ISSUE TITLE
Criação da unidade de testes para Comentário método inserir()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#167]

**Comment by Ronneesley** [comment]
Não foi feito (6 semans de atraso)

**Comment by Jonathanss123** [comment]
Rone teve uma alteração no Banco de dados ... retirando "curtidas" e inserindo "Ups e Downs" ... fiz o codigo mas esta dando erro, verificando com alguns alunos que me ajudaram me disseram q poderiam ser esse a causa do problema. Gostaria que vc verificasse.

**Comment by Jonathanss123** [comment]
Rone depois você confere para ver oq pode ser mudado... mereço ao menos 2 estrela(ou tirar um menos meu) hehe por essa atividade de hoje tive que alterar todos curtidas para Ups e downs de todo o codigo dto, dao e testes e mesmo assim ainda esta dando este erro.

**Comment by Ronneesley** [comment]
Seu código ainda está falhando por causa de um nome errado na coluna do banco de dados chamada **visualizacoes**. Nada feito de estrelas para este caso, se tivesse feito no tempo correto não teria que ter mudado tantas outras coisas.

Abri uma issue #304 que está com o Brener a respeito disso, ajude-o e após a correção veja se é só este o erro do seu teste.

**Comment by Jonathanss123** [comment]
Rone achei o erro e corrigir .. depois de alterar todos os Ups e acrescentar os Downs ... acrescentar Visualizações e Respostas corrigir vários erros no código consegui. depois da uma olhada la.

**Comment by Ronneesley** [comment]
Ok
