### ISSUE TITLE
Criação da unidade de testes para Comentário método alterar()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#168]

**Comment by JoseGilvan** [comment]
pronto

**Comment by Ronneesley** [comment]
Está com erro sintático. Veja que cada método *inserir(), alterar(), excluir()*, etc que tiver que chamar, deve ter um tratamento.
Ex. do seu próprio código: 

            try{
                                
                bo.inserir(comentario);
            } catch(Exception ex){
                //Mensagem de erro caso falhe
                 
                fail("Falha ao inserir um comentário: " + ex.getMessage());
            }

**Comment by Ronneesley** [comment]
Não terminado (2 semanas de atraso)

**Comment by JoseGilvan** [comment]
Ok

**Comment by Ronneesley** [comment]
Está com erros.

**Comment by JoseGilvan** [comment]
Estou tendo dificuldade em corrigir o código, preciso de uma orientação sua.

**Comment by Ronneesley** [comment]
José foi assunto já estudado, lembre-me de perguntar em sala de aula, porém não fique parado por isso.
É um trabalho e você deve buscar informações sobre como resolvê-lo.

O teste está falhando e a indentação não está boa (2 semanas de atraso).

**Comment by JoseGilvan** [comment]
Pronto

**Comment by Ronneesley** [comment]
Mostre-me em sala

**Comment by Ronneesley** [comment]
Atrasado: 6 semanas.

**Comment by JoseGilvan** [comment]
terminado com uns minutos de atraso...

**Comment by Ronneesley** [comment]
OK
