### ISSUE TITLE
Criação da unidade de testes para Comentário método selecionar()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#169]

**Comment by jrossini94** [comment]
Feito

**Comment by Ronneesley** [comment]
Está falhando.

**Comment by jrossini94** [comment]
feito

**Comment by jrossini94** [comment]
Professor fui trabalhar no teste hoje, porém está com problemas em outras classes..

**Comment by jrossini94** [comment]
fechei sem querer ;-;

**Comment by Ronneesley** [comment]
Então corrija o que estiver errado independemente do lugar para fazer seu teste dar certo, é esse o objetivo de um teste.

**Comment by Ronneesley** [comment]
Mostre-me em sala

**Comment by Ronneesley** [comment]
Ok
