### ISSUE TITLE
Criação da unidade de testes para Comentário método listar()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#170]

**Comment by laracaroline** [comment]
Feito!

**Comment by Ronneesley** [comment]
Lara, as atividades de testes só vou fechar após o teste ser aprovado. Você chegou a ver o resultado do seu teste?
Os comentários tem outros atributos que não foram preenchidos, portanto é esperado que nem ocorra a inserção no laço.

**Comment by laracaroline** [comment]
Finalmente funcionou :)

**Comment by Ronneesley** [comment]
Ok
