### ISSUE TITLE
Criação da unidade de testes para Comentário método excluir()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#171]

**Comment by Lucianodcb** [comment]
Dei commit, mas não esta funcionando

**Comment by Ronneesley** [comment]
Seu teste nem está sendo executado pela ausência da anotação: *@Test*
Ainda assim está com erro.

**Comment by Lucianodcb** [comment]
Na hora de dar commit eu apaguei o @test junto com o comentário

**Comment by Ronneesley** [comment]
Mesmo assim, faça o teste. Ele está falhando.

**Comment by Lucianodcb** [comment]
agora esta pronto

**Comment by Ronneesley** [comment]
Ok
