### ISSUE TITLE
Criação da unidade de testes para Multimídia método excluir()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#174]

**Comment by Macilon** [comment]
Boa tarde Rone!
Completei a atividade, depois você me diz como ela está.

**Comment by Ronneesley** [comment]
Está dando erro, execute seu teste para descobrir.

**Comment by Macilon** [comment]
O erro não é no método selecionar?
Porque o meu é o excluir...

**Comment by Macilon** [comment]
Rone, já finalizei essa atividade. Depois dê uma olhada...

**Comment by Macilon** [comment]
Rone, já finalizei essa atividade. Depois dê uma olhada...

**Comment by Ronneesley** [comment]
Ok
