### ISSUE TITLE
Criação da unidade de testes para Multimídia método listar()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#175]

**Comment by MarcosArriel** [comment]
Bom dia professor mandei os testes que o senhor pediu, imagino que esteja correto. Quanto a pesquisa estou fazendo ainda não achei muito o melhor que achei chama RTMP estou pesquisando sobre ele. levo hoje para a aula. Obrigado pela atenção e bom trabalho.


________________________________
De: Ronneesley Moura Teles <notifications@github.com>
Enviado: terça-feira, 15 de agosto de 2017 21:35
Para: Ronneesley/redesocial
Cc: MarcosArriel; Mention
Assunto: Re: [Ronneesley/redesocial] Criação da unidade de testes para Multimídia método listar() (#175)


Assigned #175<https://github.com/Ronneesley/redesocial/issues/175> to @MarcosArriel<https://github.com/marcosarriel>.

**Comment by Ronneesley** [comment]
Oi Marcos, execute o teste e verá que ele está falhando, veja as causas na mensagem de erro e ajuste seu teste (como é o caso atual em que falta preencher itens da multimídia) ou arrume o código que falha.

**Comment by MarcosArriel** [comment]
Professor aprimorei o teste agora acho que esta certo.

**Comment by Ronneesley** [comment]
Na linha 156 o caminho do arquivo não é o informado em:
*multimidia.setMidia(Utilitarios.lerArquivo(new File("../../../../../../nome_arquivo.txt")));*
e sim: **../../arquivos_teste/nome_arquivo.txt**
Mesmo preenchendo com o novo valor ainda está falhando, aguardo as correções.

**Comment by MarcosArriel** [comment]
Professor resolvido e testado

**Comment by Ronneesley** [comment]
Ainda está falhando, nunca retire um comando do gênero:

fail("Falha ao listar uma multimidia: " + ex.getMessage());

**Comment by MarcosArriel** [comment]
Testei e funcionou.

**Comment by Ronneesley** [comment]
OK
