### ISSUE TITLE
Criação da unidade de testes para Multimídia método selecionar()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#176]

**Comment by Ronneesley** [comment]
Tinha mencionado que já tinha terminado... então segue mais uma atividade.

**Comment by aandreysr** [comment]
esta feito, falta um pequeno erro que vou tirar duvida durante a aula

**Comment by Ronneesley** [comment]
Está com erro, classe *Multimidia* não tem método selecionar, quem tem é o BO.

**Comment by aandreysr** [comment]
O erro estava no multimídiaDAO, agora está funcionando corretamente

Em 25 de ago de 2017 16:20, "Ronneesley Moura Teles" <
notifications@github.com> escreveu:

**Comment by Ronneesley** [comment]
Ainda tem erro na linha 195

**Comment by aandreysr** [comment]
Vou algum erro de commit que não subiu algumas modificações, mas já arrumei

Em 26 de ago de 2017 13:15, "Ronneesley Moura Teles" <
notifications@github.com> escreveu:

**Comment by Ronneesley** [comment]
A indentação não está boa nos últimos comandos.
