### ISSUE TITLE
Criação da unidade de testes para Postagem método selecionar()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#180]

**Comment by Ley00** [comment]
De uma olhada

**Comment by Ronneesley** [comment]
Execute o teste e veja que está falhando.

**Comment by Ley00** [comment]
Não consigo entender sobre o erro sobre o curtidas

**Comment by Ronneesley** [comment]
Você precisa inserir todos os elementos anteriores a postagem, usuário, cidade, estado, país e o que tiver a mais que posso ter esquecido. Conforme o exemplo que dei em aula para o método inserir() da mesma classe, que está logo acima do seu código.

**Comment by Ley00** [comment]
Verifique

**Comment by Ronneesley** [comment]
Passou no teste, mas o final do código você não deveria ter tirado:

Postagem postagemSelecionada = postagembo.selecionar(idpostagem);            
assertNotNull("Postagem não encontrada", postagemSelecionada);
