### ISSUE TITLE
Criação da unidade de testes para Usuário método alterar()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#183]

**Comment by gusttavogomes** [comment]
Ronne, estou comum problema lá no código.
Está inserindo normalmente no banco, mas quando vai alterar, apresenta o erro:
_Falha ao alterar usuario: null_

**Comment by Ronneesley** [comment]
Execute passo a passo (Depurar) o teste para encontrar o problema.

**Comment by gusttavogomes** [comment]
Acho que encontrei.
No código que coloquei, inseri um usuário com todos os campos referentes a ele e foi inserido normalmente no banco.
Ai dei o comando para alterar apenas o nome, e ai acontece o erro (_Falhou: ao alterar usuario: null_).

Olhando na classe UsuarioDAO, o código _SQL_ de update pede 12 parâmetros  e não 2 como eu estava mandando(apenas _nome_ e _id_).
Ao alterar o código SQL para receber apenas 2 parâmetros, o método de teste de alterar do usuário funciona normalmente.
O que faço?

(Anexei os comandos como comentários no código)

**Comment by Ronneesley** [comment]
Ok
