### ISSUE TITLE
Criar a ligação de amigos no DER

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#187]

**Comment by Salminunes** [comment]
Pronto, pode mandar mais. :)

**Comment by Ronneesley** [comment]
Salmi você não pode chamar as duas colunas de *usuarios*.
Chame de *usuario_1* e *usuario_2* para resolver o conflito.

**Comment by Ronneesley** [comment]
Não se esqueça também de exportar o SQL após corrigir.
