### ISSUE TITLE
Criação do servlet de para o cadastro de países: inserir

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#189]

**Comment by Ronneesley** [comment]
Segue um desafio. Caso complete-o, você terminará o critério **programação**

Já descrevi as regras de formação de equipes na wiki: https://github.com/Ronneesley/redesocial/wiki/Quadro-de-participa%C3%A7%C3%A3o-(Turma-SI-2017-02)

Você poderá formar equipes com três pessoas.

Bom trabalho.

**Comment by IgorJustinoRodrigues** [comment]
Ok, falei com o Daniel, Paulo e Wesley. Eles vão fazer parte da minha
equipe.

Em 22 de agosto de 2017 11:12, Ronneesley Moura Teles <
notifications@github.com> escreveu:

**Comment by Ronneesley** [comment]
Igor está pronto este, mas os dois ainda não funcionam junto porque esqueceu.
De completar o código:

form action="**#**" method="post"

E não colocou *name* no campo:

input tabindex="1" type="text" class="campo" id="pais" placeholder="Digite o nome do país"

Aguardo estes ajustes mas já encerro a atividade.

**Comment by IgorJustinoRodrigues** [comment]
Completei o código, não apresentou nenhum erro, mas não consegui testar o
arquivo.

2017-08-25 11:25 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:
