### ISSUE TITLE
Criação do HTML para o timeline

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#19]

**Comment by aandreysr** [comment]
Finalizei o html do prototipo da timeline, se possivel gostaria de outra tarefa

**Comment by Ronneesley** [comment]
Oi Andrey, está ficando muito bom. Somente separe as operações da imagem *icones.jpg*.
Já que conseguiu criar uma pasta para as imagens, renomeia de *img* para *imagens*.
Aguardo o desmembramento para fechar a atividade.

**Comment by aandreysr** [comment]
Já conclui estas alterações

**Comment by Ronneesley** [comment]
Ok.
