### ISSUE TITLE
Criar documentação de todas as funções contidas no projeto RedeSocial

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#192]
Comentar os códigos criados conforme o exemplo de *Pais*, *PaisDAO* e *PaisBO*.
Esta atividade é da sala inteira, somente será dada como fechada quando tudo estiver completo.
Sugiro que cada criador de função/classe faça a sua documentação.

**Comment by Ronneesley** [comment]
A ferramenta limita a associação de apenas 10 pessoas. Comuniquem aos demais colegas sobre a atividade.

**Comment by jonatas-rezende** [comment]
Comentários do arquivo Cidade.java incluídos, os arquivos de teste deverão ser comentados também?

**Comment by Ronneesley** [comment]
Os comentários estão perfeitos. Seria ótimo.

**Comment by thaliasantana** [comment]
Comentários feitos em DTO Álbuns; DAO PostagemMultimidia Selecionar e Excluir; e organização do DAO Países Listar.

**Comment by aandreysr** [comment]
Comentários feitos em Alterar EstadosBOTest, MultimidiaBO, AlbumBO, PostagemAlbumDTO e listar AlbumDAO

**Comment by gusttavogomes** [comment]
Comentários feitos em  inserir AlbumBOTest, alterar  UsuarioBOTest, alterar ComentarioDAO e alterar PostagemAlbumDAO

**Comment by BrenerGomesSI** [comment]
Estado,java e Multimidia.java comentarios adicionados.

**Comment by dmcardoso** [comment]
Comentários feitos em selecionar AlbumDAO, inserir PostagemMultimidiaDAO, EstadoBO, validações UsuárioBO, selecionar EstadoBOTest

**Comment by iankatalita** [comment]
Arquivo Comentário.java em DTO finalizado.

**Comment by BrenerGomesSI** [comment]
Estado.java e Multimidia.java ja finalizado


2017-08-25 22:37 GMT-03:00 Ianka Talita <notifications@github.com>:

**Comment by IgorJustinoRodrigues** [comment]
Comentários Feitos

DTO Usuario.java DAO ComentarioDAO.java (Função Listar) EstadoDAO.java
(Função Listar) PostagemDAO.java (Função Excluir) PostagemDAO.java (Função
Alterar) PostagemDAO.java (Função Selecionar) BO PaisBO.java Teste
AlbumBOTest.java (Função Selecionar) UsuarioBOTest.java (Função Listar)
Servlet PaisControle.java

2017-08-26 18:46 GMT-03:00 Brener Gomes <notifications@github.com>:

**Comment by jonatas-rezende** [comment]
Comentário feito em Listar AlbumBOTest.java (uma dúvida, quando marca qual o issue, já aparece uma mensagem aqui, mesmo assim ainda precisa enviar essa mensagem?)

**Comment by thaliasantana** [comment]
Comentário feito em PostagemBOTest (não sei se os comentários estão corretos).

**Comment by iankatalita** [comment]
Comentários finalizados (Comentario.java em DTO, ComentarioDAO.java metódo Selecionar, CidadeDAO.java metódo Alterar e ArtigoBO.java).

**Comment by adallberto** [comment]
Comentários feitos em ComentarioBO.java e UsuarioDAO.java

**Comment by cybersecwoman** [comment]
Comentário do método Listar de EstadosBOTest.java vê lá como que tá ficando os comentários lá Ronneesley.

**Comment by Ronneesley** [comment]
Ainda tem muita coisa sem fazer.

**Comment by jonatas-rezende** [comment]
qualquer um pode comentar os códigos e fazer commit ou somente o responsável pela criação?

**Comment by iankatalita** [comment]
Comentário finalizado em AlbumBOTest.java no método Excluir.

**Comment by cybersecwoman** [comment]
Comentário EstadosBOTest.java método listar acho que agora ficou ok.

**Comment by Ronneesley** [comment]
OK, 2 estrelas para todos.

**Comment by Ronneesley** [comment]
OK, 2 estrelas para todos.
