### ISSUE TITLE
Incrementar no DER a tabela de aportes

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#197]

**Comment by Ronneesley** [comment]
Aporte e grupo é mesma coisa?

**Comment by dmcardoso** [comment]
Acredito que não. Aporte seria um colaborador ou apoiador para um projeto



Enviado do meu smartphone Samsung Galaxy.


-------- Mensagem original --------
De: Ronneesley Moura Teles <notifications@github.com>
Data: 25/08/17 22:41 (GMT-03:00)
Para: Ronneesley/redesocial <redesocial@noreply.github.com>
Cc: DanielIFGoianoSI <qualquercoisa6568@hotmail.com>, Assign <assign@noreply.github.com>
Assunto: Re: [Ronneesley/redesocial] Incrementar no DER a tabela de aportes (#197)


Aporte e grupo é mesma coisa?

**Comment by PauloHenriqueAraujo** [comment]
Este está pronto

**Comment by Ronneesley** [comment]
Ok
