### ISSUE TITLE
Criação a classe DTO para artigo

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#198]

**Comment by dmcardoso** [comment]
Conclui a tarefa com algumas ressalvas.
1. Como a tabela no banco não está pronta, coloquei alguns nomes que escolhi.
2. fiquei na dúvida se issn é inteiro ou string
3. Url não estava na documentação porém no protótipo estava incluído, então inclui
4. url coloquei do tipo String, não sei se está correto
5. o arquivo do artigo também não estava na documentação mas estava no protótipo, então inclui com o tipo byte.
Aguardo resposta.

**Comment by Ronneesley** [comment]
Ok, favor incluí-los na documentação então.
URL e ISSN são siglas, portanto caixa alta. Aguardo a correção, mas encerro a tarefa.

**Comment by dmcardoso** [comment]
Corrigido

2017-08-26 14:31 GMT-03:00 Ronneesley Moura Teles <notifications@github.com<mailto:notifications@github.com>>:

Ok, favor incluí-los na documentação então.
URL e ISSN são siglas, portanto caixa alta. Aguardo a correção, mas encerro a tarefa.

**Comment by dmcardoso** [comment]
Já incluí na documentação também.

2017-08-26 15:01 GMT-03:00 Daniel Moreira <qualquercoisa6568@hotmail.com<mailto:qualquercoisa6568@hotmail.com>>:
Corrigido

2017-08-26 14:31 GMT-03:00 Ronneesley Moura Teles <notifications@github.com<mailto:notifications@github.com>>:

Ok, favor incluí-los na documentação então.
URL e ISSN são siglas, portanto caixa alta. Aguardo a correção, mas encerro a tarefa.

**Comment by Ronneesley** [comment]
Fazer o comentário da classe.

**Comment by dmcardoso** [comment]
Feito.



Enviado do meu smartphone Samsung Galaxy.


-------- Mensagem original --------
De: Ronneesley Moura Teles <notifications@github.com>
Data: 30/08/17 20:44 (GMT-03:00)
Para: Ronneesley/redesocial <redesocial@noreply.github.com>
Cc: DanielIFGoianoSI <qualquercoisa6568@hotmail.com>, Assign <assign@noreply.github.com>
Assunto: Re: [Ronneesley/redesocial] Criação a classe DTO para artigo (#198)


Fazer o comentário da classe.
