### ISSUE TITLE
Criar a classe DAO para artigo método inserir()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#199]

**Comment by ghost** [comment]
Enviado aguardando correção

**Comment by ghost** [comment]
Enviei através do computador do Daniel, esqueci de deslogar aí o submit foi com o nome do Daniel

**Comment by Ronneesley** [comment]
O código:
if (dto.getArtigo().equals("")){
            throw new Exception("O arquivo do artigo não pode estar vazio!");
}
Pode ser retirado as validações passamos para os arquivos BO.
