### ISSUE TITLE
Criação do HTML para o tipo texto

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#20]

**Comment by gusttavogomes** [comment]
@Ronneesley Post de texto está pronto. Porém não tem a barra de dar UPs e nem a parte de comentário.
Tem necessidade de se fazer essa parte agora, ela vai ser designada para outra pessoa ou foi até já feita por outra pessoa?
Aguardo resposta.

**Comment by Ronneesley** [comment]
Gostaria que criasse no seu **issue** mesmo a barra de UPs e a parte do comentário lembrando que existem comentários de comentário.

**Comment by gusttavogomes** [comment]
Pronto. Manda mais. rsrs

**Comment by Ronneesley** [comment]
Perfeito.
