### ISSUE TITLE
Criar a classe DAO para artigo método excluir()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#201]

**Comment by FernandoMacielS** [comment]
Feito! Tiver mais pode passar!

**Comment by FernandoMacielS** [comment]
Passar pra outro, não pra mim. o/

**Comment by Ronneesley** [comment]
Não há seleção de atividades. Você está encarregado desta!

**Comment by FernandoMacielS** [comment]
Rapaz, tira essa atividade atrasada aí, mandei tem 1 século, esse git não ta fácil de lidar. Vou mandar novamente.

**Comment by FernandoMacielS** [comment]
Enviado novamente.

**Comment by Ronneesley** [comment]
Me mostra qual foi o commit que você mandou que reviso. Atividade terminada.
