### ISSUE TITLE
Criar a classe DAO para artigo método selecionar()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#202]

**Comment by gleyson-alves** [comment]
Criação da classe DAO para artigo método selecionar() #202

**Comment by gleyson-alves** [comment]
Criação da classe DAO para artigo método selecionar() #202 **corrigido**

**Comment by Ronneesley** [comment]
Conferir os campos: areaConhecimento e URL no DER. Veja os demais também.
