### ISSUE TITLE
Criar a classe BO para artigo

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#204]

**Comment by iankatalita** [comment]
Olá, menino Ronne. Acho que terminei o BO de artigo, porém está dando um erro onde diz que tenho que fazer o public class ser uma classe abstract. O que eu faço, o meu está dando erro pq o DAO não está pronto ou pq eu sou derte mesmo e fiz errado???        OBSERVAÇÃO: ArtigoBO.java já está comentado também.

**Comment by Ronneesley** [comment]
Ok
