### ISSUE TITLE
Criar os testes para artigos, método alterar()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#206]

**Comment by laracaroline** [comment]
Ronne, falta o inserir do artigoDAO pra eu fazer esse. Se não tiver ninguém passa pra mim :)

**Comment by laracaroline** [comment]
Feito! (FINALMENTE \O/)
Mexi no ArtigoDAO porque haviam erros no inserir e no alterar.

**Comment by Ronneesley** [comment]
Ok, perfeito.
