### ISSUE TITLE
Criar os testes para artigos, método excluir()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#207]

**Comment by Ronneesley** [comment]
Não foi feito (5 semanas de atraso)

**Comment by Lucianodcb** [comment]
Boa parte do tempo algumas das classes necessárias para fazer o teste não estavam pronta, então não dava pra fazer, mas eu já comecei, mas como não estava(está) funcionado eu não dei commit, agora eu dei, mas tem erro.

**Comment by Lucianodcb** [comment]
Tá pronto e funcionando

**Comment by Ronneesley** [comment]
A indentação não está boa, fecho mas aguardo a correção.
