### ISSUE TITLE
Criar os testes para artigos, método selecionar()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#208]

**Comment by LuckasAzevedo** [comment]
Posso fazer  a classe DAO para artigo método inserir() ? porque os métodos de teste do artigo estão ficando atrasados.

**Comment by LuckasAzevedo** [comment]
feito.

**Comment by Ronneesley** [comment]
A indentação não está boa, por mais que o teste esteja aprovado.
Aguardo a correção para fechar.

**Comment by LuckasAzevedo** [comment]
feito, aguardo minha estrela   :)  :+1:

**Comment by Ronneesley** [comment]
Ok. Parabéns, continue assim!
