### ISSUE TITLE
Criar os testes para artigos, método listar()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#209]

**Comment by Macilon** [comment]
Feito !

2017-08-25 22:23 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Macilon** [comment]
Mandei esse enganado, ainda não finalizei.

2017-09-20 21:57 GMT-03:00 Macilon Arruda <macilonarruda1@gmail.com>:

**Comment by Macilon** [comment]
Feito, aguardo a correção.

**Comment by Ronneesley** [comment]
Está falhando.

**Comment by Macilon** [comment]
Corrigido, aguardo a resposta.

**Comment by Ronneesley** [comment]
OK
