### ISSUE TITLE
Estudar e aprender a utilizar o Astah Share para edição de projeto com mais de uma pessoa

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#210]

**Comment by Ronneesley** [comment]
Olá, segue a primeira atividade de pesquisa de vocês. 

Gostaria que estudassem a ferramenta Astah Share (http://astah.net/editions/share) e escrevessem um relatório de duas páginas de como configurá-lo para funcionar a edição de projetos com o Astah Community (http://astah.net/editions/community) em duas ou mais máquinas ao mesmo tempo.

Será apresentado na sexta-feira para a sala.

**Comment by Ronneesley** [comment]
Apresente o relatório na pasta de *pesquisas*

**Comment by thaliasantana** [comment]
Relatório inserido :)

**Comment by thaliasantana** [comment]
Aaaaaah, dúvidas!
1) O relatório precisa de referências? Usamos todas as informações do site, mas precisa?
2) Precisa colocar também o arquivo editável aqui?
3) Iremos mostrar pra sala como tinha dito?

**Comment by Ronneesley** [comment]
(Sim)^3

**Comment by thaliasantana** [comment]
E vai apresentar hoje???? 
Precisa de referenciar no texto também? Do tipo (ASTAH SHARE, 2017)?

**Comment by Ronneesley** [comment]
Sim, prepare contas para todos os alunos. Já li o relatório, coloque as referencias, o arquivo editável e preparem-se para hoje a noite.
