### ISSUE TITLE
Criação do diagrama de classes dos DTOs

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#211]

**Comment by Ronneesley** [comment]
Edite no arquivo **uml.asta** na pasta **projeto**.
Crie um diagrama de classes e inclua as classes: Pais, Estado, Cidade, Usuario, Multimidia, Album, ... todas as que estão no pacote DTO do NetBeans.
Em seguida coloque seus atributos: id, nome, etc. que é específico de cada classe.

**Comment by Ronneesley** [comment]
Esta tarefa tem alta rotatividade, então a coloquei para sexta-feira que vem.

**Comment by Ronneesley** [comment]
Não foi feito (3 semanas de atraso)

**Comment by jonatas-rezende** [comment]
estamos desenvolvendo ela, vc repassou ela pro nosso grupo

**Comment by Ronneesley** [comment]
Atividade fechada.

**Comment by Ronneesley** [comment]
Sem pontuação.
