### ISSUE TITLE
Criar Servlet de Estados para Inserir

### ISSUE THREAD

**Issue by IgorJustinoRodrigues** [Ronneesley/redesocial#214]

**Comment by PauloHenriqueAraujo** [comment]
Criei o servlet e corrigi os erros que tinham. Dá uma conferida lá. Fiz com base nos modelos que já tinham feito.

**Comment by Ronneesley** [comment]
-- Aguardo a confirmação do Igor de que está pronto.

**Comment by PauloHenriqueAraujo** [comment]
@IgorJustinoRodrigues

**Comment by IgorJustinoRodrigues** [comment]
@Ronneesley conferido, falta apenas listar os países do banco, fora isso creio que esteja pronto.

**Comment by Ronneesley** [comment]
De fato. Nas linhas:

Estado estado = new Estado();
estado.setNome(request.getParameter("estado"));

Falta também preencher o país, com o código que virá da interface gráfica.

**Comment by PauloHenriqueAraujo** [comment]
Terminei as correções e adicionei os comentários.

**Comment by Ronneesley** [comment]
OK
