### ISSUE TITLE
Criar Servlet de Cidade para Inserir

### ISSUE THREAD

**Issue by IgorJustinoRodrigues** [Ronneesley/redesocial#215]

**Comment by dmcardoso** [comment]
Fecha aí

**Comment by Ronneesley** [comment]
-- Aguardo a confirmação do Igor para conferir

**Comment by IgorJustinoRodrigues** [comment]
@Ronneesley, conferi o código, creio que esteja correto, lembrando apenas da questão de listar os países e estados do banco.

**Comment by Ronneesley** [comment]
Iden, também falta preencher o estado que virá o código da interface gráfica.

**Comment by dmcardoso** [comment]
Corrigido

**Comment by dmcardoso** [comment]
Ronne, corrigi, porém não conseguir testar. Aguardo resposta

**Comment by dmcardoso** [comment]
Finalizado, ronne, agora acredito que esteja correto. Está inserindo conforme o desejado

**Comment by dmcardoso** [comment]
Houve um probleminha no commit kkk não percebi que a conta do Davi estava logada no meu github, como ele havia feito as atividades dele no meu PC e não lembrei de voltar

**Comment by Ronneesley** [comment]
É interessante que o código JSP:
*select name="estados" class="campo" id="estado"*
O *name* seja apenas **estado**, uma vez que por mais que o *combobox* tenha vários elementos, somente um é selecionado e enviado.

Assim a linha muda:
*Integer idEstado = Integer.parseInt(request.getParameter("estados"));*

**Comment by dmcardoso** [comment]
Ok, corrigido.


________________________________
De: Ronneesley Moura Teles <notifications@github.com>
Enviado: sábado, 16 de setembro de 2017 12:34
Para: Ronneesley/redesocial
Cc: DanielIFGoianoSI; Assign
Assunto: Re: [Ronneesley/redesocial] Criar Servlet de Cidade para Inserir (#215)


É interessante que o código JSP:
O name seja apenas estado, uma vez que por mais que o combobox tenha vários elementos, somente um é selecionado e enviado. Assim a linha muda: Integer idEstado = Integer.parseInt(request.getParameter("estados"));
