### ISSUE TITLE
Criação do HTML de cadastro de cidades

### ISSUE THREAD

**Issue by IgorJustinoRodrigues** [Ronneesley/redesocial#216]

**Comment by dmcardoso** [comment]
Fecha aí

**Comment by IgorJustinoRodrigues** [comment]
A tag select não tem o atributo "type", confere também se o "name" dos três
campos é esse mesmo, se não me engano eles são outros.

2017-08-31 18:26 GMT-03:00 DanielIFGoianoSI <notifications@github.com>:

**Comment by IgorJustinoRodrigues** [comment]
Ficou muito bom!

Em 31 de agosto de 2017 18:30, Igor Justino <igor98rodrigues@gmail.com>
escreveu:

**Comment by dmcardoso** [comment]
Corrigido



Enviado do meu smartphone Samsung Galaxy.


-------- Mensagem original --------
De: Igor Justino Rodrigues <notifications@github.com>
Data: 31/08/17 18:31 (GMT-03:00)
Para: Ronneesley/redesocial <redesocial@noreply.github.com>
Cc: DanielIFGoianoSI <qualquercoisa6568@hotmail.com>, Assign <assign@noreply.github.com>
Assunto: Re: [Ronneesley/redesocial] Criação do HTML de cadastro de cidades (#216)

A tag select não tem o atributo "type", confere também se o "name" dos três
campos é esse mesmo, se não me engano eles são outros.

2017-08-31 18:26 GMT-03:00 DanielIFGoianoSI <notifications@github.com>:

**Comment by Ronneesley** [comment]
Ok. Pontuação marcada nos critérios Design e Participação em grupos para ambos.
