### ISSUE TITLE
Criação do HTML de cadastro de estados

### ISSUE THREAD

**Issue by IgorJustinoRodrigues** [Ronneesley/redesocial#217]

**Comment by PauloHenriqueAraujo** [comment]
Está pronto!

**Comment by IgorJustinoRodrigues** [comment]
Ficou muito bom,

Acho que você esqueceu alguma 'div' aberta no seu código, confere por
gentileza. Fora isso ta ok.

2017-08-31 10:54 GMT-03:00 Paulo Henrique <notifications@github.com>:

**Comment by IgorJustinoRodrigues** [comment]
O atributo name não pode ser o mesmo nos dois campos.

Em 31 de agosto de 2017 18:21, Igor Justino <igor98rodrigues@gmail.com>
escreveu:

**Comment by PauloHenriqueAraujo** [comment]
Fiz as correções lá. Fechei a tag div que estava aberta e mudei os atributos para "estado" e "pais".

**Comment by Ronneesley** [comment]
Perfeito, confirmação recebida. Verificado.
Pontuação nos critérios Design e Participação em grupo, para ambos.
