### ISSUE TITLE
Criar view dos aportes mais visualizados

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#218]

**Comment by jonatas-rezende** [comment]
Sobre a view, na tabela aportes não tem valores de quantos foram visualizados, a tabela referencia a tabela de postagens e lá sim tem quantidade de visualizações, mas das postagens... seria esse valor que eu devo filtrar?

**Comment by Ronneesley** [comment]
Sim é esse valor que será utilizado conforme a infra-estrutura, um aporte é uma postagem.

**Comment by jonatas-rezende** [comment]
bateu uma dúvida... o título fala dos "aportes mais visualizados", quantos a view deve exibir como resposta?

**Comment by jonatas-rezende** [comment]
View e dados fictícios criados e postados, se não for desse jeito eu altero depois.

**Comment by Ronneesley** [comment]
OK.
