### ISSUE TITLE
Criação da documentação de caso de uso de aceite de solicitação de amizade

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#221]

**Comment by Jonathanss123** [comment]
Olá boa noite ! Ronne fiz a documentação dps da uma olhada la ...  UC14.

**Comment by Jonathanss123** [comment]
outra pergunta ... como insiro a imagem do protótipo no documento ? pois preciso colocar igual os outros tipo um hiperlink para a imagem.

**Comment by Ronneesley** [comment]
Ok. Aguardo a referência da imagem.
