### ISSUE TITLE
Criar uma view para exibir a quantidade de vezes que uma palavra-chave foi usada nas postagens/aportes

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#225]
-----
Palavra-chave | Quantidade
-----
Informática      | 1000
Código            |  9750
Biologia           |    500

**Comment by thaliasantana** [comment]
Ronne, vc quer que conte quantas vezes uma palavra-chave foi usada em diversas postagens? 
Sinceramente, estou tendo inúmeras interpretações dessa atividade... De verdade. Tem como detalhar mais? 
Ou amanhã a noite eu te acho e tiro minhas dúvidas do que vc realmente quer, pq estou bugada :/

**Comment by thaliasantana** [comment]
Feito! Veja se é realmente isso que queria :)

**Comment by Ronneesley** [comment]
OK
