### ISSUE TITLE
Como representar as relações de amizade?

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#226]
Pensar em qual estrutura de dados utilizar para representar as relações de amizade

**Comment by Ronneesley** [comment]
O relatório deve possuir até 5 páginas e deve ser colocado na pasta de pesquisa até dia 13/09.

**Comment by PauloHenriqueAraujo** [comment]
Pessoal, iniciei a pesquisa. O documento está na pasta de pesquisas nomeado como "Relações de amizades.odt". Fiquem a vontade para modificar e corrigir.

**Comment by Ronneesley** [comment]
OK
