### ISSUE TITLE
Criar view de usuários por pais

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#228]
--
Pais          | Qtde
--
Brasil        | 1000
Argentina  | 2000

**Comment by Ronneesley** [comment]
Não encontrada (3 semanas de atraso)

**Comment by Jonathanss123** [comment]
Boa noite !! Rone criei a View depois da uma olhada la ... gostaria de ver também como q testa pra ver se ela esta funcionando.

**Comment by Jonathanss123** [comment]
Boa noite !! Rone criei a View depois da uma olhada la ... gostaria de ver também como q testa pra ver se ela esta funcionando.

**Comment by Ronneesley** [comment]
OK
