### ISSUE TITLE
Criar view de usuários por cidade

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#230]
--
Cidade  | Estado | Pais | Qtde
--
Ceres    | Goiás | Brasil | 100
Goiânia | Goiás | Brasil | 200

Colocar também o id da cidade, estado e país

**Comment by IgorJustinoRodrigues** [comment]
Hoje que vi que tinha essa atividade para fazer, rsrsrsrs
Está pronta.

2017-09-05 12:25 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Mostre-me em sala

**Comment by Ronneesley** [comment]
OK
