### ISSUE TITLE
Criar view da quantidade de comentários do usuário

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#233]
Dependente da issue #231

--
Usuário | Qtde. Comentários
--
Roni      | 50
Ana       | 500
Bob       | 250

**Comment by gusttavogomes** [comment]
Feito.

**Comment by Ronneesley** [comment]
Gusttavo, crie dados fictícios e salve um arquivo SQL na pasta **dados_ficticios_para_views** e prove que o seu SQL funciona na prática.

**Comment by gusttavogomes** [comment]
Já fiz lá e testei. Dá uma olhada e me passa o _feedback_ depois.

**Comment by gusttavogomes** [comment]
Fechei sem querer a issue. rs

**Comment by gusttavogomes** [comment]
Já fiz lá e testei. Dá uma olhada e me passa o feedback depois.

**Comment by gusttavogomes** [comment]
View arrumada e com os dados fictícios criados.

**Comment by Ronneesley** [comment]
Gusttavo me mostra na sala na próxima quarta.

**Comment by Ronneesley** [comment]
Ok
