### ISSUE TITLE
Criar view da quantidade de multimídias por album do usuário

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#234]
--
Usuário | Álbum                 | Qtde Multmídias
--
Ana       | Sem categoria    | 100
Ana       | Férias                 | 37
Bob       | Viagem a Ceres  | 49

**Comment by gleyson-alves** [comment]
Criação view da quantidade de multimídias por album do usuário #234

**Comment by Ronneesley** [comment]
Ok
