### ISSUE TITLE
Criar view da quantidade de relacionamentos de um usuário

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#235]
--
Usuário | Tipo         |  Qtde
--
Ana       | Amizade  |  50
Bob       | Amizade  |  180
João      | Amizade  |  500

Conferir na documentação os diferentes tipos de relacionamentos como especificado no DER

**Comment by Ronneesley** [comment]
Não encontrada (3 semanas de atraso)

**Comment by Ronneesley** [comment]
Mostre-me em sala quando estiver pronta

**Comment by FernandoMacielS** [comment]
Feito. Estou no aguardo do ponto extra por ter criado a tabela "tipos" e resolvido o problema das definições de relacionamentos e a duplicação da coluna("tipo") na tabela "relacionamentos" e "grupos".

**Comment by Ronneesley** [comment]
Mostre-me em sala.

**Comment by Ronneesley** [comment]
Houve atraso, deveria ter sido apresentado dia 04/10 (1 semana). Não deixe de me mostrar hoje.

**Comment by Ronneesley** [comment]
Retirar a tabela de tipos ou tentar explicar ela com clareza, parece que está indevida.

**Comment by Ronneesley** [comment]
Ok
