### ISSUE TITLE
Criar view da quantidade de aportes por categoria

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#236]
--
Categoria                                        | Qtde. Aportes
--
Inteligência Artificial                        | 900
Processamento digital de imagens | 500
Algoritmos                                       | 2000

**Comment by BrenerGomesSI** [comment]
Ja realizei o commit desta atividade.

**Comment by Ronneesley** [comment]
Mostre-me em sala

**Comment by Ronneesley** [comment]
Não esqueça de me mostrar em sala.

**Comment by BrenerGomesSI** [comment]
View criada e testada, também fiz a criação dos dados fictícios para a view
funcionar.

2017-10-01 17:45 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Ok, me mostre na aula hoje então.

**Comment by Ronneesley** [comment]
Ok
