### ISSUE TITLE
Criar view da quantidade de comentários por postagem

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#238]
--
Postagem        | Qtde. Comentários
--
Como ABC?    | 500
Você viu?        | 150
Olha isso!        | 1200

**Comment by ghost** [comment]
Enviado aguardando correção

**Comment by ghost** [comment]
Enviei através do computador do Daniel, esqueci de deslogar aí o submit foi com o nome do Daniel

**Comment by Ronneesley** [comment]
Daniel me mostre na sala com os seus dados.

**Comment by Ronneesley** [comment]
Você não me mostrou em sala.

**Comment by ghost** [comment]
Ta pronto!

**Comment by Ronneesley** [comment]
Você não me mostrou hoje de novo!

**Comment by Ronneesley** [comment]
Ok

**Comment by Ronneesley** [comment]
Quem fez foi o Daniel e o Davi não fez.
