### ISSUE TITLE
Criar view da quantidade de novos usuários por mês

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#239]
--
Mês          | Ano   | Qtde. Novos Usuários
--
Janeiro     | 2017 | 500
Fevereiro | 2017 | 150
Março      | 2017 | 600

**Comment by dmcardoso** [comment]
Finalizei a tarefa, acredito que esteja correto. Aguardo a correção

**Comment by Ronneesley** [comment]
Para encerrar preciso que preencha com dados fictícios na pasta: dados_ficticios_para_views para provar que o que fez está funcionando.

**Comment by dmcardoso** [comment]
Ronne, para pegar os inserts que eu já tinha feito eu fiz o dump do banco e copiei os inserts realizados. Nos inserts de cidade, estado e país eu alterei para não inserir com ID, porém como o de usuário eram muitos eu mantive, então acredito que terá que dropar e criar o banco de novo para realizar o teste.

Aguardo resposta


________________________________
De: Ronneesley Moura Teles <notifications@github.com>
Enviado: quarta-feira, 6 de setembro de 2017 18:21
Para: Ronneesley/redesocial
Cc: DanielIFGoianoSI; Assign
Assunto: Re: [Ronneesley/redesocial] Criar view da quantidade de novos usuários por mês (#239)


Para encerrar preciso que preencha com dados fictícios na pasta: dados_ficticios_para_views para provar que o que fez está funcionando.

**Comment by Ronneesley** [comment]
Oi Daniel,
        O problema do DUMP é de onde vieram os dados, pois se foram das unidades de testes está cheio de dados repetidos e que não favorecem o entendimento. Assim sugiro mesmo, que faça o script na mão.

**Comment by dmcardoso** [comment]
Corrigido.


________________________________
De: Ronneesley Moura Teles <notifications@github.com>
Enviado: segunda-feira, 11 de setembro de 2017 11:48
Para: Ronneesley/redesocial
Cc: DanielIFGoianoSI; Assign
Assunto: Re: [Ronneesley/redesocial] Criar view da quantidade de novos usuários por mês (#239)


Oi Daniel,

    O problema do DUMP é de onde vieram os dados, pois se foram das unidades de testes está cheio de dados repetidos e que não favorecem o entendimento. Assim sugiro mesmo, que faça o script na mão.

**Comment by Ronneesley** [comment]
OK
