### ISSUE TITLE
Criar view da quantidade de estados por país

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#240]
--
Pais       | Qtde. Estados
--
Brasil     | 27
EUA       | 54
Canadá  | 38

**Comment by cybersecwoman** [comment]
É para criar o que exatamente? Uma tabela no banco?

**Comment by Ronneesley** [comment]
Uma **view**.

**Comment by Ronneesley** [comment]
Mostre-me em sala

**Comment by Ronneesley** [comment]
O SQL está falhando.

**Comment by Ronneesley** [comment]
Ok
