### ISSUE TITLE
Criar view da quantidade de cidades por estado

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#241]
--
Estado             | Pais   | Qtde. Cidades
--
Goiás               | Brasil | 600
Minas Gerais   | Brasil | 300
São Paulo        | Brasil | 800

**Comment by adallberto** [comment]
View criada e testada!

**Comment by Ronneesley** [comment]
Mostre-me em sala

**Comment by Ronneesley** [comment]
Ok. Parabéns, continue assim!
