### ISSUE TITLE
Criar o DAO de categorias: inserir

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#244]

**Comment by LuckasAzevedo** [comment]
Ok , feito

**Comment by Ronneesley** [comment]
O nome da tabela está errado. Não precisa do código:

        if(c.getDescricao().equals("")){
            throw new Exception("O campo categoria não pode estar vazio!");
        }

Fecho a atividade mesmo assim e aguardo a correção.

**Comment by LuckasAzevedo** [comment]
Exclusão  feita!

**Comment by LuckasAzevedo** [comment]
Posso fazer  a <https://github.com/Ronneesley/redesocial/issues/199> classe
DAO para artigo método inserir
<https://github.com/Ronneesley/redesocial/issues/199>*()
<https://github.com/Ronneesley/redesocial/issues/199> ?* porque os métodos
de teste do artigo estão ficando atrasados.

2017-09-06 18:47 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:
