### ISSUE TITLE
Criar o DAO de categorias: alterar

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#245]

**Comment by laracaroline** [comment]
Feito!

**Comment by Ronneesley** [comment]
O arquivo CategoriaDAO.java não está no projeto. Dê uma olhada para ver o que aconteceu.

**Comment by laracaroline** [comment]
Ronne, achei aqui. Ontem o Wesley deu um "merge branch" e aí excluiu esse CategoriaDAO. Vou ver como recupera.
Em 16 de set de 2017, às 10:48, Ronneesley Moura Teles <notifications@github.com<mailto:notifications@github.com>> escreveu:


O arquivo CategoriaDAO.java não está no projeto. Dê uma olhada para ver o que aconteceu.

**Comment by Ronneesley** [comment]
Essa parte do código foi transferida para os BOs:

        if (c.getDescricao().trim().equals("")){
            throw new Exception("A descrição não pode estar vazia!");
        }

Perfeito.
