### ISSUE TITLE
Criar o DAO de categorias: selecionar

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#248]

**Comment by Macilon** [comment]
Feito Rone!

**Comment by Macilon** [comment]
Feito !

2017-09-05 12:56 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Macilon** [comment]
Aguardo a resposta

2017-09-20 21:58 GMT-03:00 Macilon Arruda <macilonarruda1@gmail.com>:

**Comment by Ronneesley** [comment]
O nome da tabela está errado

**Comment by Macilon** [comment]
Corrigido, aguardo a resposta.

**Comment by Ronneesley** [comment]
OK
