### ISSUE TITLE
Criação Protótipo Listagem de Países

### ISSUE THREAD

**Issue by IgorJustinoRodrigues** [Ronneesley/redesocial#255]

**Comment by IgorJustinoRodrigues** [comment]
Vamos tentar seguir mais ou menos um mesmo padrão.

**Comment by dmcardoso** [comment]
Enviado, aguardo correção


________________________________
De: Igor Justino Rodrigues <notifications@github.com>
Enviado: quinta-feira, 14 de setembro de 2017 08:39
Para: Ronneesley/redesocial
Cc: DanielIFGoianoSI; Assign
Assunto: Re: [Ronneesley/redesocial] Criação Protótipo Listagem de Países (#255)


Vamos tentar seguir mais ou menos um mesmo padrão.

**Comment by Ronneesley** [comment]
Ok
