### ISSUE TITLE
Criação Protótipo Listagem de Cidades

### ISSUE THREAD

**Issue by IgorJustinoRodrigues** [Ronneesley/redesocial#256]

**Comment by IgorJustinoRodrigues** [comment]
Vamos tentar seguir mais ou menos um mesmo padrão.

**Comment by PauloHenriqueAraujo** [comment]
Atividade feita. Tentei padronizar ao máximo.

**Comment by IgorJustinoRodrigues** [comment]
@Ronneesley  tudo ok.

**Comment by Ronneesley** [comment]
Ok. Ígor com isso você marcou os 10 pontos de design.
