### ISSUE TITLE
Criação do HTML de listagem de Paises

### ISSUE THREAD

**Issue by IgorJustinoRodrigues** [Ronneesley/redesocial#257]

**Comment by IgorJustinoRodrigues** [comment]
Lembrando que já existe um arquivo listagem_paises.jsp, utilizável. Faça o seu HTML nele.

**Comment by dmcardoso** [comment]
Pronto.

**Comment by Daviifgoiano** [comment]
ok

**Comment by IgorJustinoRodrigues** [comment]
Ótimo,

Vou pedir a correção do Ronneesley

2017-09-15 20:11 GMT-03:00 Davi de Faria <notifications@github.com>:

**Comment by IgorJustinoRodrigues** [comment]
@Ronneesley 
Creio que esteja tudo ok.

**Comment by Ronneesley** [comment]
Ok
