### ISSUE TITLE
Criação do HTML de listagem de Cidades

### ISSUE THREAD

**Issue by IgorJustinoRodrigues** [Ronneesley/redesocial#258]

**Comment by PauloHenriqueAraujo** [comment]
Pronto

**Comment by PauloHenriqueAraujo** [comment]
@IgorJustinoRodrigues apenas me ajude com o botão de voltar.

**Comment by IgorJustinoRodrigues** [comment]
Paulo, parabéns ficou muito bom, temos apenas algumas alterações.
A identação do código pode ser melhorada, assim como o espaçamento das
linhas linhas.
O hr está com um erro, falta o style="".

Sobre o botão voltar, tente modificar a class direito, apagando o float e
inserindo margin-top e margin-left;

Obs.: bom trabalho com a acentuação!
Aguardo correção.

**Comment by PauloHenriqueAraujo** [comment]
@IgorJustinoRodrigues  Fiz as correções, também consegui modificar o botão conforme orientou. A questão da identação pode ser pq eu estou editando o texto no notepad++.
Acredito que agora esteja pronto.

**Comment by IgorJustinoRodrigues** [comment]
Ótimo, a tag <a> não tem value, então retirei ele.


2017-09-16 11:07 GMT-03:00 Paulo Henrique <notifications@github.com>:

**Comment by IgorJustinoRodrigues** [comment]
@Ronneesley, Creio que esteja pronto.

**Comment by Ronneesley** [comment]
OK
