### ISSUE TITLE
Pesquisar o algoritmo Viola e Jones de reconhecimento de faces

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#260]
Vale 5 estrelas em programação se mostrarem uma implementação em qualquer linguagem e explicá-la muito bem ou 10 estrelas se vocês mesmos programarem.
5 estrelas de pesquisa.

**Comment by Ronneesley** [comment]
Para dia 11/10.

**Comment by IgorJustinoRodrigues** [comment]
Estive pesquisando sobre o algoritmo, ele e muito complexo, seria bom nos reunirmos para discutir um pouco sobre oque vamos apresentar.

**Comment by cybersecwoman** [comment]
Certo combinamos pelo grupo do whatsapp

**Comment by Ronneesley** [comment]
Muito bem aprensentado!!! (Heitor não estava presente)
