### ISSUE TITLE
Criar DAO de PalavraChave: método selecionar

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#261]

**Comment by dmcardoso** [comment]
Criado e comentado. Aguardo correção.

**Comment by Ronneesley** [comment]
Muito bom. Confirmado agora pode ter sua equipe, caso queira. Parabéns.

@IgorJustinoRodrigues caso o Daniel opte por montar a equipe dele, você agora pode incluir outra pessoa.
Parabéns pelo trabalho.

**Comment by dmcardoso** [comment]
Obrigado. Montarei um grupo com a Lara, Davi e o Fernando.


________________________________
De: Ronneesley Moura Teles <notifications@github.com>
Enviado: sábado, 16 de setembro de 2017 12:41
Para: Ronneesley/redesocial
Cc: DanielIFGoianoSI; Assign
Assunto: Re: [Ronneesley/redesocial] Criar DAO de PalavraChave: método selecionar (#261)


Muito bom. Confirmado agora pode ter sua equipe, caso queira. Parabéns.

@IgorJustinoRodrigues<https://github.com/igorjustinorodrigues> caso o Daniel opte por montar a equipe dele, você agora pode incluir outra pessoa.
Parabéns pelo trabalho.
