### ISSUE TITLE
Criar DAO de PostagemPalavraChave método inserir

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#264]

**Comment by Ronneesley** [comment]
Não feito. (2 semanas de atraso)

**Comment by jrossini94** [comment]
Feito

**Comment by Ronneesley** [comment]
Não tem o parâmetro: , Statement.RETURN_GENERATED_KEYS e não é pstmt.executeQuery();

**Comment by jrossini94** [comment]
Professor removi o Statement.RETURN_GENERATED_KEYS
qual seria o comando para executar a query?  pstmt.executeUpdate();? 
nos outros inserts estão utilizando o executeQuery();

**Comment by jrossini94** [comment]
Professor confere a atividade por favor

**Comment by Ronneesley** [comment]
Ok
