### ISSUE TITLE
Criar DAO de PostagemPalavraChave método excluir

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#266]

**Comment by Ronneesley** [comment]
Não feito (2 semanas de atraso)

**Comment by jrossini94** [comment]
Feito

**Comment by jrossini94** [comment]
Professor confere a atividade por favor

**Comment by Ronneesley** [comment]
São duas chaves primárias. Assim como todos os outros: *PostagemMultimidiaDAO* e *PostagemAlbumDAO* que já estão de exemplo para ti. 
Arrume, mas mesmo assim fecho a atividade.
