### ISSUE TITLE
Criar DAO de PostagemPalavraChave método selecionar

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#267]

**Comment by laracaroline** [comment]
Está feito, porém como ainda não existe o DTO do PostagemPalavraChave vou esperar pra poder conferir. Fiquei em dúvida sobre o selecionar desse, eu fiz o selecionar das postagens a partir das palavras chaves. Foi o que fez mais sentido :)

**Comment by Ronneesley** [comment]
Veja que são duas chaves primárias, portanto 2 parâmetros.
Veja em PostagemMultimidiaDAO.

**Comment by laracaroline** [comment]
Então tenho que selecionar uma postagem específica de uma palavra chave específica só? Tipo, me retorna só uma postagem, no caso?

**Comment by Ronneesley** [comment]
Aguardo.

**Comment by laracaroline** [comment]
Corrigido, mas ainda está comentado. Aguardando criação do DTO.

**Comment by laracaroline** [comment]
Feito!

**Comment by Ronneesley** [comment]
OK
