### ISSUE TITLE
Criar DTO aporte

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#270]

**Comment by LuckasAzevedo** [comment]
Feito!

**Comment by Ronneesley** [comment]
Favor somente quebrar a linha entre os campos:
    /**
     * Atributo que identifica aporte
     */
    private Integer id;
    /**
     * Atributo que armazena o titulo do aporte
     */
    private String titulo;

Assim:

    /**
     * Atributo que identifica aporte
     */
    private Integer id;

    /**
     * Atributo que armazena o titulo do aporte
     */
    private String titulo;

**Comment by LuckasAzevedo** [comment]
Ok Feito, aguardo a estrela 😁!

2017-09-16 11:44 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:
