### ISSUE TITLE
Criar DAO aporte método alterar

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#272]

**Comment by Macilon** [comment]
Rone, está com alguns erros. Dei uma olhada e vi que no DTO do Aporte os "set da Categoria e da Postagem", não está batendo com o sql. Mas não sei se o problema está ai, depois dê uma olhada.

**Comment by Ronneesley** [comment]
Aguardo correção

**Comment by Macilon** [comment]
Feito !

2017-09-20 20:08 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Macilon** [comment]
Aguardo a resposta

**Comment by Macilon** [comment]
Aguardo a resposta

2017-09-20 21:56 GMT-03:00 Macilon Arruda <macilonarruda1@gmail.com>:

**Comment by Ronneesley** [comment]
O nome da tabela está errado e nem há cláusula condicional.
Faltou fechar a conexão.

**Comment by Macilon** [comment]
Corrigido, aguardo.

**Comment by Ronneesley** [comment]
Ok
