### ISSUE TITLE
Encontrar uma alternativa de editor WYSIWYG no lugar do CKEditor

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#275]
Pelo menos 3 alternativas. Justificar a escolha da melhor. Exemplificar como utilizar no HTML.
Elaborar relatório com pelo menos 5 páginas (**com códigos**).

**Comment by Ronneesley** [comment]
Para dia 22/09.

**Comment by jonatas-rezende** [comment]
JhtmlArea - https://github.com/crpietschmann/jHtmlArea – licença MIT
MarkltUp! - http://markitup.jaysalvat.com/home/ - licença MIT / GPL
TinyMCE - https://www.tinymce.com- possui versão community
NicEdit - http://nicedit.com/ - licença MIT

bom dia, encontrei esses editores

**Comment by dmcardoso** [comment]
bootstrap - https://github.com/mindmup/bootstrap-wysiwyg/

**Comment by Ronneesley** [comment]
Ok, parabéns ficou muito bom.
