### ISSUE TITLE
Ajustar a rotina de login e postar para apresentar as postagens

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#278]

**Comment by Ronneesley** [comment]
Não feito (2 semanas de atraso).

**Comment by aandreysr** [comment]
feito

**Comment by Ronneesley** [comment]
Você estava fazendo o redirect depois que a página já estava montada. Assim não funciona.

            RequestDispatcher rd = request.getRequestDispatcher("paginas/layout.jsp");
            rd.forward(request, response);
            
            response.sendRedirect("./FeedControle?operacao=Atualizar");

Tem que tirar as duas primeiras linhas.

Na hora de postar tinha que chamar a função atualizar.
