### ISSUE TITLE
Criação do diagrama de classes da entidade Postagem e Comentarios

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#288]

**Comment by Ronneesley** [comment]
OK

**Comment by Ley00** [comment]
Essa atividade o Sr. Me passou duas que foi “Criação do diagrama de classes da entidade Postagem e Comentarios<https://github.com/Ronneesley/redesocial/issues/288>” a primeira eu fiz hoje na sala já a segunda vou terminar agora.

De: Ronneesley Moura Teles<mailto:notifications@github.com>
Enviado:quarta-feira, 4 de outubro de 2017 22:01
Para: Ronneesley/redesocial<mailto:redesocial@noreply.github.com>
Cc:Warley01<mailto:warley_rodrigues_andrade@hotmail.com>; Assign<mailto:assign@noreply.github.com>
Assunto: Re: [Ronneesley/redesocial] Criação do diagrama de classes da entidade Postagem e Comentarios (#288)


Closed #288<https://github.com/Ronneesley/redesocial/issues/288>.

**Comment by Ley00** [comment]
Me passe outra atividade

De: Ronneesley Moura Teles<mailto:notifications@github.com>
Enviado:quarta-feira, 4 de outubro de 2017 22:01
Para: Ronneesley/redesocial<mailto:redesocial@noreply.github.com>
Cc:Warley01<mailto:warley_rodrigues_andrade@hotmail.com>; Assign<mailto:assign@noreply.github.com>
Assunto: Re: [Ronneesley/redesocial] Criação do diagrama de classes da entidade Postagem e Comentarios (#288)


Closed #288<https://github.com/Ronneesley/redesocial/issues/288>.

**Comment by Ronneesley** [comment]
Computarei mais um ponto a esta atividade, visto que eram dois diagramas.
