### ISSUE TITLE
Criação do diagrama de classes da entidade Multimidias e Albuns

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#290]

**Comment by jonatas-rezende** [comment]
criado, aguardo comentário se está correto ou precisa alterar

**Comment by Ronneesley** [comment]
Não encontrei.

**Comment by Ronneesley** [comment]
Mostre-me o *commit* e esta mensagem para rever a situação depois.

**Comment by jonatas-rezende** [comment]
![image](https://user-images.githubusercontent.com/30481949/31058613-fe222c9c-a6cc-11e7-9008-bfe2b1ba6351.png)

está no arquivo projeto.tex

no pdf dá pra visualizar, eu fiz e postei dia 22/09

**Comment by Ronneesley** [comment]
Cadê o arquivo do Astah? Coloque-o na pasta **projeto**. (me avise quando fizer)
Multimidia e Album possuem apenas métodos *get* e *set*

**Comment by Ronneesley** [comment]
Cadê o arquivo do Astah? Coloque-o na pasta **projeto**. (me avise quando fizer)
Multimidia e Album possuem apenas métodos *get* e *set*

**Comment by jonatas-rezende** [comment]
coloquei o arquivo dentro da pasta projeto/diagramas/

eu tinha colocado uma imagem lá, tem como referenciar um arquivo do astah dentro do latex?

**Comment by Ronneesley** [comment]
Você referencia a imagem normalmente, indicando o caminho onde ela está em relação ao caminho em que o latex está.

**Comment by jonatas-rezende** [comment]
atualizado

**Comment by Ronneesley** [comment]
Ainda não encontrei o arquivo na pasta de projeto.

**Comment by jonatas-rezende** [comment]
![image](https://user-images.githubusercontent.com/30481949/31298968-c7a8a2c8-aac2-11e7-9d1b-c1de8762033e.png)

**Comment by Ronneesley** [comment]
A pasta de projeto é **redesocial/projeto** você está na pasta de projeto da **documentação**.

**Comment by Ronneesley** [comment]
Ok
