### ISSUE TITLE
Criar BO de Categoria

### ISSUE THREAD

**Issue by dmcardoso** [Ronneesley/redesocial#294]

**Comment by laracaroline** [comment]
Ta pronto :D

**Comment by dmcardoso** [comment]
Conferido, Lara. Ficou perfeito.
Só uma coisa que acho que você deixou passar. O método de validação de chave primária não foi comentado. Só acrescentar isso e estará terminado.

**Comment by dmcardoso** [comment]
@Ronneesley atividade finalizada

**Comment by Ronneesley** [comment]
Ok. Parabéns pelo trabalho.
