### ISSUE TITLE
Correções gerais no banco de dados DER

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#304]
1) Corrigir o nome da coluna **vizualizacoes** em postagens para **visualizacoes** com S e não com Z.

2) Alinhar as tabelas de forma a minimizar o cruzamento de linhas

**Comment by BrenerGomesSI** [comment]
Realizei as correções, no aguardo!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-10-06 17:04 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Ainda tem tabelas que você deve alinhar melhor, alguns exemplos:
1) artigos e autores, na vertical
2) postagens_artigos e artigos na horizontal
3) albuns e postagens_albuns na vertical

Mesmo assim fecho a tarefa, mas aguardo essa correção.
