### ISSUE TITLE
Criação do diagrama de classes de CategoriaDAO

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#313]

**Comment by Ronneesley** [comment]
Atrasado: 7 semanas de atraso.

**Comment by BrenerGomesSI** [comment]
Feito.

**Comment by Ronneesley** [comment]
O nome do arquivo físico deve ser *CategoriaDAO.png* e não *Categoria_DAO.png*.
Diminuir o tamanho do pacote para focar somente na classe.
