### ISSUE TITLE
Criar o diagrama de classes de PostagemMultimidiaBO

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#334]

**Comment by Macilon** [comment]
Feito!

2017-10-06 17:52 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Não foi exportado para imagem.

**Comment by Macilon** [comment]
Pronto.

**Comment by Ronneesley** [comment]
Não feche as atividades @Macilon

**Comment by Macilon** [comment]
Perdão. Havia fechado sem querer na hora que comentei aqui! Aguardo a pontuação...

**Comment by Ronneesley** [comment]
Ok
