### ISSUE TITLE
LaTeX utilizar long table para permitir as tabelas dos casos de uso quebrarem a página

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#342]

**Comment by IgorJustinoRodrigues** [comment]
Ronne, não to conseguindo fazer funcionar, pesquisei sobre o assunto,
consegui fazer uma tabela que quebra a página, mas quando coloco ela no
comando newcommand da erro.

2017-10-06 18:03 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by IgorJustinoRodrigues** [comment]
O arquivo chamado "long table.txt", está o código que estou trabalhando e
está dando erro.
Já inclui o comando \usepackage{longtable} no documentacao.tex



Em 9 de outubro de 2017 13:49, Igor Justino <igor98rodrigues@gmail.com>
escreveu:

**Comment by Ronneesley** [comment]
OK
