### ISSUE TITLE
Criar protótipo para a pagina de um evento

### ISSUE THREAD

**Issue by Salminunes** [Ronneesley/redesocial#348]

**Comment by gusttavogomes** [comment]
Feito.
[https://github.com/Ronneesley/redesocial/blob/primeira_codifica%C3%A7%C3%A3o/prototipos/resultados/tela_evento.png](url)

**Comment by Salminunes** [comment]
Tá bacana. Acho que pode colocar também pra aparecer o local geral do evento. E nas atividade pode colocar o local também. Ex: Atividade - Local / Minucurso de java - Lab. 04.

**Comment by Salminunes** [comment]
A gente pode pensar também em um local pra referenciar a pessoa responsável por aquela atividade, no caso de palestrante por exemplo. Ex: 
Tipo de Atividade    -    Descrição    -    Professor    -    Local   -   Horário
Minucurso -  Algorítimos Genéticos - Ronneesley Moura Teles - Lab. 04.  - 19:00 as 22:00
E no nome do palestrante, colocar um link onde clicando no nome leva o usuário pra página do palestrante (Caso seja cadastrado na rede social) pra conhecer melhor a pessoa, ver informações do perfil dela como local onde ministra aula, formação e etc.

**Comment by gusttavogomes** [comment]
O local do evento geral é realmente interessante colocar.
Agora essas informações sobre as atividades em si, local que será realizada, a descrição, quem é a pessoa responsável por aquela atividade, isso eu já acho que não ficaria interessante ficar exposto logo nessa parte, por isso que coloquei o botão de "Mais informações" que ao ser acionado, exibiria essas informações, deixando a tela de evento, menos saturada, mas essa é só uma ideia, se achar melhor eu faço as alterações.

**Comment by Salminunes** [comment]
Na minha visão muitas vezes as pessoas vão em certos cursos/palestras mais por causa do palestrante do que por causa do proprio curso, por isso acho interessante colocar ele.

**Comment by gusttavogomes** [comment]
Faz sentido, fiz as alterações no protótipo já, dá uma olhada e me dá um feedback.

**Comment by Salminunes** [comment]
Ok, pronto.

**Comment by Ronneesley** [comment]
OK
