### ISSUE TITLE
Corrigir a classe PostagemAlbumDAO

### ISSUE THREAD

**Issue by dmcardoso** [Ronneesley/redesocial#351]

**Comment by laracaroline** [comment]
Feito! Confere se ta tudo okay, e me dê um retorno, por favor. Fiquei em dúvida em algumas, mas olhando outros acho que consegui resolver.
Nota: o inserir() não estava feito, daí procurei se tinha sido passado pra alguém e encontrei, é a #82, ta com atraso consecutivo, tinha sido passada pro Heitor no dia 09 de Agosto e tomei a liberdade de fazer, não temos tempo de ficar esperando. @Ronneesley veja essa questão também.

**Comment by Ronneesley** [comment]
Ok
