### ISSUE TITLE
Correção da documentação inteira

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#352]
Valendo 10 estrelas com 2 semanas de prazo (20/10/2017)

**Comment by thaliasantana** [comment]
Pronto!!!

**Comment by Ronneesley** [comment]
Tem várias figuras sem o referenciamento correto.
O diagrama de caso de uso já feito não foi adicionado.
Os diagramas de classes já prontos não foram adicionados.

Aguardo a correção até sexta.

**Comment by Ronneesley** [comment]
OK. Parabéns. Ficou muito bom!
