### ISSUE TITLE
Avaliar o tipo de relacionamento com suas diferenças regras de negócio

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#354]

**Comment by FernandoMacielS** [comment]
Não encontrei motivos suficientes para manter a tabela "tipos", logo fiz o retorno as ligações e campos existentes anteriormente.

**Comment by Ronneesley** [comment]
Então volte o tipo de relacionamento, na tabela **relacionamentos** para  INT.
Fecho a tarefa sem pontuar então, uma vez que não houve necessidade de alteração do modelo original.
Aguardo a volta do campo **tipo** para INT.
