### ISSUE TITLE
Criação do diagrama de componentes para a entidade Estado

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#368]

**Comment by iankatalita** [comment]
Ronne, o diagrama de componentes tem divisões de tipo dao, dto e tals ou o meu é de Estado e vai ser de estado geral. Pesquisei sobre o que é diagrama de componentes, não parece ser complicado, só estou em dúvida nessa parte.

**Comment by iankatalita** [comment]
Outra coisinha kkkkk eu vou olhar no DER pra fazer ele?

**Comment by iankatalita** [comment]
Ronne, amigo, no seu livro não tem o que seria um diagrama de componentes, pesquisei na internet e bem, seu como faz, onde faz mas não sei fazer kkkkkk espero ajudinha quarta, obrigada.

**Comment by Ronneesley** [comment]
Exporte para imagem.

**Comment by iankatalita** [comment]
Pronto.

**Comment by Ronneesley** [comment]
Você não exportou para imagem ainda.

**Comment by Ronneesley** [comment]
Achei. A dependência do HTML não está correta.
