### ISSUE TITLE
Criar requisito de inscrição automática nas atividades do evento.

### ISSUE THREAD

**Issue by Salminunes** [Ronneesley/redesocial#369]
Quando o usuário clicar para participar do evento, as inscrição das atividades já será feita automaticamente, marcando todos os checkbox's. Isso para evitar que os alunos se cadastrem no evento mas esqueçam de se cadastrar nas atividades, igual acontece no sigect.
(Requisito elaborado pelo grupo)

**Comment by gusttavogomes** [comment]
Feito

**Comment by Salminunes** [comment]
Ok, pronto.

**Comment by Ronneesley** [comment]
OK
