### ISSUE TITLE
Criar requisito para que resolva o problema de possíveis conflitos de horários na marcação automática do issue 369.

### ISSUE THREAD

**Issue by Salminunes** [Ronneesley/redesocial#370]
Conforme feito o requisito 369, as atividades poderão ter conflito de horários caso existam duas atividades no mesmo horário, pelo fato de que as atividades virão todas marcadas por padrão.
Criar requisito que não permita a ocorrência desse conflito.

**Comment by gusttavogomes** [comment]
Feito.

**Comment by Salminunes** [comment]
Ok!

**Comment by Ronneesley** [comment]
Aguardo correção.

**Comment by Salminunes** [comment]
Conforme debatido em sala com o professor,
juntar as tabelas de requisitos das issues #369 e #370 em uma só, explicando como fazer o cadastro no evento e nas atividades, além do que seria um conflito de horário e como soluciona-lo.

**Comment by gusttavogomes** [comment]
Feito

**Comment by Ronneesley** [comment]
Ok
