### ISSUE TITLE
Corrigir o DER parte de eventos conforme discutido em sala com o professor.

### ISSUE THREAD

**Issue by Salminunes** [Ronneesley/redesocial#382]

**Comment by Salminunes** [comment]
Inserir os campos responsável e organização na tabela. 
Responsável é quem cadastrou o evento.
Organização é quem está organizando o evento. (pode ser uma pessoa/entidade ou várias, então tabela N-N).

**Comment by gusttavogomes** [comment]
Feito

**Comment by Ronneesley** [comment]
Ok (2 estrelas)
