### ISSUE TITLE
Criar protótipo de como o usuário visualizará a página do evento após já ter se cadastrado.

### ISSUE THREAD

**Issue by Salminunes** [Ronneesley/redesocial#383]
Depois que o usuário tiver se cadastrado ele pode querer entrar novamente na página para visualizar a inscrição, alterar algum dado(Como adicionar ou remover atividades) ou cancelar a inscrição.
Importante: Discutir se é interessante colocar vagas disponíveis e acrescentar data limite para alteração de dados na inscrição/edição do evento.

**Comment by gusttavogomes** [comment]
Feito.

**Comment by Ronneesley** [comment]
Ok
