### ISSUE TITLE
Definição e característica do JPA

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#386]
O que é?
O que é necessário para funcionar?
Quais as vantagens e desvantagens?
Existe algo parecido no PHP?
Exemplos e difefenças do JPQL.

3 estrelas em pesquisa (relatório de 4 páginas com exemplos). 
3 estrelas em BD (se os exemplos de JPQL forem completos)

**Opcional**
3 estrelas em programação (se fizer pelo menos um CRUD com uma entidade)

Entrega: **08/11**

**Comment by Ley00** [comment]
Apresentado

**Comment by Ronneesley** [comment]
OK
