### ISSUE TITLE
Estudo da diferença de performance com índices em tabelas

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#388]
Criar uma tabela em um BD qualquer.
Popular esta tabela com muitos dados.

Realizar X **consultas** na tabela e calcular o tempo necessário para estas consultas.

Criar outro BD com a mesma tabela, porém com um índice em um campo (na chave primária e sem ser a chave primária).

Realizar novamente as X  consultas na tabela e calcular o tempo necessário para estas consultas.

Repetir 30 vezes, onde X no mínimo 10^7.

Apresentar os resultados.

5 estrelas em pesquisa (relatório de 5 páginas)
10 estrelas em BD
3 estrelas em programação.

Entrega: **10/11**.

**Comment by gleyson-alves** [comment]
apresentado.

**Comment by Ronneesley** [comment]
Ok
