### ISSUE TITLE
Vantagens e desvantagens do uso de triggers

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#389]
Mencionar sobre a portabilidade de Sistema Gerenciador de Banco de Dados (SGBD) quando as *triggers* são utilizadas.

3 estrelas pesquisa (relatório de 4 páginas).
2 estrelas em BD (+1 estrela se fizer vários exemplos de *triggers*).

**Se as triggers forem codificadas em mais de um SGBD**
       **5 estrelas**

Data: **08/11**

**Comment by dmcardoso** [comment]
ok, queremos apresentar HOJE

**Comment by Ronneesley** [comment]
Ok, muito bom.

**Comment by Ronneesley** [comment]
Exemplo completo considerarei 10 estrelas em BD.
