### ISSUE TITLE
Criar requisito para criar pré-cadastro do responsável pela atividade.

### ISSUE THREAD

**Issue by Salminunes** [Ronneesley/redesocial#390]
Requisito que especifique que quando for vincular um responsável pela atividade (palestrante, professor, etc) se o responsável não for cadastrado na rede social, permitir que o usuário faça um pré-cadastro do responsável, informando por e-mail ao palestrante e convidando-o para participar da rede social e completar seu cadastro.

**Comment by gusttavogomes** [comment]
Feito.

**Comment by Ronneesley** [comment]
Ok
