### ISSUE TITLE
Introdução e características do JSF

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#391]
Apresentar o que é JSF.
Principais *frameworks*.
Principais componentes de um dos frameworks.

5 estrelas em pesquisa (Relatório de 5 páginas)
4 estrelas em *design* (se forem construidas várias páginas de exemplo).

Data: **08/11**

**Comment by Ley00** [comment]
Apresentado

**Comment by Ronneesley** [comment]
OK, somente foi apresentados os conceitos, sem códigos.
Então somente: 5 estrelas em pesquisa (Relatório de 5 páginas)
