### ISSUE TITLE
Criar tabela de instituição

### ISSUE THREAD

**Issue by Salminunes** [Ronneesley/redesocial#392]
Criar tabela que cadastre instituições ex: IFGCeres, SENAC, FACER, UEG, etc.

**Comment by Jonathanss123** [comment]
ok

**Comment by Ronneesley** [comment]
As chaves primárias estão erradas, aguardo a correção.

**Comment by Jonathanss123** [comment]
Corrigido!

**Comment by Ronneesley** [comment]
OK
