### ISSUE TITLE
O que é AJAX? Como se programa?

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#393]
Mostrar o que é AJAX e como fazê-lo **SEM** o uso de *frameworks*.

Envio de dados com método POST e GET.

3 estrelas em *design*
2 estrelas em pesquisa (relatório de 3 páginas)

Se fizer com exemplo ligado a um BD vale 5 estrelas em *design* e 1 estrela em BD.

Entrega: **10/11**

**Comment by PauloHenriqueAraujo** [comment]
Atividade Apresentada!

**Comment by Ronneesley** [comment]
Ok
