### ISSUE TITLE
Como fazer AJAX com jQuery?

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#394]
Mostrar o que é AJAX e como fazê-lo **COM** o uso de **jQuery**.

Envio de dados com método POST e GET.

3 estrelas em *design*
2 estrelas em pesquisa (relatório de 3 páginas)

Se fizer com exemplo ligado a um BD vale 5 estrelas em *design* e 1 estrela em BD.

Entrega: **10/11**

**Comment by gleyson-alves** [comment]
apresentado.

**Comment by Ronneesley** [comment]
A atividade não foi realizada adequadamente, somente:
2 estrelas em pesquisa;
2 estrelas em design positivas e uma negativa.
