### ISSUE TITLE
Ajustar DER conforme discutido em sala com o professor em 27/10.

### ISSUE THREAD

**Issue by Salminunes** [Ronneesley/redesocial#395]

**Comment by Salminunes** [comment]
Adição da tabela organizadores_eventos
Adição da tabela responsaveis_atividades
Inclusão do campo incio_inscricoes e encerramento_inscricao na tabela eventos
reorganizar tabelas do DER.

**Comment by gusttavogomes** [comment]
Feito.

**Comment by Ronneesley** [comment]
Ok (2 estrelas)
