### ISSUE TITLE
Pesquisar sobre dicionário de dados para implementação no projeto.

### ISSUE THREAD

**Issue by Salminunes** [Ronneesley/redesocial#396]
Criar dicionário de dados de **todo o DER** (5 estrelas em Banco de Dados)
Relatório de 4 Paginas (3 Estrelas em pesquisa)

Entrega 10/11

**Comment by Willian-Matts** [comment]
ok! o arquivo sera separado da pesquisa e adicionado a alguma pasta na parte de documentação. OBS: só lembrando de colocar pontuação em documentação também.

**Comment by Salminunes** [comment]
Ok! Parabéns! Aumento de salário pra todo mundo...

**Comment by Ronneesley** [comment]
Ok
