### ISSUE TITLE
Fazer o cadastro de albuns e multimídias funcionarem na página Web, incluíndo o upload de fotos

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#398]
Fazer tudo que for necessário para que o cadastro de fotos funcione, incluindo Servlet, JSPs, BOs e DAOs.

**10 estrelas em design**

Data: **10/11**.

**Comment by DanielIFGoianoSI** [comment]
@Ronneesley, Não tem protótipo de cadastro de álbum. E para "cadastrar" uma multimídia seria dentro do próprio álbum ou em uma postagem, correto?

**Comment by dmcardoso** [comment]
@Ronneesley, o campo *blob* tem algumas limitações

BLOB, TEXT | L + 2 bytes, where L < 2^16  **64^Kb**
MEDIUMBLOB, MEDIUMTEXT | L + 3 bytes, where L < 2^24  **+-14Mb**
LONGBLOB, LONGTEXT | L + 4 bytes, where L < 2^32 **4GB**

Se fosse somente para fotos, acho que o medium blob se encaixaria perfeitamente, porém tem a opção de vídeos, então teremos de usar o Long, certo?
Quanto à visualização no JSP, não estou conseguindo exibir do banco o tipo blob para a interface em JSP... Poderia me dar algumas instruções?

**Comment by dmcardoso** [comment]
@Ronneesley a atividade está concluída, com algumas ressalvas: A **Listagem das fotos** está da maneira que conversamos antes, não consegui passar o blob para a interface e a sessão com o usuário tentei fazer e não consegui, mesmo com os exemplos, tentei depurar pra ver se chegava mas não estava funcionando o break point não sei porque... Estamos passando um usuário fixo toda vez para realizar as operações. **Como bônus fizemos as edições dos álbuns(não estava na atividade), acho que merecíamos umas estrelas a mais**, no mais é isso aguardo resposta

**Comment by Ronneesley** [comment]
Mostre-me em sala

**Comment by dmcardoso** [comment]
@Ronneesley arrumei a sessão com o usuário (porém, quando coloco ele para redirecionar para a outra página quando não recebe o usuário e quando tento depurar ele não chega no lugar e só envia para a outra página, então apaguei e deixei somente pegando o usuário mesmo). Ainda sobre a sessão, estou passando o usuário como **type="hidden"** em todas as páginas e não só na que ele é realmente necessário, gostaria de ver se está correto

**Comment by dmcardoso** [comment]
Concluída

**Comment by Ronneesley** [comment]
Ok
