### ISSUE TITLE
Criar banco de dados inicial

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#4]
Criar o DER e o SQL de criação do banco de dados do sistema.

**Comment by Ronneesley** [comment]
Senhores, lembra que eu mencionei que o layout do DER era importante. 

Mesmo já tendo melhorado muito, lembrei que vocês podem usar um recurso chamado **Layer** lá no MySQL Workbench para melhorar ainda mais o entendimento do DER.

Usem os *layers* para separar as áreas do projeto. Por exemplo: um *layer* chamado localidades para agrupar países, estados e cidades e outro *layer* apara agrupar usuários, *posts* e albuns.

Estes *layers* podem ter cores diferentes para facilitar o entendimento.
Aguardo o *commit* da modificação.

**Comment by dmcardoso** [comment]
Ronne, boa tarde. Já fiz um commit com o layer das localidades, porém não entendemos muito bem sobre o segundo. É pra fazer um layer somente com essas 3 tabelas citadas ou com elas e suas ligações n-n?

Em 29 de julho de 2017 12:31, Ronneesley Moura Teles <notifications@github.com<mailto:notifications@github.com>> escreveu:

Senhores, lembra que eu mencionei que o layout do DER era importante.

Mesmo já tendo melhorado muito, lembrei que vocês podem usar um recurso chamado Layer lá no MySQL Workbench para melhorar ainda mais o entendimento do DER.

Usem os layers para separar as áreas do projeto. Por exemplo: um layer chamado localidades para agrupar países, estados e cidades e outro layer apara agrupar usuários, posts e albuns.

Estes layers podem ter cores diferentes para facilitar o entendimento.
Aguardo o commit da modificação.

**Comment by Ronneesley** [comment]
Vocês podem usar quantos *layers* acharem necessário, tente agrupá-los por áreas específicas.
Sugiro um *layer* para: postagens, comentários, postagens_albuns e postagens_multimidias; e outro *layer* para usuários, álbuns, multimídias.

**Comment by Ronneesley** [comment]
Fiz as modificações para vocês. Tarefa considerada fechada.
