### ISSUE TITLE
Fazer o CRUD de grupos e participantes no DTO, DAO e BO e unidades de testes.

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#402]
Fazer os CRUDs e unidades de testes das entidades: **grupos e participantes**.

**10 estrelas em programação.**

**Data entrega: 10/11**

**Comment by FernandoMacielS** [comment]
O Update esta da forma correta Rone? Ajude um necessitado, o natal esta aí.

@Override
    public void alterar(Grupo g) throws Exception {
        Connection conexao = getConexao();

        if(g.getNome().trim().equals("")){
            throw new Exception("O campo Nome não pode estar vazio!");
        }
        
        if(g.getDataCriacao() == null){
            throw new Exception("O campo Data da Criação não pode estar vazio!");
        }
        
        if(g.getDescricao().trim().equals("")){
            throw new Exception("O campo Descrição não pode estar vazio!");
        }
        
        if(g.getPrivacidade() == null){
            throw new Exception("O campo Privacidade não pode estar vazio!");
        }
        
        if(g.getTipo().trim().equals("")){
            throw new Exception("O campo Tipo não pode estar vazio!");
        }

        PreparedStatement pstmt;
        pstmt = conexao.prepareStatement("update grupos set nome, data_criacao, descricao, privacidade, tipo = ?,?,?,?,? where id = ?");

        pstmt.setString(1, g.getNome());
        pstmt.setDate(2, new java.sql.Date(g.getDataCriacao().getTime()));
        pstmt.setString(3,g.getDescricao());
        pstmt.setInt(4, g.getPrivacidade());
        pstmt.setString(5, g.getTipo());
        
        
        pstmt.setInt(6,g.getId());

        pstmt.executeUpdate();
    }

**Comment by FernandoMacielS** [comment]
Participantes, dê uma olhada pra mim, esta dando problema na iteração entre DAO e BO, não sei mais o que fazer.

**Comment by FernandoMacielS** [comment]
Concluído.

**Comment by Ronneesley** [comment]
OK
