### ISSUE TITLE
Unir os diagramas de classes de Servlet

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#403]
Unir os diagramas de Servlet já feitos e fazer os que não foram feitos em um único arquivo.

**10 estrelas em documentação**

**Data entrega: 10/11**

**Comment by PauloHenriqueAraujo** [comment]
Atividade concluída!
Como a atividade foi trabalhosa de fazer e nenhum dos participantes tem a anotação "(OPT)" em documentação talvez seria interessante reavaliar a quantidade de estrelas oferecida.

**Comment by Ronneesley** [comment]
Ok
