### ISSUE TITLE
Criar SQL de preenchimento inicial do banco de dados para a fase de testes.

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#404]
Preencher todas as tabelas com dados fictícios, tendo pelo menos 5 registros em cada tabela.

Fazer todos os *inserts* necessários e salvar no arquivo **preenchimento.sql**

OBS: Estes dados servirão para os testes do sistema, assim como para visualização das funcionalidades Web.

**10 estrelas em BD.**

**Entrega: 10/11**

**Comment by Lucianodcb** [comment]
Feito

**Comment by EduardoOliveiraSilva** [comment]
me retire daqui e coloque o jonatas! porfavor

**Comment by Ronneesley** [comment]
OK
