### ISSUE TITLE
Pesquisa sobre diferenças de desempenho do uso de BLOBs no banco de dados

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#409]
4 estrelas em pesquisa (se feito uma revisão boa sobre estes aspectos)
---
**se implementar:**
       Criar a mesma tabela em dois bancos separados, uma contendo o BLOB e outra com a URL do arquivo.
       A quantidade de registros deve ser a mesma, de preferência 10^6 de registros.
       Avaliar a diferença de tempo de 1000 consultas.
       Comparar apenas a média, porém anotar o tempo gasto em todas repetições.

**10 estrelas em BD**

**Comment by dmcardoso** [comment]
Apresentado

**Comment by Ronneesley** [comment]
Ok
