### ISSUE TITLE
Corrigir e aumentar o preenchimento do banco de dados no arquivo preenchimento.sql

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#411]
Aumentar para 10 registros para cada tabela.

**Valor: 10 estrelas.**

**Comment by adallberto** [comment]
Não vai precisar mais fazer neh?

**Comment by EduardoOliveiraSilva** [comment]
vai sim! ja comecei

**Comment by WesleyMFelix** [comment]
Me passa o que precisa que eu ajudo!

**Comment by adallberto** [comment]
Ok! Então @EduardoOliveiraSilva

**Comment by adallberto** [comment]
Finalizado!!

**Comment by Ronneesley** [comment]
Mostre-me em sala

**Comment by Ronneesley** [comment]
Ok, pontuação somente para Eduardo e Adallberto.
