### ISSUE TITLE
Criar o banco de dados de anúncios

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#412]
Especificar formas de propaganda dentro da rede social que utilizem as informações planejadas a respeito do usuário.

Pensar em formas diferentes de pagamento, assim como crédito prévio para o anúncio.

O anunciante deve poder escolher a região em que deseja anunciar ou o público que deseja atingir.

Contar a quantidade de visualizações do anuncio ou cliques neles.

Pensar em mais características úteis.

**10 estrelas.**

**Deve ser apresentado para a sala.**
Todos devem apresentar.

**Data: 24/11**

**Comment by adallberto** [comment]
Como foi dito em sala estou em outra atividade! Então fico aguardando a remoção!

**Comment by aandreysr** [comment]
feito

**Comment by Ronneesley** [comment]
OK
