### ISSUE TITLE
Pesquisa: prototype.js

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#416]
Apresentar a biblioteca prototype.js
Disponível em: http://prototypejs.org/

Relatório de 3 páginas.

**Pesquisa: 3 estrelas.**

Se mostrarem códigos feitos por vocês: 
3 estrelas programação.

**Entrega: 29/11**

**Comment by WesleyMFelix** [comment]
Já foi feita essa atividade!

**Comment by WesleyMFelix** [comment]
Apresentada em aula

**Comment by Ronneesley** [comment]
OK
