### ISSUE TITLE
Criação do DAO para a entidade Usuario método excluir

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#43]

**Comment by Ronneesley** [comment]
Anny, o único detalhe na sua implementação é o nome da tabela, veja no DER como ela se chama.
Após a correção me avise.

**Comment by cybersecwoman** [comment]
Finalmente deu certo, desinstalei o programa e instalei novamente. Pode fechar!

**Comment by Ronneesley** [comment]
A indentação da linha 138 não está boa. Mesmo assim encerro a atividade, mas aguardo a correção.

**Comment by cybersecwoman** [comment]
Acho que ficou correto agora.

**Comment by Ronneesley** [comment]
Ficou só evite e linha de excesso 143. Estas linhas podem ser usadas no código, ex.: recomendaria uma entre a 138 e 139 e outra entre 141 e 142, pois facilitam o entendimento.
