### ISSUE TITLE
Criação do DAO para a entidade Usuario método listar

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#44]

**Comment by Ronneesley** [comment]
Adalberto, a indentação da linha 85 está errada. Além disso, no SQL não há filtros com a cláusula *where*, portanto a linha 80 deve ser excluída *pstmt.setInt(1, id);*.
No SQL deve haver uma ordenação dos resultados dos usuários, gostaria que você ordenasse-os pelo nome.
Na linha 88 a classe *ArrayList* deve ser importada do pacote *java.util*.
Aguardo sua correção e me avise quando terminar.

**Comment by Ronneesley** [comment]
Adalberto, ainda vejo no código a cláusula *where id = ?* que não deve estar presente.
Ao corrigir me avise no comentário para checar novamente.

**Comment by adallberto** [comment]
Verifica de novo por gentileza

**Comment by Ronneesley** [comment]
Adalberto o SQL seria:
*select * from multimidias order by data desc*
Veja a linha 90:
*m.setTipoConteudo(rs.getString("TipoConteudo"));*
O valor "TipoConteudo" não confere com o nome da coluna no banco de dados.
Quando alterar me avise.

**Comment by Ronneesley** [comment]
Havia olhado o código errado. Perfeito atividade fechada.
