### ISSUE TITLE
Criação do DAO para a entidade Usuario método alterar

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#45]

**Comment by Ronneesley** [comment]
Oi Lucas, você criou um arquivo chamado *AlterarUsuario.java* na pasta raiz do projeto, sendo que seu código deve ser feito na classe *UsuarioDAO* já existente.
Então aguardo a inserção do código no lugar correto. Após isso delete o arquivo *AlterarUsuario.java*.

**Comment by LuckasAzevedo** [comment]
Olá Rony,  quando fui colocar o codigo do alterar usuario dentro da classe os seguintes atributos deram erro .
pstmt.setString(7, dto.getSexo());
 pstmt.setDate  (8, dto.getData_Cadastro());

pstmt.setInt   (10, dto.getFoto());
pstmt.setInt   (11, dto.getCidade());

 será porque não foram criados métodos get dentro da classe inserir?
e quando você criou a classe usuário não fez a inserção de todos os atributos, posso faze-los?

**Comment by LuckasAzevedo** [comment]
CORRIGINDO**


Olá Rony, quando fui colocar o codigo do alterar usuario dentro da classe os seguintes atributos deram erro .
pstmt.setString(7, u.getSexo());
pstmt.setDate (8, u.getData_Cadastro());

pstmt.setInt (10, u.getFoto());
pstmt.setInt (11, u.getCidade());

será porque não foram criados métodos get dentro da classe inserir?
e quando você criou a classe usuário não fez a inserção de todos os atributos, posso faze-los?

**Comment by LuckasAzevedo** [comment]
Consegui ajeitar 


esta errado ficando desta maneira ?

@Override
    public void alterar (Usuario  u) throws Exception {
        Connection conexao = getConexao();

        PreparedStatement  pstmt; 
        pstmt = conexao.prepareStatement("update usuario set id = ?, nome = ?, email=?, telefone=? senha =?, nascimento =?, sexo = ?, data_cadastro =?, status =?, foto=?, cidade=?");
        
        ResultSet rs;
        rs = pstmt.executeQuery();
       
        MultimidiaDAO multimidiaDAO = new MultimidiaDAO();
        CidadeDAO cidadeDAO = new CidadeDAO();
        
        
        pstmt.setInt(1, u.getId());
        pstmt.setString(2, u.getNome());
        pstmt.setString(3, u.getEmail());
        pstmt.setString(4, u.getTelefone());
        pstmt.setString(5, u.getSenha());  
        pstmt.setDate  (6, u.getNascimento());
        u.setSexo(Sexo.getSexo(rs.getString("sexo").charAt(0)));
        pstmt.setDate  (8, u.getDataCadastro());
        pstmt.setBoolean(9, u.getStatus());
        u.setFoto(multimidiaDAO.alterar(rs.getInt("foto")));
        u.setCidade(cidadeDAO.alterar(rs.getInt("cidade")));

        pstmt.executeUpdate();
      
    
    }

**Comment by Ronneesley** [comment]
Isso, mas eu gostaria que fizesse isso no NetBeans e encaminhasse para o repositório.

**Comment by LuckasAzevedo** [comment]
isso foi feito

**Comment by Ronneesley** [comment]
Então submete ele, não tem nada, se tiver erro eu vou indicar onde.

**Comment by LuckasAzevedo** [comment]
ja submeti ele, foi mais cedo. uma 10:30.

Mas sinceramente não to conseguindo acompanhar o que você ta pedindo, como que você quer, estou  com dificuldades pra entender o que esta sendo pedido,  com toda certeza acho que alguns alunos não ta no mesmo ritmo que você esta levando.

**Comment by Ronneesley** [comment]
Oi Lucas, o interessante deste método é que o ritmo quem estabelece é o próprio participante. Favor não deletar os comentários, porque fica parecendo que é uma nova *issue*.
Bem, vamos ao código. No update não se altera o campo *id* no SQL está assim *set id = ?*
Você deve utilizar o *id* como cláusula de alteração.

Evite linhas em excesso como as linhas 77 a 79 e 94 e 95. Duas linhas seguidas em branco ou mais devem sempre ser questionadas.

Como o *id* só entra no *where* o comando da linha 80 deveria ser o último interrogação.
No SQL você esqueceu a vírgula entre colunas, veja: *telefone=? senha =?*

A conversão entre tipos da linha 85 é feita assim *pstmt.setDate(6, new java.sql.Date(u.getNascimento().getTime()));* é um caso especial então fiz para você. Isso converte um objeto da classe de *java.util.Date* para *java.sql.Date*.

Na linha 86, o código *pstmt.setString(10, String.valueOf(u.getSexo().getId()));* converte o sexo para um literal do tipo *String*.

Deixei a linha 87 para você fazer seguindo o comentário da linha 85.

No demais está muito bom. Aguardo só estas correções para encerrar a atividade.

**Comment by LuckasAzevedo** [comment]
Ok

**Comment by Ronneesley** [comment]
Oi Lucas, trabalhoso esse hein? Isto acontece porque tem muitos atributos.
Apenas dois últimos detalhes no SQL: a tabela não se chama *usuario*, veja no DER o nome correto; e antes do *where* você fez assim: *cidade=?, where* neste caso a vírgula após o interrogação indica que haveria um outro parâmetro e não tem.
Vou aguardar que envie estas correções, mas já considero a atividade completada. Parabéns.
