### ISSUE TITLE
Criação da classe DAO para Album método listar

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#46]

**Comment by Ronneesley** [comment]
Andrey, corrija a indetanção. Seu código está um espaço a frente do normal.
O comando de seleção deve ser mudado, a tabela não é mais *posts*.
Coloquei o exemplo de chave estrangeira.

**Comment by aandreysr** [comment]
Eu corrigi a tabela, quanto a ordenação, ela muda ou pode deixar pelo id
 desc?

Em 5 de ago de 2017 20:16, "Ronneesley Moura Teles" <
notifications@github.com> escreveu:

**Comment by Ronneesley** [comment]
Não vi a modificação, deve ser porque não enviou (commit e push). 
O *Album* deve ser ordenado descrescente pela **data** de criação.

**Comment by Ronneesley** [comment]
Andrey, está quase perfeito agora. Note que no seu SQL você colocou *order by date desc* enquanto que o campo chama-se **data** e não *date*, veja o DER para confirmar.
Mesmo assim considero a atividade terminada, mas aguardo sua correção.

**Comment by aandreysr** [comment]
corrigido
