### ISSUE TITLE
Criação da classe DAO para Album método alterar

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#49]

**Comment by Ronneesley** [comment]
Gleyson, está muito bom. Somente me avise aqui nesta **issue** para olhar quando terminar.
O único detalhe é que em seu SQL você colocou uma vírgula sobressalente em:
*usuario=?, where*

Aguardo a correção para fechar e pontuar a tarefa.

**Comment by gleyson-alves** [comment]
Boa tarde, ate que horas posso enviar

Enviado pelo meu Windows Phone
________________________________
De: Ronneesley Moura Teles<mailto:notifications@github.com>
Enviada em: ‎11/‎08/‎2017 11:49
Para: Ronneesley/redesocial<mailto:redesocial@noreply.github.com>
Cc: gleyson-alves<mailto:gleyson.alves@outlook.com>; Assign<mailto:assign@noreply.github.com>
Assunto: Re: [Ronneesley/redesocial] Criação da classe DAO para Album método alterar (#49)


Gleyson, está muito bom. Somente me avise aqui nesta issue para olhar quando terminar.
O único detalhe é que em seu SQL você colocou uma vírgula sobressalente em:
usuario=?, where

Aguardo a correção para fechar e pontuar a tarefa.

**Comment by Ronneesley** [comment]
Antes das 19h

**Comment by gleyson-alves** [comment]
Não teria como enviar no início da aula, to sem pc

Enviado pelo meu Windows Phone
________________________________
De: Ronneesley Moura Teles<mailto:notifications@github.com>
Enviada em: ‎11/‎08/‎2017 14:27
Para: Ronneesley/redesocial<mailto:redesocial@noreply.github.com>
Cc: gleyson-alves<mailto:gleyson.alves@outlook.com>; Assign<mailto:assign@noreply.github.com>
Assunto: Re: [Ronneesley/redesocial] Criação da classe DAO para Album método alterar (#49)


Antes das 19h

**Comment by Ronneesley** [comment]
Talvez nos primeiros 10 min de aula, mas isso não garante que estará correta a entrega, então sugiro enviar logo.

**Comment by Ronneesley** [comment]
Perfeito
