### ISSUE TITLE
Criação do DAO para a classe Comentario método listar

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#53]

**Comment by Ronneesley** [comment]
Igor, a indentação da declaração da função listar não está boa.
Além disso, não utilize o método *conectar();* e sim o comando *Connection conexao = getConexao();* assim como na classe *UsuarioDAO*. Para isso na declaração da classe *ComentarioDAO* coloque o comando * extends DAOBase * assim com havia comentado em aula.

Aguardo as correções para fechar a tarefa.

**Comment by IgorJustinoRodrigues** [comment]
Acabei de fazer as alterações.

**Comment by Ronneesley** [comment]
A indentação ainda não está boa. Aguardo a alteração.

**Comment by IgorJustinoRodrigues** [comment]
Acho que agora esta tudo ok rsrsrsrs

**Comment by Ronneesley** [comment]
Arrumei a ordenação do select pela data. Coloquei um condicional na obtenção da resposta, porque ela é opcional e dei um exemplo de como seria a obtenção da postagem. Este código está comentado porque não terminaram o *PostagemDAO* ainda.

Considero a tarefa terminada, já marquei sua pontuação.
