### ISSUE TITLE
Criação do DAO para a classe Multimidia método alterar

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#54]

**Comment by Ronneesley** [comment]
(Novo atraso consecutivo)

**Comment by JoseGilvan** [comment]
Já fiz, ver pra mim depois se esta tudo ok...

**Comment by Ronneesley** [comment]
José, o nome da tabela não é *Multimidia* veja no DER o nome correto. Nos códigos *midia =?* separe o interrogação com um espaço. Faltou um interrogação no trecho *data where *.
Aguardo as correções.

**Comment by JoseGilvan** [comment]
CORRIGIDO

**Comment by Ronneesley** [comment]
Aguardando correção

**Comment by JoseGilvan** [comment]
pronto

**Comment by JoseGilvan** [comment]
pronto

**Comment by Ronneesley** [comment]
Tem uma vírgula sobressalente no SQL:
album = ?, where id = ?

Vou fechar mas aguardo a correção.
