### ISSUE TITLE
Criação do DAO para a classe Multimidia método listar

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#57]

**Comment by Ronneesley** [comment]
Luciano, em seu código o nome da tabela está errado, a ordenação de multimídia seria mais interessante por data do que por id. E na hora de obter o tipo de conteúdo em *rs.getString("TipoConteudo")*, o nome da coluna também está errado.
Então, por favor olhe o DER e faça as devidas correções.

**Comment by Lucianodcb** [comment]
Fiz as duas ultimas alterações, mas o nome da tabela não consegui identificar o erro. ?

**Comment by Ronneesley** [comment]
Olhe no DER, na tabela *multimidias*, lá não existe uma coluna chamada *tipoConteudo*, assim como informado no comando:
m.setTipoConteudo(rs.getString(**"tipoConteudo"**));
Corrija o nome e fecho a tarefa.

**Comment by Lucianodcb** [comment]
terminei

**Comment by Ronneesley** [comment]
Corrigir o nome da coluna *tipoConteudo*

**Comment by Lucianodcb** [comment]
agora sim

**Comment by Ronneesley** [comment]
Agora está perfeito.
