### ISSUE TITLE
Criação do DAO para a classe Países método inserir

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#58]

**Comment by Ronneesley** [comment]
Maciele, quando terminar avise aqui.
Note apenas que a classe *PaisDAO* já possui um método *public void inserir(Pais dto) throws Exception* nas linhas 48 a 51.
Então se você criou outro nas linhas 12 a 19, deve apagar o antigo. Cuidado apague somente o outro *inserir()*.

**Comment by maciele** [comment]
terminei

**Comment by Ronneesley** [comment]
Maciele, veja que Java é *sensitive-case*, então letras maiúsculas são diferentes de minúsculas.
Nas linhas 20 e 23 ocorrem detalhes apenas relacionados a este fato.
Veja o método *inserir()* de *UsuarioDAO* para ter uma ideia do que é maiúsculo.
Aguardo a correção para fechar a tarefa.

**Comment by Ronneesley** [comment]
Sua atividade não está entregue. Quando terminar me avise que avalio e fecho a tarefa.

**Comment by maciele** [comment]
eu não estou conseguindo edita. já vir os erros: 
PreparedStatement pstmt; e getNome

**Comment by maciele** [comment]
pronto

**Comment by Ronneesley** [comment]
Perfeito
