### ISSUE TITLE
Criação do DAO para a classe Países método alterar

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#59]

**Comment by Ronneesley** [comment]
Macilon, remova o método *conectar()* do seu código,, no lugar disso você vai acrescentar na declaração da classe o comando *extends DAOBase*, assim como em *UsuarioDAO*.
Ao fazer isto, você poderá utilizar o comando **Connection conexao = getConexao();** para obter a conexão na linha 20 do seu código.

Evite no código quebrar duas linhas seguidas, uma só é suficiente.
Após isto considerarei a tarefa encerrada.

**Comment by Ronneesley** [comment]
Não havia reparado. Seu parâmetro do método está errado. Onde está *public void alterar(PaisDAO p) throws Exception* deveria ser **public void alterar(Pais p) throws Exception** (sem o DAO em Pais).

Isso fez você criar os métodos  *getNome()* e *getId()* que devem ser removidos. O atributo *con* também depois da alteração anterior.

**Comment by Macilon** [comment]
Rone, lá havia um "if" com outro getNome. Fiz a remoção dele também, ou deveria deixar?
E sobre os "pstmt" está correto?

**Comment by Macilon** [comment]
Sobre o comando extends DAOBase, se não me engano já está criado lá no início da classe. Se for isso mesmo o seu pedido. Se não for me corrige novamente. Aguardo!

**Comment by Ronneesley** [comment]
Agora está perfeito, parabéns. Considero a atividade encerrada.
