### ISSUE TITLE
Criação dos protótipos da timeline e dos posts (textos, vídeos, fotos e galerias)

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#6]
Criação dos protótipos no Pencil da timeline e dos posts incluindo os diversos formatos (textos, vídeos, fotos e galerias).

**Comment by Ronneesley** [comment]
Lara, agora que os rascunhos estão prontos, gostaria que passasse-os para o Pencil para padronizar o *layout* dos protótipos.
Preencha os protótipos com dados fictícios no lugar de colocar (NOME) etc.

Pensando aqui, a opção de dar *like* creio que é patente de alguém, informe-se em: https://olhardigital.com.br/noticia/timeline-e-botao-like-geram-processo-por-patente-contra-o-facebook/32543.

Então pense em outra coisa para representar a afirmação positiva daquele *post*.

Gostaria que escolhessem já as imagens e ícones que vão utilizar para os protótipos.
Aguardo a versão final.

**Comment by Ronneesley** [comment]
Vi os protótipos estão ótimo, porém aguardo a reavaliação do conceito do *like* devido ao problema do comentário anterior.
Assim que pensarem em algo para substituí-lo e mudarem os protótipos fecho a atividade.

**Comment by Ronneesley** [comment]
Reforçando o prazo final para entrega data tarefa é amanhã, conforme combinamos na última aula.

**Comment by aandreysr** [comment]
Professor,
Quanto ao nome do botão "like" seria mais fácil caso ja tenhamos o nome da
rede social definido, a micrsoft criou uma rede social que o logo forma um
rosto sorrindo, e o "like" deles se chama "smile", mas se não for possível
definir um nome  agora estamos pensando em utiilizar "Top" ou "Up"

2017-08-08 11:36 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Gostei do "Top" ou "Up". Desde que seja algo que manifeste a afirmação positiva ou negativa do que foi publicado está bom por enquanto. O que não podemos é utilizar o mesmo termo .

**Comment by aandreysr** [comment]
Já fiz a alteração do botão de reação no prototipo da time line, ficou
definido como UP para positvo e DOWN para negativa

Em 8 de agosto de 2017 12:15, Ronneesley Moura Teles <
notifications@github.com> escreveu:

**Comment by Ronneesley** [comment]
Ok, só não vi o ícone do DOWN. Mesmo assim, já vou fechar a tarefa.
Gostaria que quem fez o protótipo chamado "tela de postagem.png" ajustasse o layout para ficar do tamanho apenas da tela que foi desenhada.
Ao clicar com o botão oposto no palco do Pencil existe uma opção "Fit..." que faz este ajuste.
Parabéns para a equipe. Pontuação marcada.

**Comment by laracaroline** [comment]
Okay! Não me lembro se fui eu ou quem fez, mas verificarmos isso e a questão do botão down.
Obrigada!



Enviado do meu smartphone Samsung Galaxy.


-------- Mensagem original --------
De: Ronneesley Moura Teles <notifications@github.com>
Data: 08/08/17 13:32 (GMT-03:00)
Para: Ronneesley/redesocial <redesocial@noreply.github.com>
Cc: Lara Caroline <laracaroline2007@hotmail.com>, Assign <assign@noreply.github.com>
Assunto: Re: [Ronneesley/redesocial] Criação dos protótipos da timeline e dos posts (textos, vídeos, fotos e galerias) (#6)


Ok, só não vi o ícone do DOWN. Mesmo assim, já vou fechar a tarefa.
Gostaria que quem fez o protótipo chamado "tela de postagem.png" ajustasse o layout para ficar do tamanho apenas da tela que foi desenhada.
Ao clicar com o botão oposto no palco do Pencil existe uma opção "Fit..." que faz este ajuste.
Parabéns para a equipe. Pontuação marcada.
