### ISSUE TITLE
Criação do DAO para a classe Países método listar

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#62]

**Comment by Ronneesley** [comment]
Thalia, está quase perfeito. Apenas a ordenação dos países pelo *id* que não é o adequado.
O interessante é ordená-los pelo nome.
Aguardo a submissão da correção para encerrar a tarefa.

**Comment by thaliasantana** [comment]
Ronne, eu subi antes, pra não perder o arquivo, mas tinha pensado nisso mesmo. Porém eu tava com medo de estar errado, ai perguntei o Andrey e pesquisei no meu caderno de BD e vi que podia mesmo! Uhuu!

Hey, eu preciso fazer um main aqui também? É uma grande dúvida!

**Comment by Ronneesley** [comment]
Não o *main()* era só um exemplo para você ver que estava funcionando.
Considero a atividade completa.
