### ISSUE TITLE
Criação do DAO para a classe Estados método alterar

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#64]

**Comment by WesleyMFelix** [comment]
Bom dia! 
Creio que consegui enviar minha atividade, se puder da uma olhada e me dar um retorno agradeço!

**Comment by Ronneesley** [comment]
Wesley, você tem que enviar para o servidor. Caso não lembre como fazer as instruções estão no link: https://ronneesley.github.io/redesocial/#como_enviar_o_que_fiz

**Comment by WesleyMFelix** [comment]
Eu fiz o commit direto do NetBeans pensando que após isso teria que
fazermos também no Github!

Em 7 de ago de 2017 10:40 AM, "Ronneesley Moura Teles" <
notifications@github.com> escreveu:

**Comment by Ronneesley** [comment]
Wesley, remova o método *getConexao()*, no lugar disso você vai acrescentar na declaração da classe o comando *extends DAOBase*, assim como em *UsuarioDAO*.
Ao fazer isto, você poderá utilizar o comando *Connection conexao = getConexao();* para obter a conexão na linha 31 do seu código.

Além disso, no SQL a ordem dos estados tem que ser feita pelo **nome** e não pelo *id*. Em ordem crescente.

A indentação está boa. Após as alterações fecho a tarefa.

**Comment by WesleyMFelix** [comment]
Ok! A tarde organizo tudo.

Em 7 de ago de 2017 11:02 AM, "Ronneesley Moura Teles" <
notifications@github.com> escreveu:

**Comment by Ronneesley** [comment]
Oi Wesley, está quase ficando bom, veja alguns detalhes:
1) O parâmetro do método *public void alterar(EstadoDAO p)* não é *EstadoDAO* e sim **Estado**
2) Isto fez você criar três métodos na classe *EstadoDAO* equivocadamente, são eles: *getNome()*, *getPais()* e *getId()*. Eles devem ser excluídos;
3) No último comando onde usou *pstmt.execute();* o melhor é utilizar *pstmt.executeUpdate();*
4) As linhas 26 e 27 estão em branco, sendo excessivas, exclua elas.
5) O comando SQL (linha 19) está alterando o *id*, enquanto que este deveria ser uma cláusula condicional **where**, além disso não se aplica *order by* neste tipo de *DML*

Aguardo o próximo *commit* com as correções.

**Comment by WesleyMFelix** [comment]
Enviei a correção!

Em 7 de ago de 2017 6:49 PM, "Ronneesley Moura Teles" <
notifications@github.com> escreveu:

**Comment by Ronneesley** [comment]
Muito bem Wesley, terminei a linha 23 para ti. Era assim: *pstmt.setInt(2, p.getPais().getId());*
Considero a tarefa terminada, já encaminho outra para continuar trabalhando.
