### ISSUE TITLE
Criação do DAO para a classe Estados método listar

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#67]

**Comment by Ronneesley** [comment]
Igor, caso queira continuar pontuando, já distribui uma nova tarefa.

**Comment by IgorJustinoRodrigues** [comment]
Quero sim, qual?


2017-08-07 10:32 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Veja o título da **issue**: Criação do DAO para a classe Estados método listar

**Comment by IgorJustinoRodrigues** [comment]
Ok

**Comment by Ronneesley** [comment]
Igor, está ficando muito bom.
Tanto em  *ComentarioDAO* quanto em *EstadoDAO*, remova o método *getConexao()*.
Em *EstadoDAO* acrescente o comando de herança **extends DAOBase** na declaração da classe.
A ordenação de estados não é pelo *id* e sim pelo *nome*.

Após isto, considerarei a tarefa completa. Parabéns pelo empenho.

**Comment by Ronneesley** [comment]
Perfeito, parabéns!
