### ISSUE TITLE
Criação do DAO para a entidade Postagem método excluir

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#68]

**Comment by Ronneesley** [comment]
Então, mais uma tarefa, já marquei sua pontuação anterior.

**Comment by IgorJustinoRodrigues** [comment]
Já mandei essa também, se tiver mais pode me mandar ok


2017-08-07 11:43 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Não encontrei o arquivo *PostagemDAO* você deve ter esquecido de fazer o *commit*, dê uma olhada ai.
Assim que fizer me avisa que dou uma olhada.

**Comment by IgorJustinoRodrigues** [comment]
Bom dia, acabei de mandar.

Em 7 de agosto de 2017 18:43, Ronneesley Moura Teles <
notifications@github.com> escreveu:

**Comment by Ronneesley** [comment]
Perfeito ficou muito bom.
