### ISSUE TITLE
Incremento dos requisitos de grupos/comunidades no DER

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#69]
Modelar o RF 07, 08, 09, 10, 11 e 14 de acordo com o documento de especificação de requisitos.

**Comment by Ronneesley** [comment]
Salmi, distribui esta tarefa de BD para ti, já que tinha me solicitado a edição.
Veja a descrição da atividade no primeiro comentário da **issue**.

**Comment by Ronneesley** [comment]
Salmi, as colunas: *privacidade* e *tipo_do_grupo* na tabela *grupos* são do tipo **int**
A coluna *tipo_do_grupo* deve se chamar apenas *tipo*, uma vez que o resto está implícito.

Não esqueça de fazer aquelas alterações que comentamos:
1) *postagem_multimidias* (nome da tabela errado)

Quais os possíveis valores para *cargo* e *tipo_do_grupo*?

**Comment by Salminunes** [comment]
Correções feitas. Cargo seria usuário, administrador, dono e etc. Tipo é a finalidade do grupo, se é grupo para vendas igual o "barganhas ceres", se é grupo especifico para apresentação de conteúdos e etc como o grupo de Sistemas de Informação, se é grupo de entretenimento, e etc. Dependendo do tipo do grupo ele apresenta algumas opções diferentes, como o grupo de vendas, ele apresenta no momento da postagem a opção "vender um item", além da "iniciar discussão".

**Comment by Ronneesley** [comment]
Então cargos deveria ser *int*.
As chaves estrangeiras chame apenas de: **grupo** e **usuario**, na tabela *usuarios_grupos*
Aliás, chame esta tabela de **participantes**, veja que como ela tem uma relação *n-para-m* não existe a chave primária **id**.
O campo data de criação do grupo acrescente o tempo no tipo da coluna: *DATETIME*
Aguardo as correções.

**Comment by Salminunes** [comment]
Corrigido.

**Comment by Ronneesley** [comment]
Na descrição do grupo use tipo TEXT.
Mova as tabelas para que as linhas dos relacionamentos fiquem retas (sem curvas).
Mesmo assim encerro a atividade, mas aguardo as correções.
