### ISSUE TITLE
Criar protótipos de cadastro de usuários, login e perfil

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#7]
Criação dos protótipos de cadastros de usuários, login e perfil.

**Comment by Ronneesley** [comment]
Ianka, os protótipos feitos no Corel Draw não deixaram claro quais são os campos e quais são caixas. É necessário um esforço muito grande para entender. 
O arquivo chamado **novo.png** não ajuda a entender de que ele se trata, porque nem o nome do arquivo é representativo e nem a imagem contém textos.
Então preencha com dados fictícios os protótipos e sugiro fielmente que use o Pencil para os protótipos até mesmo para padronização.

**Comment by iankatalita** [comment]
Okay, vou refazer os protótipos e enviar.

**Comment by Ronneesley** [comment]
Senhores o andamento desta tarefa está muito lento, lembrando que o prazo para entrega é até amanhã.
Meu objetivo não é vários protótipos da mesma coisa, vocês até podem fazer separadamente.
Mas eu quero o veredito final da equipe, quanto ao que foi julgado melhor.

Novamente, reforçando o comentário anterior, deve ser feito na ferramenta Pencil para que todos possam alterar sem ter que instalar *software* pirata e até mesmo para trabalharmos nos laboratórios.

**Comment by jrossini94** [comment]
Feito

**Comment by Ronneesley** [comment]
Aguardo renomear o arquivo **untitled_page.png** para algo que o descreva de fato, mude isso no Pencil também.
Mesmo assim encerro a tarefa.
