### ISSUE TITLE
Criação do DAO para a entidade Postagem método alterar

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#70]

**Comment by Ronneesley** [comment]
Mais uma **issue**, está indo muito bem.

**Comment by IgorJustinoRodrigues** [comment]
Te mandei o alterar, mas não sei como fazer no caso do usuário, em que
tenho apenas o id dele na postagem...
devo alterar apenas esse id, ou tenho que alterar todas as informações
desse usuário também?
ou o id, não pode mudar? rsrsrss

**Comment by Ronneesley** [comment]
Está muito bom, era quase isso mesmo.
Havia um problema em quem codificou Postagem para o campo data, já arrumei, a classe que ele usou deveria ser *java.util.Date* o que afetou a linha 40 para *pstmt.setDate(3, new java.sql.Date(p.getData().getTime()));*.
Já a chave estrangeira é apenas *pstmt.setInt(4, p.getUsuario().getId());*
Já está no código, e mais uma tarefa completa.
