### ISSUE TITLE
Criação do DAO para a entidade Postagem método selecionar

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#72]

**Comment by Ronneesley** [comment]
Mais um então.

**Comment by IgorJustinoRodrigues** [comment]
Pronto, apenas com um erro no getUsuario.
Ainda não conseguir entender muito bem a parte do usuário, que tenho que
chamar um método dentro de outro.

2017-08-08 12:36 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Fiz o exemplo da chave estrangeira para ti, parabéns pelo empenho, está tudo correto.
