### ISSUE TITLE
Criação da classe PaisBO

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#73]
Criação da classe *PaisBO* seguindo os moldes da classe *UsuarioBO*.

Definir a herança *extends BOCRUDBase<Usuario, UsuarioDAO>* de forma adequada para o caso.

Implementar os métodos *instanciarDAO()* e *validar()*

**Comment by Ronneesley** [comment]
Igor, agora uma tarefa um pouco mais avançada, creio que já consegue desenvolver bem as classes DAO.
Agora trata-se de codificar a classe *PaisBO* conforme o enunciado na descrição da atividade.
Esta classe deve ser criada no pacote **br.com.redesocial.modelo.bo**.
Bom trabalho.

**Comment by IgorJustinoRodrigues** [comment]
Certo, tem algum modelo do que é para fazer? rsrsrs


Em 8 de agosto de 2017 13:39, Ronneesley Moura Teles <
notifications@github.com> escreveu:

**Comment by Ronneesley** [comment]
Sim, a classe *UsuarioBO*, veja a descrição dos passos no primeiro comentário da **issue**.

**Comment by IgorJustinoRodrigues** [comment]
Acabei de te mandar o arquivo, não tenho certeza se é isso mesmo rsrsrsrs,
oque for preciso alterar me fala


2017-08-08 15:01 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Era isso mesmo. Parabéns.

**Comment by IgorJustinoRodrigues** [comment]
Ok, se precisar de mais algum estou aqui

2017-08-09 11:24 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Ok, já vou definir uma nova atividade.
