### ISSUE TITLE
Criação do DAO para entidade Cidade método inserir

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#74]

**Comment by Ronneesley** [comment]
Salmi, caso queira continuar pontuando, segue mais uma atividade para fazer.

**Comment by Salminunes** [comment]
Meu CidadeDAO está com erro no getEstado. De resto está pronto. Pode me auxiliar? Imagino que tenha relação com o fato do estado estar sendo puxado da outra classe estado.

**Comment by Ronneesley** [comment]
Perfeito já dei uma olhada.
