### ISSUE TITLE
Criar o HTML da galeria de imagens

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#77]

**Comment by Ronneesley** [comment]
Siga o padrão do arquivo "GaleriaFotos.png" no diretório de protótipos.
Ao terminar o HTML salve no projeto **RedeSocialWeb** na pasta **Páginas Web**

**Comment by IgorJustinoRodrigues** [comment]
Tenho que fazer toda a tela? ou apenas a parte da galeria?

[image: GaleriaFotos.png]


2017-08-09 11:57 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Apenas a parte da galeria

**Comment by IgorJustinoRodrigues** [comment]
Acabei de mandar o arquivo, usei apenas html e css rsrsrsrs então não ficou
lá essas coisas...

2017-08-09 12:13 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>
:

**Comment by Ronneesley** [comment]
Ficou muito bom.
