### ISSUE TITLE
Criação do DAO para entidade Cidade método listar

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#79]

**Comment by Ronneesley** [comment]
Marcos mais uma atividade caso queira continuar pontuando.

**Comment by MarcosArriel** [comment]
Professor te enviei essa criação na quarta dia 06/09. Desculpe a demora.

**Comment by Ronneesley** [comment]
Marcos a linha 102: *EstadoDAO estadoDAO = new EstadoDAO();* é desnecessária.
Falta preencher o estado veja o código do método *selecionar()*.

**Comment by MarcosArriel** [comment]
Retirei o EstadoDAO estadoDAO = new EstadoDAO().
E foi feito o preenchimento do estado como o Sr° me falou.

**Comment by Ronneesley** [comment]
Ok.
