### ISSUE TITLE
Criação do DTO da classe PostagemAlbum

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#81]
Seguir o mesmo padrão das outras classes DTOs como: Pais, Estado, Cidade, Postagem, Usuario, etc.
A diferença é que esta classe tem apenas atributos que referem-se a chaves estrangeiras, veja no DER.

**Comment by Ronneesley** [comment]
Andrey, mais uma atividade caso queira continuar pontuando.

**Comment by aandreysr** [comment]
criei o arquivo, porém nao tenho certeza se esta totalmente correto

**Comment by Ronneesley** [comment]
Está correto. Só um detalhe, na parte de documentação você está me falando que quem fez foi:
*@author Daniel e Macilon*
Devo dar crédito a eles? rsrs

**Comment by aandreysr** [comment]
confesso que teve um copiar e colar, mas foi apenas no cabeçalho!

**Comment by Ronneesley** [comment]
Tranquilo... rsrs
