### ISSUE TITLE
Criação do DAO para entidade PostagemMultimidia método inserir()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#83]
Criação da classe PostagemMultimidiaDAO.
Esta atividade é dependente da atividade #80 então converse com o responsável para saber o andamento.

**Comment by Ronneesley** [comment]
Daniel, segue mais uma atividade caso queira continuar pontuando.
Sua atividade depende da atividade #80 que está com o @Macilon trabalhe em equipe com ele para terminar a sua atividade.

**Comment by dmcardoso** [comment]
Entrei em contato com o Macilon, a classe DTO PostagemMultimidia não terá um construtor, correto?

2017-08-09 12:50 GMT-03:00 Ronneesley Moura Teles <notifications@github.com<mailto:notifications@github.com>>:

Daniel, segue mais uma atividade caso queira continuar pontuando.
Sua atividade depende da atividade #80<https://github.com/Ronneesley/redesocial/issues/80> que está com o @Macilon<https://github.com/macilon> trabalhe em equipe com ele para terminar a sua atividade.

**Comment by dmcardoso** [comment]
Fiquei na dúvida...

Em 9 de agosto de 2017 14:47, Daniel Moreira <qualquercoisa6568@hotmail.com<mailto:qualquercoisa6568@hotmail.com>> escreveu:
Entrei em contato com o Macilon, a classe DTO PostagemMultimidia não terá um construtor, correto?

2017-08-09 12:50 GMT-03:00 Ronneesley Moura Teles <notifications@github.com<mailto:notifications@github.com>>:

Daniel, segue mais uma atividade caso queira continuar pontuando.
Sua atividade depende da atividade #80<https://github.com/Ronneesley/redesocial/issues/80> que está com o @Macilon<https://github.com/macilon> trabalhe em equipe com ele para terminar a sua atividade.

**Comment by Ronneesley** [comment]
Tem sim. De certa forma, não existe classe sem construtor a não ser que estejam usando *Singleton*, que creio não ser o caso.
O que acontece lá é que todos os atributos tem seus tipos de dados vinculados a classes que já criamos.
Ao contrário das outras que possuem tipos "primitivos" como: Integer, String, Double, Float. Lá os dois tipos são: *Multimidia* e *Postagem*

**Comment by dmcardoso** [comment]
Fiz uma correção *

Em 9 de agosto de 2017 15:22, Daniel Moreira <qualquercoisa6568@hotmail.com<mailto:qualquercoisa6568@hotmail.com>> escreveu:
Já fiz o commit, se puder conferir, ver se está certo...

Em 9 de agosto de 2017 14:58, Daniel Moreira <qualquercoisa6568@hotmail.com<mailto:qualquercoisa6568@hotmail.com>> escreveu:
Ok, corrigido. Obrigado.

Em 9 de agosto de 2017 14:52, Ronneesley Moura Teles <notifications@github.com<mailto:notifications@github.com>> escreveu:

Tem sim. De certa forma, não existe classe sem construtor a não ser que estejam usando Singleton, que creio não ser o caso.
O que acontece lá é que todos os atributos tem seus tipos de dados vinculados a classes que já criamos.
Ao contrário das outras que possuem tipos "primitivos" como: Integer, String, Double, Float. Lá os dois tipos são: Multimidia e Postagem

**Comment by dmcardoso** [comment]
Já fiz o commit, se puder conferir, ver se está certo...

Em 9 de agosto de 2017 14:58, Daniel Moreira <qualquercoisa6568@hotmail.com<mailto:qualquercoisa6568@hotmail.com>> escreveu:
Ok, corrigido. Obrigado.

Em 9 de agosto de 2017 14:52, Ronneesley Moura Teles <notifications@github.com<mailto:notifications@github.com>> escreveu:

Tem sim. De certa forma, não existe classe sem construtor a não ser que estejam usando Singleton, que creio não ser o caso.
O que acontece lá é que todos os atributos tem seus tipos de dados vinculados a classes que já criamos.
Ao contrário das outras que possuem tipos "primitivos" como: Integer, String, Double, Float. Lá os dois tipos são: Multimidia e Postagem

**Comment by Ronneesley** [comment]
Daniel está quase correto. Note que o método já existe *public void inserir(PostagemMultimidia dto) throws Exception {* na linha 34. Então deve ser feito lá dentro o código.
O seu código está correto o único detalhe é que os dados vêem da variável *PostagemMultimidia dto*

**Comment by dmcardoso** [comment]
Ok, corrigido. Obrigado.

Em 9 de agosto de 2017 14:52, Ronneesley Moura Teles <notifications@github.com<mailto:notifications@github.com>> escreveu:

Tem sim. De certa forma, não existe classe sem construtor a não ser que estejam usando Singleton, que creio não ser o caso.
O que acontece lá é que todos os atributos tem seus tipos de dados vinculados a classes que já criamos.
Ao contrário das outras que possuem tipos "primitivos" como: Integer, String, Double, Float. Lá os dois tipos são: Multimidia e Postagem

**Comment by Ronneesley** [comment]
Somente a validação que possuía um detalhe no código, deveria ser assim:
*if(dto.getPostagem() == null || dto.getMultimidia() == null){*
Mesmo assim já fiz a alteração e considero a tarefa encerrada.
