### ISSUE TITLE
Criação do diagrama de casos de uso

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#84]

**Comment by Ronneesley** [comment]
Willian, você tinha comentado que ficou sem atividade porque não foi à última aula.
Então segue uma atividade de documentação que é um conteúdo já visto no semestre passado.
Criei uma pasta no sistema chamada **projeto**, nela existe um arquivo **uml.asta** que você deve terminar o diagrama.

**Comment by Willian-Matts** [comment]
Terminei!

**Comment by Ronneesley** [comment]
Perfeito.
