### ISSUE TITLE
Criação do DAO para entidade PostagemMultimidia método alterar()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#85]

**Comment by Ronneesley** [comment]
Mais uma atividade caso queira continuar pontuando.

**Comment by PauloHenriqueAraujo** [comment]
Vou fazer sim,

apenas comecei lá, já tá na na hora de começar a ajeitar pra ir pro IF

em breve termino.


________________________________
De: Ronneesley Moura Teles <notifications@github.com>
Enviado: quarta-feira, 9 de agosto de 2017 14:23
Para: Ronneesley/redesocial
Cc: Paulo Henrique; Assign
Assunto: Re: [Ronneesley/redesocial] Criação do DAO para entidade PostagemMultimidia método alterar() (#85)


Mais uma atividade caso queira continuar pontuando.

**Comment by Ronneesley** [comment]
Paulo, fiz a alteração no protótipo que mencionei que seria necessária.
*PostagemMultimidia dto, PostagemMultimidia dtoNovo*
Agora são dois parâmetros.
Tente montar a condição de alteração correta e nas linhas 39 e 40 use os dados do *dtoNovo*.
Em ambos os casos tem que colocar *.getId()* na frente para obter o *id* do álbum e da multmídia.

**Comment by PauloHenriqueAraujo** [comment]
A instrução SQL ficou um pouco grande pois usei "nomeDaTabela.nomeDoAtributo".

Fiz um teste aqui no papel a me parece estar certo a condição.

Se tiver algo errado, me comunique, se não, me passe outra atividade.





________________________________
De: Ronneesley Moura Teles <notifications@github.com>
Enviado: quinta-feira, 10 de agosto de 2017 07:14
Para: Ronneesley/redesocial
Cc: Paulo Henrique; Assign
Assunto: Re: [Ronneesley/redesocial] Criação do DAO para entidade PostagemMultimidia método alterar() (#85)


Paulo, fiz a alteração no protótipo que mencionei que seria necessária.
PostagemMultimidia dto, PostagemMultimidia dtoNovo
Agora são dois parâmetros.
Tente montar a condição de alteração correta e nas linhas 39 e 40 use os dados do dtoNovo.
Em ambos os casos tem que colocar .getId() na frente para obter o id do álbum e da multmídia.

**Comment by Ronneesley** [comment]
O SQL correto seria:
*update postagens_multimidias set postagem = ?, multimidia = ? where postagem = ? and multimidia = ?*
É mais simples do que pensou.
Veja no entanto que as linhas 39 e 40 preenchem apenas 2 sinais de interrogação, agora preencha os dois últimos com os dados do *dto*.

**Comment by PauloHenriqueAraujo** [comment]
Confere lá se tá ok

**Comment by Ronneesley** [comment]
Certinho.
