### ISSUE TITLE
Criação do DAO para entidade PostagemMultimidia método listar()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#86]

**Comment by Ronneesley** [comment]
Mais uma tarefa caso queira continuar pontuando.

**Comment by Macilon** [comment]
Rone, dê uma olhada no código que fez. Tem um erro na chave estrangeira da "multimidia" que não consegui encontrar.

**Comment by Ronneesley** [comment]
Na verdade o erro está no seu comando:
*pm.setMultimidia(**postagemDAO**.selecionar(rs.getInt("multimidia")));*

Se você deseja obter uma multimídia, não deveria pedir a um objeto de **PostagemDAO** e sim de **MultimidiaDAO**

**Comment by Macilon** [comment]
Foi feita a correção, depois dê uma olhada se ficou correto.

**Comment by Ronneesley** [comment]
Ok
