### ISSUE TITLE
Criação do DAO para entidade PostagemMultimidia método selecionar()

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#87]

**Comment by Ronneesley** [comment]
Mais uma tarefa caso queira continuar pontuando.

**Comment by thaliasantana** [comment]
Eu acho que está okay. Veja depois!

**Comment by Ronneesley** [comment]
Está quase bom mesmo. A grande questão é que esta entidade é um pouco diferente, ela tem duas chaves primárias e nenhuma delas chama-se *id*.
Modifiquei o protótipo do método agora recebendo dois parâmetros, que são as duas chaves primárias.
Tente montar a condição adequada do *where* agora e me avise quando terminar.

**Comment by thaliasantana** [comment]
Eu nem tinha olhado isso em cima kkk Não ia funcionar msm, pois não tem id, mas eu não sei como resolver. Coloquei as duas agora, mas bem, eu não sei se está certo.

**Comment by Ronneesley** [comment]
É isso mesmo, devem ter as duas colunas no *where* consequentemente tem que preencher dois interrogações.

**Comment by thaliasantana** [comment]
Então está pronto? Gente, que negócio doido esse! Uhu!

**Comment by Ronneesley** [comment]
Perfeito, agora só tirar o comentário * //a condição muda*
