### ISSUE TITLE
Criação do DAO para a classe Multimidia método inserir

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#9]

**Comment by Ronneesley** [comment]
Jonathan, aguardo a correção das validações. Quanto aos dados de mídia use setBytes e para data fiz um exemplo para ti.

**Comment by Ronneesley** [comment]
Jonathan, retire o código da linha 25 *System.out.print(m);*, ele serve apenas para testar algo, mas não pode ser mantido na versão final do sistema.
No comando SQL de inserção você está inserido os campos *id, midia, tipoConteudo, data*, veja que o *id* é um campo auto incremental, portanto é automático e não deve ser informado.
Já o campo tipo de conteúdo veja como ele é escrito no DER. Além disso no DER existe mais um campo lá que gostaria que olhasse novamente.
Como o *id* sai do SQL então a linha 35 também sai do código *pstmt.setInt(1, m.getId());*, em seguida as numerações dos sinais de interrogação mudam.

**Comment by Jonathanss123** [comment]
tem algumas coisas que não entendi, como na parte Validações ... vou tirar essas dúvidas com você hoje.

**Comment by Ronneesley** [comment]
Jonathan, veja no DER que o nome da tabela e das colunas estão errados na parte do código *multimidia(Album, midia, tipoConteudo, data)*, assim como a quantidade de parâmetros *values(?, ?, ?)* sendo 3 apenas enquanto está informando que 4 serão passados.

As linhas 27 a 29 estão com erro. Você acabou criando novos métodos na classe DTO *Multimidia*, no final do arquivo veja:

    public String tipoConteudo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public byte getmidia() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public int getAlbum() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

**Comment by Ronneesley** [comment]
Quanto as dúvidas de validações que vimos na última aula, sugiro a leitura dos textos a seguir:

1) https://docs.oracle.com/javase/tutorial/essential/exceptions/throwing.html
2) https://www.caelum.com.br/apostila-java-orientacao-objetos/excecoes-e-controle-de-erros/

O primeiro é a fonte oficial portanto a mais confiável de todas, porém em inglês. A segunda é de uma empresa que ministra vários cursos na área, caso tenha dificuldades com o inglês.

Espero que tenha ajudado.

**Comment by Jonathanss123** [comment]
Ronne fiz as alteração conforme foi pedido ...

**Comment by Ronneesley** [comment]
Está ficando muito bom, mas preciso que veja alguns detalhes ainda.
No insert *insert into multimidias(id, * o campo *id* é auto incremental portanto não deve ser informado.
Ainda no SQL não existe nenhuma coluna chamada *tipoConteudo*, veja no DER como é o nome real da coluna.
É só isso, após corrigir me avise.

**Comment by Jonathanss123** [comment]
Neste caso e so retirar o ID ? ...  E no DER tem a coluna tipo_Conteudo porem no DTO tem tipoConteudo ...

**Comment by Ronneesley** [comment]
Jonathan, estes ambientes são sensíveis ao caso, então não existe uma coluna chamada *tipo_Conteudo* e sim *tipo_conteudo*. Neste caso o que importa no String que você está montando é o nome da coluna no banco de dados, pois é para ele que o comando será enviado.
Note que a quantidade de interrogações: *(?, ?, ?, ?, ?)* está desproporcional a quantidade de parâmetros *(midia, tipoConteudo, data, album)*

**Comment by Jonathanss123** [comment]
Segue as correções pedidas ...

**Comment by Ronneesley** [comment]
Perfeito.
