### ISSUE TITLE
Criação do HTML para post de vídeo do youtube

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#90]

**Comment by PauloHenriqueAraujo** [comment]
O modelo diverge do protótipo pois o vídeo está como link (no protótipo).

**Comment by Ronneesley** [comment]
O HTML está perfeito, o protótipo foi só um rascunho mesmo.

**Comment by PauloHenriqueAraujo** [comment]
O Sr. se esqueceu de marcar a * pra mim no quadro de participação desta atividade em Design/construção das páginas.




________________________________
De: Ronneesley Moura Teles <notifications@github.com>
Enviado: sábado, 12 de agosto de 2017 11:41
Para: Ronneesley/redesocial
Cc: Paulo Henrique; Assign
Assunto: Re: [Ronneesley/redesocial] Criação do HTML para post de vídeo do youtube (#90)


O HTML está perfeito, o protótipo foi só um rascunho mesmo.

**Comment by Ronneesley** [comment]
De fato, continue acompanhando. Obrigado por perceber.
