### ISSUE TITLE
Protótipo do painel administrativo

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#92]

**Comment by thaliasantana** [comment]
Uma tela já foi pro Git. Demais membros poderão inserir mais modelos.

**Comment by Ronneesley** [comment]
Visualizado aguardo o parecer da equipe sobre qual é o final.

**Comment by LuckasAzevedo** [comment]
Foi discutido em grupo e vimos que o protótipo que mais esta "cobrindo as
necessidades"   do projeto  foi o protótipo submetido anteriormente.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-08-16 1:04 GMT-03:00 Ronneesley Moura Teles <notifications@github.com>:

**Comment by Ronneesley** [comment]
Tah mais cadê os outro? Já avia conversado com a Thalia e segundo ela aquele que está lá foi ela quem fez sozinha, então é fácil para a equipe concordar!

**Comment by LuckasAzevedo** [comment]
não consegui fazer o commit dos que eu fiz, porém enviar os arquivos para a
Thalia pra que ela envie pra mim!

Em 17 de agosto de 2017 18:01, Ronneesley Moura Teles <
notifications@github.com> escreveu:

**Comment by iankatalita** [comment]
Já mandei o meu, está na pasta protótipo em Painel ADM.

**Comment by adallberto** [comment]
Enviei o meu ta na pasta Protótipo em Painel ADM, com o nome PAINEL1

**Comment by iankatalita** [comment]
Terminamos.

**Comment by Ronneesley** [comment]
OK
