### ISSUE TITLE
Protótipo do 2°passo do cadastro de usuários

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#93]

**Comment by BrenerGomesSI** [comment]
Cadastro de Usuario Passo 2 e 3 completo.

**Comment by Ronneesley** [comment]
Ok, só não esqueça de mudar o nome.

**Comment by Ronneesley** [comment]
Você está devendo o arquivo editável do Pencil, esperarei ele até dia: 08/09, sob a condição de retirada da nota cedida e consideração de atraso.
