### ISSUE TITLE
Protótipo do 3° passo do cadastro de usuários

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#94]

**Comment by Lucianodcb** [comment]
Pronto

**Comment by Lucianodcb** [comment]
Se quiser passar mais alguma tarefa

**Comment by Ronneesley** [comment]
Oi Luciano, ainda há uns detalhes. Renomeie o arquivo "3° passo do cadastro de usuarios.epgz" para não ter espaços nem caracteres especiais. Mude também o nome da aba no Pencil. Depois exporte o arquivo para PNG na pasta resultados.

**Comment by Lucianodcb** [comment]
alterações feitas

**Comment by Ronneesley** [comment]
OK
