### ISSUE TITLE
Protótipo de resultado de busca de pessoas ou grupos

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#96]

**Comment by ghost** [comment]
Enviado aguardando correção

**Comment by ghost** [comment]
Enviei através do computador do Daniel, esqueci de deslogar aí o submit foi com o nome do Daniel

**Comment by Ronneesley** [comment]
Davi, você deve retirar o espaço excessivo do fundo da imagem.
Clicando com o botão oposto no palco você tem a opção de ajustar ao *canvas*.
A pasta correta para colocar os resultados é **resultados**.

**Comment by Ronneesley** [comment]
Não foi feito (2 semanas de atraso).

**Comment by ghost** [comment]
pronta!

**Comment by Ronneesley** [comment]
O palco ainda está grande, aguardo a correção.
