### ISSUE TITLE
Protótipo do cadastro de grupos de usuários

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#97]

**Comment by WesleyMFelix** [comment]
Atividade enviada!

**Comment by Ronneesley** [comment]
Wesley antes de fechar eu preciso que gere o PNG do protótipo.

**Comment by WesleyMFelix** [comment]
Enviado!

Em 10 de ago de 2017 9:11 AM, "Ronneesley Moura Teles" <
notifications@github.com> escreveu:

**Comment by Ronneesley** [comment]
Perfeito.
