### ISSUE TITLE
Protótipo da edição de perfil de usuário (sobre)

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#98]

**Comment by cybersecwoman** [comment]
Já está na pasta o arquivo do protótipo editar perfil e também uma versão do perfil com um botão de editar perfil (não tinha).

**Comment by Ronneesley** [comment]
Oi Anny, não encontrei a imagem na pasta **resultados**. Quando estiver exportado me avise.
Não crie outro arquivo **perfil com botão editar.epgz**, simplesmente salve sobre o arquivo original que é **perfil.epgz**

**Comment by cybersecwoman** [comment]
Prontinho.

**Comment by Ronneesley** [comment]
Anny, preciso que sempre que terminar exporte a imagem para PNG para a pasta resultados.
Além disso mude o nome da guia no Pencil para algo que represente o protótipo, atualmente está **Untitled Page**
No nome do arquivo, salve sem espaços e tudo minúsculo ex: editar_perfil.epgz, sugiro também editar_perfil no nome da guia.

Quanto a protótipo em si, gostaria que padronizasse o posicionamento dos títulos ou ao centro ou à esquerda. Os últimos dois estão em lugar diferente dos anteriores.
O alinhamento dos componentes não está bom, veja que os componentes formam uma cascata à direita.

Se o lápis serve para editar, então o conteúdo não deveria estar numa caixa de texto a não ser que a pessoa tenha clicado nele. Então deveria ser um rótulo e não uma caixa de texto.

Utilize a função "Fit content" para não gerar as bordas brancas na imagem, conforme comentei contigo, não quero uma imagem em A4 e sim uma imagem do tamanho necessário.

Aguardo as correções.

**Comment by cybersecwoman** [comment]
Arrumei lá, verifica se está tudo ok!

**Comment by Ronneesley** [comment]
No lugar da foto e à direita do topo, o que os lápis querem dizer?

**Comment by cybersecwoman** [comment]
Edição de foto de perfil e capa, acha melhor fazer alguma alteração?
